// research-archive-gen mechanically forks the sealed V25 native append.
// Only the admission predicate changes; receipt/readback/marker logic is kept.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
)

func main() {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "internal/store/libravdbstore/research_joined_journal_v25_test.go", nil, 0)
	if err != nil {
		panic(err)
	}
	changes := 0
	for _, d := range f.Decls {
		fn, ok := d.(*ast.FuncDecl)
		if !ok || fn.Name.Name != "appendJoinedJournalV25" {
			continue
		}
		fn.Name.Name = "appendArchiveJournalV29"
		typ, err := parser.ParseExpr("func(model.BayesianJournalEntry, model.Snapshot) bool")
		if err != nil {
			panic(err)
		}
		fn.Type.Params.List = append(fn.Type.Params.List, &ast.Field{Names: []*ast.Ident{ast.NewIdent("admit")}, Type: typ})
		ast.Inspect(fn.Body, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}
			sel, ok := call.Fun.(*ast.SelectorExpr)
			if !ok || sel.Sel.Name != "JournalSnapshotCompatible" {
				return true
			}
			id, ok := sel.X.(*ast.Ident)
			if !ok || id.Name != "store" || len(call.Args) != 4 {
				panic("unexpected admission AST")
			}
			call.Fun = ast.NewIdent("admit")
			call.Args = call.Args[:2]
			call.Args[0] = ast.NewIdent("entry")
			changes++
			return true
		})
	}
	if changes != 1 {
		panic(fmt.Sprintf("admission changes=%d", changes))
	}
	// Reuse the sealed V25 item type rather than redeclaring it in this package.
	decls := f.Decls[:0]
	for _, d := range f.Decls {
		g, ok := d.(*ast.GenDecl)
		if ok && g.Tok == token.TYPE {
			continue
		}
		decls = append(decls, d)
	}
	f.Decls = decls
	var b bytes.Buffer
	b.WriteString("// Code generated by research-archive-gen; DO NOT EDIT.\n// V25 persistence is unchanged. Admission requires a sealed historical capture.\n")
	if err := format.Node(&b, fset, f); err != nil {
		panic(err)
	}
	data, err := format.Source(b.Bytes())
	if err != nil {
		panic(err)
	}
	// Only this test-only generated file is writable; old frozen files stay intact.
	if err := os.WriteFile("internal/store/libravdbstore/research_archive_journal_v29_generated_test.go", data, 0600); err != nil {
		panic(err)
	}
}
