import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';
const sources={},outputs={},hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const read=p=>{const b=fs.readFileSync(p);sources[p]=hash(b);return b.toString();};
const sub=(s,a,b)=>{assert(s.includes(a),a);return s.replaceAll(a,()=>b);};
function save(p,s){fs.mkdirSync(p.slice(0,p.lastIndexOf('/')),{recursive:true,mode:0o700});if(p.endsWith('.go'))s=execFileSync('gofmt',[],{input:s,encoding:'utf8'});if(fs.existsSync(p))assert.equal(fs.readFileSync(p,'utf8'),s);else fs.writeFileSync(p,s,{flag:'wx',mode:0o600});outputs[p]=hash(s);}
for(const name of ['model.go','memo_v49.go']){
 let s=read('internal/researchmoment/'+name);s=sub(s,'researchmoment','researchnoisemoment');
 s=sub(s,'cfg.Hazard >= 1','cfg.Hazard >= 1 || !finite(cfg.Noise) || cfg.Noise < 0 || cfg.Noise >= .5');
 if(name==='model.go'){
  s=sub(s,'Strength, Hazard float64','Strength, Hazard float64\n Noise float64');
  s=sub(s,'p := atom(z)','p := m.cfg.Noise + (1-2*m.cfg.Noise)*atom(z)');
  s=sub(s,'// Package researchnoisemoment tests declared-mean finite priors in isolation.','// Package researchnoisemoment separates latent usefulness from noisy labels.');
 }
 save('internal/researchnoisemoment/'+name.replace('.go','_generated.go'),'// Code generated by noise-v53-gen.mjs; DO NOT EDIT.\n'+s);
}
let s=read('internal/researchmomentref/reference.go');s=sub(s,'researchmoment','researchnoisemoment');
s=sub(s,'cfg.Hazard >= 1','cfg.Hazard >= 1 || math.IsNaN(cfg.Noise) || math.IsInf(cfg.Noise,0) || cfg.Noise < 0 || cfg.Noise >= .5');
s=sub(s,'\t\t\t\t\ta := (float64(z) + .5) / 21\n\t\t\t\t\tif r.yes','\t\t\t\t\tp := (float64(z) + .5) / 21\n\t\t\t\t\ta := (1-r.cfg.Noise)*p + r.cfg.Noise*(1-p)\n\t\t\t\t\tif r.yes');
save('internal/researchnoisemomentref/reference_generated.go','// Code generated by noise-v53-gen.mjs; DO NOT EDIT.\n'+s);
for(const[p,h]of Object.entries(sources))assert.equal(hash(fs.readFileSync(p)),h);
save('research/noise-v53-generation.json',JSON.stringify({sources,outputs,originalSourcesUnchanged:true,cleanMarginalUnchanged:true,emissionChannelAdded:true},null,2)+'\n');
