// Mechanical, exclusive new-source generation. Original research remains intact.
import fs from 'node:fs';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'), sources={}, outputs={};
const previous=fs.existsSync('research/scored-v52-generation.json')?JSON.parse(fs.readFileSync('research/scored-v52-generation.json')):null;
function read(p){const b=fs.readFileSync(p);sources[p]=sha(b);return b.toString();}
function sub(s,a,b){assert(s.includes(a),'missing transformation '+a);return s.replaceAll(a,b);}
function save(p,s){if(p.endsWith('.go'))s=execFileSync('gofmt',[],{input:s,encoding:'utf8'});if(fs.existsSync(p)){const old=fs.readFileSync(p);if(old.toString()!==s){assert.equal(process.env.EVENTFRAME_V52_PREFLIGHT_REPAIR,'1','existing generated source differs '+p);assert(previous,'owned generation proof required');assert.equal(sha(old),p==='research/scored-v52-generation.json'?sha(JSON.stringify(previous,null,2)+'\n'):previous.outputs[p],'owned old hash '+p);fs.writeFileSync(p,s,{mode:0o600});}}else fs.writeFileSync(p,s,{flag:'wx',mode:0o600});outputs[p]=sha(s);}
let s=read('internal/researchswitch/local_pool_v47.go');
s=sub(s,'LocalPool','scoreLocalV52');s=sub(s,'LocalTicket','scoreLocalTicketV52');s=sub(s,'poolRow','scoreLocalRowV52');
s=sub(s,'*Model','*scoreModelV51');
s=sub(s,'memberTrials int, epoch uint64)','memberTrials int, epoch uint64, mode string)');
s=sub(s,'\tpoison         bool','\tpoison         bool\n\tmode           string');
s=sub(s,'New(local, epoch)','newScoreV51(scoreConfigV51{Prior: local.Prior, Hazard: local.Hazard, Trials: local.Trials, Pending: local.Pending, Mode: mode}, epoch)');
s=sub(s,'researchmoment.New(base','researchmoment.NewMemoV49(base');
s=sub(s,'epoch: epoch}, nil','epoch: epoch, mode: mode}, nil');
s=sub(s,'var receipt Receipt','var receipt scoreReceiptV51');
s=sub(s,'PoolReceipt{receipt, r.member','PoolReceipt{Receipt(receipt), r.member');
s=sub(s,'p.memberTrials, epoch)','p.memberTrials, epoch, p.mode)');
s += '\n// Rows own child tickets and the task-local original-position score ticket.\ntype scoreLocalRowV52 struct {\nfull, adaptive researchdispersion.DelayedTicket\nmoment researchmoment.Ticket\nmix scoreTicketV51\nmember, ordinal int\nat int64\nstatus uint8\n}\n';
save('internal/researchswitch/scored_local_v52_generated.go','// Code generated by scored-v52-gen.mjs; DO NOT EDIT.\n'+s);
s=read('internal/researchswitch/scored_hybrid_v51.go');
s=sub(s,'ScoredHybridV51','ScoredHybridV52');s=sub(s,'ScoredHybridTicketV51','ScoredHybridTicketV52');
s=sub(s,'*LocalPool','*scoreLocalV52');s=sub(s,'LocalTicket','scoreLocalTicketV52');
s=sub(s,'*compactModelV48','*scoreModelV51');s=sub(s,'compactTicketV48','scoreTicketV51');
s=sub(s,'newCompactV48(compactConfigV48(globalCfg), epoch)','newScoreV51(scoreConfigV51{Prior: globalCfg.Prior, Hazard: globalCfg.Hazard, Trials: globalCfg.Trials, Pending: globalCfg.Pending, Mode: mode}, epoch)');
s=sub(s,'newMemoLocalV49(base, cfg, memberTrials, epoch)','NewscoreLocalV52(base, cfg, memberTrials, epoch, mode)');
s=sub(s,'// ScoredHybridV52 changes only the served outer head. The original local/global\n// heads and child learners retain their advice/update contracts. Nested loss\n// weights do not assert multiple independent Bayesian uses of one observation.','// ScoredHybridV52 aligns all mixture heads, not the statistical child learners.\n// Nested strategy weights do not assert independent Bayesian evidence copies.');
save('internal/researchswitch/scored_hybrid_v52_generated.go','// Code generated by scored-v52-gen.mjs; DO NOT EDIT.\n'+s);
for(const kind of ['collector','audit']){
 const p=`internal/researchswitch/scored_${kind}_v51_generated_test.go`;
 s=read(p);s=sub(s,'research-scored-study-gen','scored-v52-gen.mjs');
 s=sub(s,'ScoredV51','ScoredV52');s=s.replaceAll('ScoredHybridV51','ScoredHybridV52').replaceAll('ScoredHybridTicketV51','ScoredHybridTicketV52');
 if(kind==='audit'){
  s=sub(s,'\n\t"github.com/JuanHuaXu/eventframed/internal/researchswitchref"','');
  s=sub(s,'researchswitchref.EndWeights(prior, 1./16, tapes[m], known[m])','scoreHeadWeightsV52(prior, 1./16, tapes[m], known[m], style)');
  s=sub(s,'researchswitchref.EndWeights(prior, 1./2400, globalTape, globalKnown)','scoreHeadWeightsV52(prior, 1./2400, globalTape, globalKnown, style)');
  s=sub(s,'\n\t\t\tfor h := range heads {','\n\t\t\theads[0], err = researchscoreref.Forecast(gw[:], a.Advice[tick][:], style)\n\t\t\tif err != nil { return err }\n\t\t\theads[1], err = researchscoreref.Forecast(w[:], a.Advice[tick][:], style)\n\t\t\tif err != nil { return err }\n\t\t\tfor h := range heads {');
  // The snapshot loop is deeper; do not reuse issue-time advice here.
  s=sub(s,'\n\t\t\t\tfor h := range heads {','\n\t\t\t\theads[0], err = researchscoreref.Forecast(gw[:], snap.Advice[m][:], style)\n\t\t\t\tif err != nil { return err }\n\t\t\t\theads[1], err = researchscoreref.Forecast(w[:], snap.Advice[m][:], style)\n\t\t\t\tif err != nil { return err }\n\t\t\t\tfor h := range heads {');
  s += '\nfunc scoreHeadWeightsV52(prior []float64, hazard float64, tape [][3]float64, known map[int]bool, style string) ([3]float64, error) {\n dense:=make([][]float64,len(tape)); for j:=range tape { dense[j]=tape[j][:] };\n w,err:=researchscoreref.End(prior,hazard,dense,known,style);var out [3]float64;copy(out[:],w);return out,err\n}\n';
 }
 save(`internal/researchswitch/scored_${kind}_v52_generated_test.go`,s);
}
for(const kind of ['study','fixture_checks','allocation']){
 s=read(`internal/researchswitch/scored_${kind}_v51_test.go`);
 s=sub(s,'ScoredV51','ScoredV52');s=s.replaceAll('ScoredHybridV51','ScoredHybridV52');
 s=s.replaceAll('validScoredStudyStyleV51','validScoredStudyStyleV52').replaceAll('auditScoredStreamV51','auditScoredStreamV52');
 s=sub(s,'SCORED_V51','SCORED_V52');s=s.replaceAll('2026105107','2026105207');
 save(`internal/researchswitch/scored_${kind}_v52_generated_test.go`,'// Code generated by scored-v52-gen.mjs; DO NOT EDIT.\n'+s);
}
s=read('internal/researchdispersion/scored_fixture_v51_generated_test.go');
s=sub(s,'research-scored-fixture-gen','scored-v52-gen.mjs');s=sub(s,'ScoredV51','ScoredV52');s=sub(s,'scoredCohortV51','scoredCohortV52');s=sub(s,'SCORED_V51','SCORED_V52');
s=sub(s,'2026105107, 1','2026105207, 1');s=sub(s,'2026105109, 16','2026105209, 16');s=sub(s,'2026105111, 16','2026105211, 16');
s=sub(s,'2026105107, 2026105109, 2026105111}','2026105107, 2026105109, 2026105111, 2026105207, 2026105209, 2026105211}');
save('internal/researchdispersion/scored_fixture_v52_generated_test.go',s);
for(const[p,h]of Object.entries(sources))assert.equal(sha(fs.readFileSync(p)),h);
save('research/scored-v52-generation.json',JSON.stringify({sources,outputs,originalSourcesUnchanged:true,allThreeMixtureHeads:true,childLearnersUnchanged:true},null,2)+'\n');
