// Clone only the sealed load body; storage wrappers define the new factor.
package main

import (
	"bytes"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"strconv"
)

func main() {
	f, err := parser.ParseFile(token.NewFileSet(), "internal/store/libravdbstore/research_metadata_projection_load_v35_generated_test.go", nil, 0)
	if err != nil {
		panic(err)
	}
	renames := map[string]string{"runMetadataProjectionLoadV35": "runMetadataCoreLoadV36", "TestResearchMetadataProjectionLoadV35": "TestResearchMetadataCoreLoadV36", "attachLoadProjectionV35": "attachLoadCoreV36", "finishProjectionTrialV35": "finishCoreTrialV36", "closeV35": "closeV36", "projectionTrialV35": "coreTrialV36"}
	ast.Inspect(f, func(n ast.Node) bool {
		if id, ok := n.(*ast.Ident); ok {
			if name, ok := renames[id.Name]; ok {
				id.Name = name
			}
		}
		if l, ok := n.(*ast.BasicLit); ok && l.Kind == token.STRING {
			v, _ := strconv.Unquote(l.Value)
			if v == "EVENTFRAME_METADATA_PROJECTION_V35_OUTPUT" {
				l.Value = strconv.Quote("EVENTFRAME_METADATA_CORE_V36_OUTPUT")
			}
			if v == "../../../research/metadata-projection-v35/freeze.json" {
				l.Value = strconv.Quote("../../../research/metadata-core-v36/freeze.json")
			}
		}
		return true
	})
	var b bytes.Buffer
	if err = format.Node(&b, token.NewFileSet(), f); err != nil {
		panic(err)
	}
	data, err := format.Source(b.Bytes())
	if err != nil {
		panic(err)
	}
	if err = os.WriteFile("internal/store/libravdbstore/research_metadata_core_load_v36_generated_test.go", append([]byte("// Code generated by research-metadata-core-gen; DO NOT EDIT.\n"), data...), 0600); err != nil {
		panic(err)
	}
}
