// Mechanical collector fork: only constructor and function names may change.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
)

func main() {
	const source = "internal/researchswitch/hybrid_study_v48_test.go"
	const dest = "internal/researchswitch/memo_collector_v49_generated_test.go"
	b, e := os.ReadFile(source)
	must(e)
	fset := token.NewFileSet()
	f, e := parser.ParseFile(fset, source, b, 0)
	must(e)
	var fn *ast.FuncDecl
	for _, d := range f.Decls {
		if x, ok := d.(*ast.FuncDecl); ok && x.Name.Name == "collectHybridV48" {
			fn = x
		}
	}
	if fn == nil {
		panic("missing original collector")
	}
	var original bytes.Buffer
	must(format.Node(&original, fset, fn))
	names := map[string]string{"collectHybridV48": "collectMemoV49", "NewHybridPool": "NewMemoHybridV49"}
	counts := map[string]int{}
	ast.Inspect(fn, func(n ast.Node) bool {
		if x, ok := n.(*ast.Ident); ok {
			if name, ok := names[x.Name]; ok {
				counts[x.Name]++
				x.Name = name
			}
		}
		return true
	})
	if counts["collectHybridV48"] != 1 || counts["NewHybridPool"] != 1 {
		panic("unexpected rewrite cardinality")
	}
	var output bytes.Buffer
	output.WriteString("// Code generated by research-memo-collector-gen; DO NOT EDIT.\npackage researchswitch\nimport \"time\"\n")
	must(format.Node(&output, fset, fn))
	out, e := format.Source(output.Bytes())
	must(e)
	ast.Inspect(fn, func(n ast.Node) bool {
		if x, ok := n.(*ast.Ident); ok {
			for old, name := range names {
				if x.Name == name {
					x.Name = old
				}
			}
		}
		return true
	})
	var inverse bytes.Buffer
	must(format.Node(&inverse, fset, fn))
	if !bytes.Equal(original.Bytes(), inverse.Bytes()) {
		panic("inverse collector changed")
	}
	w, e := os.OpenFile(dest, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600)
	must(e)
	_, e = w.Write(out)
	must(e)
	must(w.Sync())
	must(w.Close())
	report := map[string]any{"source": source, "sourceSHA256": fmt.Sprintf("%x", sha256.Sum256(b)), "destination": dest, "destinationSHA256": fmt.Sprintf("%x", sha256.Sum256(out)), "rewrites": counts, "inverseEqual": true}
	r, e := json.MarshalIndent(report, "", "  ")
	must(e)
	w, e = os.OpenFile("research/memo-v49-generation.json", os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600)
	must(e)
	_, e = w.Write(append(r, '\n'))
	must(e)
	must(w.Sync())
	must(w.Close())
}
func must(e error) {
	if e != nil {
		panic(e)
	}
}
