// Mechanically preserve V26 offered workload/gates; change only attachment and
// archive diagnostics. Controls remain joined+scheduled, rather than unscheduled.
package main

import (
	"bytes"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"strconv"
)

func main() {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "internal/store/libravdbstore/research_combined_witness_v26_load_test.go", nil, 0)
	if err != nil {
		panic(err)
	}
	ast.Inspect(f, func(n ast.Node) bool {
		if id, ok := n.(*ast.Ident); ok {
			switch id.Name {
			case "runCombinedWitnessLoadV26":
				id.Name = "runBatchArchiveLoadV33"
			case "TestResearchCombinedWitnessLoadV26":
				id.Name = "TestResearchBatchArchiveLoadV33"
			case "attachCombinedV26":
				id.Name = "attachLoadArchiveV33"
			}
		}
		if lit, ok := n.(*ast.BasicLit); ok && lit.Kind == token.STRING {
			value, _ := strconv.Unquote(lit.Value)
			switch value {
			case "EVENTFRAME_COMBINED_WITNESS_V26_OUTPUT":
				lit.Value = strconv.Quote("EVENTFRAME_BATCH_ARCHIVE_V33_OUTPUT")
			case "../../../research/combined-witness-v26/freeze.json":
				lit.Value = strconv.Quote("../../../research/batch-archive-v33/freeze.json")
			}
		}
		return true
	})
	for _, d := range f.Decls {
		fn, ok := d.(*ast.FuncDecl)
		if !ok || fn.Name.Name != "runBatchArchiveLoadV33" {
			continue
		}
		fn.Type.Results.List[0].Type = ast.NewIdent("archiveTrialV33")
		ast.Inspect(fn.Body, func(n ast.Node) bool {
			if kv, ok := n.(*ast.KeyValueExpr); ok {
				if key, ok := kv.Key.(*ast.Ident); ok && key.Name == "Scheduled" {
					kv.Value = ast.NewIdent("true")
				}
			}
			if ret, ok := n.(*ast.ReturnStmt); ok && len(ret.Results) == 1 {
				if _, ok := ret.Results[0].(*ast.CompositeLit); ok {
					ret.Results[0] = &ast.CallExpr{Fun: ast.NewIdent("finishArchiveTrialV33"), Args: []ast.Expr{ast.NewIdent("s"), ret.Results[0]}}
				}
			}
			return true
		})
		// f.close closes native fixtures, not the new worker. Add a worker Close
		// after attachment, deferred AFTER f.close so it drains before native teardown.
		for i, stmt := range fn.Body.List {
			assign, ok := stmt.(*ast.AssignStmt)
			if !ok || len(assign.Rhs) != 1 {
				continue
			}
			call, ok := assign.Rhs[0].(*ast.CallExpr)
			if !ok {
				continue
			}
			id, ok := call.Fun.(*ast.Ident)
			if !ok || id.Name != "attachLoadArchiveV33" {
				continue
			}
			deferClose := &ast.DeferStmt{Call: &ast.CallExpr{Fun: &ast.SelectorExpr{X: ast.NewIdent("s"), Sel: ast.NewIdent("closeV33")}}}
			fn.Body.List = append(fn.Body.List[:i+1], append([]ast.Stmt{deferClose}, fn.Body.List[i+1:]...)...)
			break
		}
	}
	var b bytes.Buffer
	if err := format.Node(&b, fset, f); err != nil {
		panic(err)
	}
	data, err := format.Source(b.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("internal/store/libravdbstore/research_batch_archive_load_v33_generated_test.go", append([]byte("// Code generated by research-batch-archive-gen; DO NOT EDIT.\n"), data...), 0600); err != nil {
		panic(err)
	}
}
