// Fork only the archival commit's operation-timeout placement and its tests.
package main

import (
	"bytes"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
)

func save(fset *token.FileSet, f *ast.File, path string) {
	var b bytes.Buffer
	if err := format.Node(&b, fset, f); err != nil {
		panic(err)
	}
	out, err := format.Source(b.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile(path, append([]byte("// Code generated by research-archive-timeout-gen; DO NOT EDIT.\n"), out...), 0600); err != nil {
		panic(err)
	}
}
func main() {
	fset := token.NewFileSet()
	source, err := parser.ParseFile(fset, "internal/store/libravdbstore/research_archive_witness_v29_test.go", nil, 0)
	if err != nil {
		panic(err)
	}
	var commit *ast.FuncDecl
	for _, d := range source.Decls {
		if fn, ok := d.(*ast.FuncDecl); ok && fn.Name.Name == "commit" {
			commit = fn
		}
	}
	if commit == nil {
		panic("missing sealed commit")
	}
	commit.Name.Name = "commitV31"
	addition, err := parser.ParseFile(token.NewFileSet(), "addition", "package p; import(\"context\";\"time\"); func f(){ctx,cancel:=context.WithTimeout(ctx,500*time.Millisecond);defer cancel()}", 0)
	if err != nil {
		panic(err)
	}
	statements := addition.Decls[1].(*ast.FuncDecl).Body.List
	commit.Body.List = append(commit.Body.List[:2], append(statements, commit.Body.List[2:]...)...)
	header, err := parser.ParseFile(token.NewFileSet(), "header", "package libravdbstore; import(\"context\";\"database/sql\";\"encoding/json\";\"errors\";\"fmt\";\"time\";\"github.com/JuanHuaXu/eventframed/internal/model\";\"github.com/JuanHuaXu/eventframed/internal/store\")", 0)
	if err != nil {
		panic(err)
	}
	header.Decls = append(header.Decls, commit)
	save(token.NewFileSet(), header, "internal/store/libravdbstore/research_archive_commit_v31_generated_test.go")
	tests, err := parser.ParseFile(fset, "internal/store/libravdbstore/research_archive_lifecycle_v30_test.go", nil, 0)
	if err != nil {
		panic(err)
	}
	ast.Inspect(tests, func(n ast.Node) bool {
		if id, ok := n.(*ast.Ident); ok {
			switch id.Name {
			case "attachArchiveV29":
				id.Name = "attachArchiveV31"
			case "TestResearchArchiveInterruptionV30":
				id.Name = "TestResearchArchiveInterruptionV31"
			case "TestResearchArchiveConcurrentV30":
				id.Name = "TestResearchArchiveConcurrentV31"
			case "TestResearchArchiveOwnershipV30":
				id.Name = "TestResearchArchiveOwnershipV31"
			}
		}
		return true
	})
	// Preserve old environment variable in the cloned lifecycle tests. Runners
	// select test names explicitly; V30 failure artifacts are never overwritten.
	save(fset, tests, "internal/store/libravdbstore/research_archive_lifecycle_v31_generated_test.go")
}
