// Transform the complete original workload using Go's parser, not text edits.
package main

import (
	"bytes"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"strconv"
)

func main() {
	f, err := parser.ParseFile(token.NewFileSet(), "internal/store/libravdbstore/research_warm_search_load_v37_generated_test.go", nil, 0)
	if err != nil {
		panic(err)
	}
	renames := map[string]string{"runWarmSearchLoadV37": "runEagerLoadV44", "TestResearchWarmSearchLoadV37": "TestResearchEagerLoadV44", "warmTrialV37": "eagerTrialV44", "finishWarmTrialV37": "finishEagerTrialV44", "attachLoadWarmV37": "attachLoadEagerV44"}
	attachments, invocations, factors, signatures := 0, 0, 0, 0
	ast.Inspect(f, func(n ast.Node) bool {
		if decl, ok := n.(*ast.FuncDecl); ok && decl.Name.Name == "runWarmSearchLoadV37" {
			decl.Type.Params.List = append(decl.Type.Params.List, &ast.Field{Names: []*ast.Ident{ast.NewIdent("eager")}, Type: ast.NewIdent("bool")})
			signatures++
		}
		if call, ok := n.(*ast.CallExpr); ok {
			if id, ok := call.Fun.(*ast.Ident); ok {
				if id.Name == "attachLoadWarmV37" {
					if len(call.Args) != 3 {
						panic("attachment arity")
					}
					call.Args = append(call.Args, ast.NewIdent("eager"))
					attachments++
				}
				if id.Name == "runWarmSearchLoadV37" {
					if len(call.Args) != 4 {
						panic("invocation arity")
					}
					call.Args = append(call.Args, ast.NewIdent("eager"))
					invocations++
				}
			}
		}
		if loop, ok := n.(*ast.RangeStmt); ok {
			if id, ok := loop.Value.(*ast.Ident); ok && id.Name == "mode" {
				lit, ok := loop.X.(*ast.CompositeLit)
				if !ok || len(lit.Elts) != 4 {
					panic("original storage factor")
				}
				lit.Elts = []ast.Expr{&ast.UnaryExpr{Op: token.SUB, X: &ast.BasicLit{Kind: token.INT, Value: "2"}}, &ast.BasicLit{Kind: token.INT, Value: "4"}}
				loop.Body = &ast.BlockStmt{List: []ast.Stmt{&ast.RangeStmt{Key: ast.NewIdent("_"), Value: ast.NewIdent("eager"), Tok: token.DEFINE, X: &ast.CompositeLit{Type: &ast.ArrayType{Elt: ast.NewIdent("bool")}, Elts: []ast.Expr{ast.NewIdent("false"), ast.NewIdent("true")}}, Body: loop.Body}}}
				factors++
			}
		}
		if id, ok := n.(*ast.Ident); ok {
			if name, ok := renames[id.Name]; ok {
				id.Name = name
			}
		}
		if lit, ok := n.(*ast.BasicLit); ok && lit.Kind == token.STRING {
			value, _ := strconv.Unquote(lit.Value)
			if value == "EVENTFRAME_WARM_SEARCH_V37_OUTPUT" {
				lit.Value = strconv.Quote("EVENTFRAME_EAGER_LOAD_V44_OUTPUT")
			}
			if value == "../../../research/warm-search-v37/freeze.json" {
				lit.Value = strconv.Quote("../../../research/eager-load-v44/freeze.json")
			}
		}
		return true
	})
	if attachments != 1 || invocations != 1 || factors != 1 || signatures != 1 {
		panic("transformation coverage")
	}
	var buf bytes.Buffer
	if err = format.Node(&buf, token.NewFileSet(), f); err != nil {
		panic(err)
	}
	data, err := format.Source(buf.Bytes())
	if err != nil {
		panic(err)
	}
	out := "internal/store/libravdbstore/research_eager_load_v44_generated_test.go"
	fd, err := os.OpenFile(out, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600)
	if err != nil {
		panic(err)
	}
	defer fd.Close()
	if _, err = fd.Write(append([]byte("// Code generated by research-eager-load-gen; DO NOT EDIT.\n"), data...)); err != nil {
		panic(err)
	}
	if err = fd.Sync(); err != nil {
		panic(err)
	}
}
