// Preserve sealed getter and workload semantics except explicit view substitution.
package main

import (
	"bytes"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"strconv"
)

func expr(n ast.Node) string {
	if n == nil {
		return ""
	}
	var b bytes.Buffer
	if err := format.Node(&b, token.NewFileSet(), n); err != nil {
		panic(err)
	}
	return b.String()
}
func body(src string) []ast.Stmt {
	f, e := parser.ParseFile(token.NewFileSet(), "snippet", "package p\nfunc snippet(){"+src+"}", 0)
	if e != nil {
		panic(e)
	}
	return f.Decls[0].(*ast.FuncDecl).Body.List
}
func save(f *ast.File, path string) {
	var b bytes.Buffer
	if err := format.Node(&b, token.NewFileSet(), f); err != nil {
		panic(err)
	}
	data, err := format.Source(b.Bytes())
	if err != nil {
		panic(err)
	}
	if err = os.WriteFile(path, append([]byte("// Code generated by research-metadata-projection-gen; DO NOT EDIT.\n"), data...), 0600); err != nil {
		panic(err)
	}
}
func main() {
	f, e := parser.ParseFile(token.NewFileSet(), "internal/store/libravdbstore/research_durable_witness_v23_test.go", nil, 0)
	if e != nil {
		panic(e)
	}
	out, e := parser.ParseFile(token.NewFileSet(), "header", `package libravdbstore
import("context";"reflect";"github.com/JuanHuaXu/eventframed/internal/model")`, 0)
	if e != nil {
		panic(e)
	}
	kept := 0
	for _, d := range f.Decls {
		fn, ok := d.(*ast.FuncDecl)
		if !ok {
			continue
		}
		switch fn.Name.Name {
		case "GetSelectionCertificate", "GetOmittedInfluenceCertificate", "GetBayesianPosterior":
		default:
			continue
		}
		fn.Recv.List[0].Type = &ast.StarExpr{X: ast.NewIdent("projectionStoreV35")}
		args := ""
		for _, p := range fn.Type.Params.List {
			for _, id := range p.Names {
				if args != "" {
					args += ","
				}
				args += id.Name
			}
		}
		resultType := expr(fn.Type.Results.List[0].Type)
		key := `""`
		if fn.Name.Name == "GetBayesianPosterior" {
			key = "key"
		}
		trace := `s.traceGetterV35(ctx,` + strconv.Quote(fn.Name.Name) + `,` + key + `,err)`
		pre := body(`pin, projected, projectionErr := s.pinV35(ctx); if projectionErr != nil { return ` + resultType + `{},projectionErr }; if !projected { value, err := s.authority.` + fn.Name.Name + `(` + args + `); s.markOwnerResultV35(err); ` + trace + `; return value,err }; s.projectedGets.Add(1)`)
		var statements []ast.Stmt
		locks := 0
		for _, stmt := range fn.Body.List {
			if x, ok := stmt.(*ast.ExprStmt); ok && expr(x.X) == "s.owner.Lock()" {
				locks++
				continue
			}
			if x, ok := stmt.(*ast.DeferStmt); ok && expr(x.Call) == "s.owner.Unlock()" {
				locks++
				statements = append(statements, body(`s.nativeSuccess.Add(1)`)...)
				continue
			}
			statements = append(statements, stmt)
			if a, ok := stmt.(*ast.AssignStmt); ok && len(a.Rhs) == 1 {
				if call, ok := a.Rhs[0].(*ast.CallExpr); ok && expr(call.Fun) == "s.EventStore."+fn.Name.Name {
					statements = append(statements, body(trace)...)
				}
			}
		}
		if locks != 2 {
			panic("wrong getter owner count")
		}
		fn.Body.List = statements
		ast.Inspect(fn.Body, func(n ast.Node) bool {
			if sel, ok := n.(*ast.SelectorExpr); ok && expr(sel.X) == "s" {
				switch sel.Sel.Name {
				case "EventStore", "transports":
					sel.X = &ast.SelectorExpr{X: ast.NewIdent("s"), Sel: ast.NewIdent("authority")}
				case "state":
					sel.X = ast.NewIdent("pin")
				}
			}
			if call, ok := n.(*ast.CallExpr); ok && expr(call.Fun) == "s.compatibleV23" {
				call.Fun = &ast.SelectorExpr{X: ast.NewIdent("s"), Sel: ast.NewIdent("compatibleV35")}
				call.Args = append(call.Args[:1], append([]ast.Expr{ast.NewIdent("pin")}, call.Args[1:]...)...)
			}
			return true
		})
		fn.Body.List = append(pre, fn.Body.List...)
		out.Decls = append(out.Decls, fn)
		kept++
	}
	if kept != 3 {
		panic("getter coverage gap")
	}
	save(out, "internal/store/libravdbstore/research_metadata_getters_v35_generated_test.go")
	f, e = parser.ParseFile(token.NewFileSet(), "internal/store/libravdbstore/research_archive_cost_load_v34_generated_test.go", nil, 0)
	if e != nil {
		panic(e)
	}
	renames := map[string]string{"runBatchArchiveLoadV34": "runMetadataProjectionLoadV35", "TestResearchBatchArchiveLoadV34": "TestResearchMetadataProjectionLoadV35", "attachLoadArchiveV34": "attachLoadProjectionV35", "closeV34": "closeV35", "finishArchiveTrialV34": "finishProjectionTrialV35", "archiveTrialV34": "projectionTrialV35"}
	ast.Inspect(f, func(n ast.Node) bool {
		if id, ok := n.(*ast.Ident); ok {
			if name, ok := renames[id.Name]; ok {
				id.Name = name
			}
		}
		if l, ok := n.(*ast.BasicLit); ok && l.Kind == token.STRING {
			v, _ := strconv.Unquote(l.Value)
			if v == "EVENTFRAME_ARCHIVE_COST_V34_OUTPUT" {
				l.Value = strconv.Quote("EVENTFRAME_METADATA_PROJECTION_V35_OUTPUT")
			}
			if v == "../../../research/archive-cost-v34/freeze.json" {
				l.Value = strconv.Quote("../../../research/metadata-projection-v35/freeze.json")
			}
		}
		if kv, ok := n.(*ast.KeyValueExpr); ok && expr(kv.Key) == `"Trials"` {
			kv.Value = &ast.BasicLit{Kind: token.INT, Value: "16"}
		}
		if r, ok := n.(*ast.RangeStmt); ok && expr(r.Value) == "mode" {
			r.X = &ast.CompositeLit{Type: &ast.ArrayType{Elt: ast.NewIdent("int")}, Elts: []ast.Expr{&ast.UnaryExpr{Op: token.SUB, X: &ast.BasicLit{Kind: token.INT, Value: "1"}}, &ast.UnaryExpr{Op: token.SUB, X: &ast.BasicLit{Kind: token.INT, Value: "2"}}, &ast.BasicLit{Kind: token.INT, Value: "3"}, &ast.BasicLit{Kind: token.INT, Value: "4"}}}
		}
		return true
	})
	save(f, "internal/store/libravdbstore/research_metadata_projection_load_v35_generated_test.go")
}
