// Generate an isolated factorial fork; sealed V33 remains unchanged.
package main

import (
	"bytes"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"strconv"
	"strings"
)

func body(src string) []ast.Stmt {
	f, err := parser.ParseFile(token.NewFileSet(), "snippet", "package p\nfunc snippet(){"+src+"}", 0)
	if err != nil {
		panic(err)
	}
	return f.Decls[0].(*ast.FuncDecl).Body.List
}
func parse(path string) (*token.FileSet, *ast.File) {
	set := token.NewFileSet()
	f, err := parser.ParseFile(set, path, nil, 0)
	if err != nil {
		panic(err)
	}
	ast.Inspect(f, func(n ast.Node) bool {
		if id, ok := n.(*ast.Ident); ok && strings.HasSuffix(id.Name, "V33") {
			id.Name = strings.TrimSuffix(id.Name, "V33") + "V34"
		}
		if lit, ok := n.(*ast.BasicLit); ok && lit.Kind == token.STRING {
			v, _ := strconv.Unquote(lit.Value)
			if strings.Contains(v, "BATCH_ARCHIVE_V33") {
				lit.Value = strconv.Quote(strings.ReplaceAll(v, "BATCH_ARCHIVE_V33", "ARCHIVE_COST_V34"))
			}
			if v == "../../../research/batch-archive-v33/freeze.json" {
				lit.Value = strconv.Quote("../../../research/archive-cost-v34/freeze.json")
			}
		}
		return true
	})
	return set, f
}
func write(set *token.FileSet, f *ast.File, dst string) {
	var b bytes.Buffer
	if err := format.Node(&b, set, f); err != nil {
		panic(err)
	}
	data, err := format.Source(b.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile(dst, append([]byte("// Code generated by research-archive-cost-gen; DO NOT EDIT.\n"), data...), 0600); err != nil {
		panic(err)
	}
}
func main() {
	set, f := parse("internal/store/libravdbstore/research_batch_archive_v33_test.go")
	var keep []ast.Decl
	validations, proofLoops, initCount := 0, 0, 0
	for _, d := range f.Decls {
		if g, ok := d.(*ast.GenDecl); ok && g.Tok == token.TYPE {
			name := g.Specs[0].(*ast.TypeSpec).Name.Name
			if name == "loadArchiveV34" || name == "archiveTrialV34" {
				continue
			}
			if name == "batchArchiveV34" {
				st := g.Specs[0].(*ast.TypeSpec).Type.(*ast.StructType)
				st.Fields.List = append(st.Fields.List,
					&ast.Field{Names: []*ast.Ident{ast.NewIdent("sharedAncestry"), ast.NewIdent("deferredProofs")}, Type: ast.NewIdent("bool")},
					&ast.Field{Names: []*ast.Ident{ast.NewIdent("scanPasses"), ast.NewIdent("proofBeforeAck")}, Type: ast.NewIdent("int")},
					&ast.Field{Names: []*ast.Ident{ast.NewIdent("pendingProofs")}, Type: &ast.ArrayType{Elt: &ast.StarExpr{X: ast.NewIdent("archiveJobV34")}}})
			}
		}
		if fn, ok := d.(*ast.FuncDecl); ok {
			if fn.Name.Name == "attachLoadArchiveV34" || fn.Name.Name == "finishArchiveTrialV34" || fn.Name.Name == "closeV34" {
				continue
			}
			if fn.Recv != nil && strings.Contains(expr(fn.Recv.List[0].Type), "loadArchiveV34") {
				continue
			}
			if fn.Name.Name == "attachBatchArchiveV34" {
				fn.Type.Params.List = append(fn.Type.Params.List, &ast.Field{Names: []*ast.Ident{ast.NewIdent("shared"), ast.NewIdent("deferred")}, Type: ast.NewIdent("bool")})
				ast.Inspect(fn.Body, func(n ast.Node) bool {
					if c, ok := n.(*ast.CompositeLit); ok && expr(c.Type) == "batchArchiveV34" {
						c.Elts = append(c.Elts, &ast.KeyValueExpr{Key: ast.NewIdent("sharedAncestry"), Value: ast.NewIdent("shared")}, &ast.KeyValueExpr{Key: ast.NewIdent("deferredProofs"), Value: ast.NewIdent("deferred")})
						initCount++
					}
					return true
				})
			}
			if fn.Name.Name == "applyV34" {
				for i, stmt := range fn.Body.List {
					if df, ok := stmt.(*ast.DeferStmt); ok && expr(df.Call.Fun) == "cancel" {
						insert := body(`validate, err := s.validatorV34(ctx, s.state.Head); if err != nil { return row, err }`)
						fn.Body.List = append(fn.Body.List[:i+1], append(insert, fn.Body.List[i+1:]...)...)
						break
					}
				}
				ast.Inspect(fn.Body, func(n ast.Node) bool {
					if call, ok := n.(*ast.CallExpr); ok && expr(call.Fun) == "s.validate" {
						if len(call.Args) != 3 {
							panic("bad validation call")
						}
						call.Fun, call.Args = ast.NewIdent("validate"), []ast.Expr{call.Args[1]}
						validations++
					}
					return true
				})
			}
			if fn.Name.Name == "workerV34" {
				ast.Inspect(fn.Body, func(n ast.Node) bool {
					if block, ok := n.(*ast.BlockStmt); ok {
						for i, stmt := range block.List {
							loop, ok := stmt.(*ast.RangeStmt)
							if !ok || expr(loop.X) != "batch" || !strings.Contains(expr(loop.Body), "s.proofs") {
								continue
							}
							old := loop.Body
							old.List = append(old.List, body(`s.proofBeforeAck++`)...)
							loop.Body = &ast.BlockStmt{List: []ast.Stmt{&ast.IfStmt{Cond: &ast.SelectorExpr{X: ast.NewIdent("s"), Sel: ast.NewIdent("deferredProofs")}, Body: &ast.BlockStmt{List: body(`s.pendingProofs = append(s.pendingProofs, job)`)}, Else: old}}}
							block.List[i] = loop
							proofLoops++
						}
					}
					return true
				})
			}
		}
		keep = append(keep, d)
	}
	if validations != 2 || proofLoops != 1 || initCount != 1 {
		panic("unexpected fork transformation counts")
	}
	f.Decls = keep
	write(set, f, "internal/store/libravdbstore/research_archive_cost_v34_generated_test.go")
	set, f = parse("internal/store/libravdbstore/research_batch_archive_load_v33_generated_test.go")
	ast.Inspect(f, func(n ast.Node) bool {
		if id, ok := n.(*ast.Ident); ok && id.Name == "combined" {
			id.Name = "mode"
		}
		return true
	})
	for _, d := range f.Decls {
		fn, ok := d.(*ast.FuncDecl)
		if !ok {
			continue
		}
		if fn.Name.Name == "runBatchArchiveLoadV34" {
			fn.Type.Params.List = append(fn.Type.Params.List[:2], &ast.Field{Names: []*ast.Ident{ast.NewIdent("mode")}, Type: ast.NewIdent("int")}, &ast.Field{Names: []*ast.Ident{ast.NewIdent("visible")}, Type: ast.NewIdent("bool")})
		} else if fn.Name.Name == "TestResearchBatchArchiveLoadV34" {
			ast.Inspect(fn.Body, func(n ast.Node) bool {
				if kv, ok := n.(*ast.KeyValueExpr); ok && expr(kv.Key) == `"Trials"` {
					kv.Value = &ast.BasicLit{Kind: token.INT, Value: "20"}
				}
				if r, ok := n.(*ast.RangeStmt); ok && expr(r.Value) == "mode" {
					r.X = &ast.CompositeLit{Type: &ast.ArrayType{Elt: ast.NewIdent("int")}, Elts: []ast.Expr{&ast.UnaryExpr{Op: token.SUB, X: &ast.BasicLit{Kind: token.INT, Value: "1"}}, &ast.BasicLit{Kind: token.INT, Value: "0"}, &ast.BasicLit{Kind: token.INT, Value: "1"}, &ast.BasicLit{Kind: token.INT, Value: "2"}, &ast.BasicLit{Kind: token.INT, Value: "3"}}}
				}
				return true
			})
		}
	}
	write(set, f, "internal/store/libravdbstore/research_archive_cost_load_v34_generated_test.go")
	set, f = parse("internal/store/libravdbstore/research_batch_archive_checks_v33_test.go")
	ast.Inspect(f, func(n ast.Node) bool {
		if call, ok := n.(*ast.CallExpr); ok && expr(call.Fun) == "attachBatchArchiveV34" {
			call.Args = append(call.Args, ast.NewIdent("true"), ast.NewIdent("true"))
		}
		return true
	})
	write(set, f, "internal/store/libravdbstore/research_archive_cost_checks_v34_generated_test.go")
}
func expr(n ast.Node) string {
	var b bytes.Buffer
	if err := format.Node(&b, token.NewFileSet(), n); err != nil {
		panic(err)
	}
	return b.String()
}
