// research-handoff-observer-gen generates test-only forwarding instrumentation
// from the actual EventStore AST. It does not edit runtime or instruction files.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"sort"
	"strings"
)

func qualify(e ast.Expr, local map[string]bool) ast.Expr {
	switch x := e.(type) {
	case *ast.Ident:
		if local[x.Name] {
			return &ast.SelectorExpr{X: ast.NewIdent("store"), Sel: ast.NewIdent(x.Name)}
		}
	case *ast.ArrayType:
		x.Elt = qualify(x.Elt, local)
	case *ast.StarExpr:
		x.X = qualify(x.X, local)
	case *ast.MapType:
		x.Key = qualify(x.Key, local)
		x.Value = qualify(x.Value, local)
	case *ast.Ellipsis:
		x.Elt = qualify(x.Elt, local)
	}
	return e
}
func main() {
	if len(os.Args) != 2 {
		panic("one exclusive output path required")
	}
	set := token.NewFileSet()
	file, err := parser.ParseFile(set, "internal/store/store.go", nil, 0)
	if err != nil {
		panic(err)
	}
	local := map[string]bool{}
	var api *ast.InterfaceType
	for _, decl := range file.Decls {
		if g, ok := decl.(*ast.GenDecl); ok {
			for _, spec := range g.Specs {
				if t, ok := spec.(*ast.TypeSpec); ok {
					local[t.Name.Name] = true
					if t.Name.Name == "EventStore" {
						api, _ = t.Type.(*ast.InterfaceType)
					}
				}
			}
		}
	}
	if api == nil {
		panic("EventStore missing")
	}
	used := map[string]bool{"store": true}
	var body bytes.Buffer
	count := 0
	for _, method := range api.Methods.List {
		if len(method.Names) != 1 {
			panic("embedded/unnamed interface method requires explicit review")
		}
		name := method.Names[0].Name
		fn, ok := method.Type.(*ast.FuncType)
		if !ok {
			panic("not a method")
		}
		count++
		if name == "PutBayesianJournal" {
			continue
		} // hand-written terminal boundary
		var args []string
		for _, field := range fn.Params.List {
			field.Type = qualify(field.Type, local)
			if len(field.Names) == 0 {
				panic("unnamed parameter")
			}
			for _, n := range field.Names {
				args = append(args, n.Name)
			}
		}
		if fn.Results != nil {
			for _, field := range fn.Results.List {
				field.Type = qualify(field.Type, local)
			}
		}
		ast.Inspect(fn, func(n ast.Node) bool {
			if s, ok := n.(*ast.SelectorExpr); ok {
				if id, ok := s.X.(*ast.Ident); ok {
					used[id.Name] = true
				}
			}
			return true
		})
		var sig bytes.Buffer
		if err := format.Node(&sig, set, fn); err != nil {
			panic(err)
		}
		fmt.Fprintf(&body, "func (p *handoffObserverV27) %s%s {\np.observe(%q)\n", name, strings.TrimPrefix(sig.String(), "func"), name)
		if fn.Results != nil && len(fn.Results.List) > 0 {
			body.WriteString("return ")
		}
		fmt.Fprintf(&body, "p.EventStore.%s(%s)\n}\n", name, strings.Join(args, ","))
	}
	imports := map[string]string{"store": "github.com/JuanHuaXu/eventframed/internal/store", "model": "github.com/JuanHuaXu/eventframed/internal/model", "bayes": "github.com/JuanHuaXu/eventframed/internal/bayes", "residual": "github.com/JuanHuaXu/eventframed/internal/residual", "context": "context", "time": "time"}
	var names []string
	for name := range used {
		if imports[name] == "" {
			panic("undeclared import " + name)
		}
		names = append(names, name)
	}
	sort.Strings(names)
	var out bytes.Buffer
	out.WriteString("// Code generated by research-handoff-observer-gen; DO NOT EDIT.\npackage libravdbstore\nimport (\n")
	for _, n := range names {
		fmt.Fprintf(&out, "%q\n", imports[n])
	}
	out.WriteString(")\n")
	fmt.Fprintf(&out, "const handoffMethodCountV27 = %d\nvar _ store.EventStore = (*handoffObserverV27)(nil)\n", count)
	out.Write(body.Bytes())
	formatted, err := format.Source(out.Bytes())
	if err != nil {
		panic(err)
	}
	f, err := os.OpenFile(os.Args[1], os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0600)
	if err != nil {
		panic(err)
	}
	if _, err = f.Write(formatted); err != nil {
		f.Close()
		panic(err)
	}
	if err = f.Close(); err != nil {
		panic(err)
	}
	fmt.Println("generated", count, "EventStore methods including custom journal hook")
}
