// Code generated by research-archive-timeout-gen; DO NOT EDIT.
package libravdbstore

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/JuanHuaXu/eventframed/internal/model"
	"github.com/JuanHuaXu/eventframed/internal/store"
	"time"
)

func (s *archiveWitnessV29) commitV31(ctx context.Context, c *archiveCaptureV29) error {
	s.owner.Lock()
	defer s.owner.Unlock()
	ctx, cancel := context.WithTimeout(ctx, 500*time.Millisecond)
	defer cancel()
	if err := s.validate(ctx, c, s.state.Head); err != nil {
		return err
	}
	prep := &joinedWitnessV25{scheduledWitnessV24: s.scheduledWitnessV24}
	job := &joinedJobV25{entry: c.entry, binding: c.binding}
	next, payload, digest, err := prep.prepare([]*joinedJobV25{job})
	if err != nil {
		return err
	}
	prior := s.state.Hash
	err = s.gate.appendArchiveJournalV29(ctx, []model.BayesianJournalEntry{c.entry}, s.stopAt, 0, func(tx *sql.Tx) error {
		if s.stopAt == "before_witness" {
			return errors.New("injected archive witness rollback")
		}
		snapshot, err := json.Marshal(c.entry.Snapshot)
		if err != nil {
			return err
		}
		_, err = tx.ExecContext(ctx, "INSERT INTO archive_capture_v29(journal_id,root,wire,snapshot) VALUES(?,?,?,?) ON CONFLICT(journal_id) DO NOTHING", c.entry.ID, c.root, c.wire, string(snapshot))
		if err != nil {
			return err
		}
		var root, wire, snap string
		if err := tx.QueryRowContext(ctx, "SELECT root,wire,snapshot FROM archive_capture_v29 WHERE journal_id=?", c.entry.ID).Scan(&root, &wire, &snap); err != nil {
			return err
		}
		if root != c.root || wire != c.wire || snap != string(snapshot) {
			return store.ErrJournalConflict
		}
		if _, err := tx.ExecContext(ctx, "INSERT INTO witness_v23(payload,prior,digest) VALUES(?,?,?)", payload, prior, digest); err != nil {
			return err
		}
		encoded, err := json.Marshal(next)
		if err != nil {
			return err
		}
		result, err := tx.ExecContext(ctx, "UPDATE witness_state_v23 SET payload=? WHERE id=1", string(encoded))
		if err != nil {
			return err
		}
		if n, err := result.RowsAffected(); err != nil || n != 1 {
			return fmt.Errorf("archive state rows=%d: %v", n, err)
		}
		return nil
	}, func(entry model.BayesianJournalEntry, current model.Snapshot) bool {
		return current == s.state.Head && witnessHashV23(entry) == c.wire && entry.Snapshot == c.entry.Snapshot
	})
	if err != nil {
		s.poison.Store(true)
		s.current.Store(nil)
		return err
	}
	s.state = next
	if err := s.publishLocked(ctx); err != nil {
		s.poison.Store(true)
		s.current.Store(nil)
		return err
	}
	return nil
}
