// Code generated by research-metadata-projection-gen; DO NOT EDIT.
package libravdbstore

import (
	"context"
	"github.com/JuanHuaXu/eventframed/internal/model"
	"reflect"
)

func (s *projectionStoreV35) GetSelectionCertificate(ctx context.Context, tenant string) (model.SelectionSupportCertificate, error) {
	pin, projected, projectionErr := s.pinV35(ctx)
	if projectionErr != nil {
		return model.SelectionSupportCertificate{}, projectionErr
	}
	if !projected {
		value, err := s.authority.GetSelectionCertificate(ctx, tenant)
		s.markOwnerResultV35(err)
		s.traceGetterV35(ctx, "GetSelectionCertificate", "", err)
		return value, err
	}
	s.projectedGets.Add(1)
	c, err := s.authority.EventStore.GetSelectionCertificate(ctx, tenant)
	s.traceGetterV35(ctx, "GetSelectionCertificate", "", err)
	if err != nil {
		return c, err
	}
	s.nativeSuccess.Add(1)
	if pin.state.Certificate != nil {
		b := *pin.state.Certificate
		r := witnessRecordV23("certificate", b, c.ValidFrom)
		if c.EvidenceEpoch == b.Snapshot.EvidenceEpoch && s.compatibleV35(ctx, pin, r, b) {
			c.EvidenceEpoch = s.Snapshot(ctx).EvidenceEpoch
		}
	}
	return c, nil
}
func (s *projectionStoreV35) GetOmittedInfluenceCertificate(ctx context.Context, tenant string) (model.OmittedInfluenceCertificate, error) {
	pin, projected, projectionErr := s.pinV35(ctx)
	if projectionErr != nil {
		return model.OmittedInfluenceCertificate{}, projectionErr
	}
	if !projected {
		value, err := s.authority.GetOmittedInfluenceCertificate(ctx, tenant)
		s.markOwnerResultV35(err)
		s.traceGetterV35(ctx, "GetOmittedInfluenceCertificate", "", err)
		return value, err
	}
	s.projectedGets.Add(1)
	c, err := s.authority.EventStore.GetOmittedInfluenceCertificate(ctx, tenant)
	s.traceGetterV35(ctx, "GetOmittedInfluenceCertificate", "", err)
	if err != nil {
		return c, err
	}
	s.nativeSuccess.Add(1)
	if pin.state.Certificate != nil {
		b := *pin.state.Certificate
		r := witnessRecordV23("certificate", b, b.SourceAt)
		if c.EvidenceEpoch == b.Snapshot.EvidenceEpoch && s.compatibleV35(ctx, pin, r, b) {
			c.EvidenceEpoch = s.Snapshot(ctx).EvidenceEpoch
		}
	}
	return c, nil
}
func (s *projectionStoreV35) GetBayesianPosterior(ctx context.Context, tenant, key string) (model.BayesianPosterior, error) {
	pin, projected, projectionErr := s.pinV35(ctx)
	if projectionErr != nil {
		return model.BayesianPosterior{}, projectionErr
	}
	if !projected {
		value, err := s.authority.GetBayesianPosterior(ctx, tenant, key)
		s.markOwnerResultV35(err)
		s.traceGetterV35(ctx, "GetBayesianPosterior", key, err)
		return value, err
	}
	s.projectedGets.Add(1)
	p, err := s.authority.EventStore.GetBayesianPosterior(ctx, tenant, key)
	s.traceGetterV35(ctx, "GetBayesianPosterior", key, err)
	if err != nil {
		return p, err
	}
	s.nativeSuccess.Add(1)
	if source, ok := pin.state.Sources[key]; ok && reflect.DeepEqual(source.Posterior, p) && s.compatibleV35(ctx, pin, source.Record, source.Binding) {
		if p.EvidenceEpoch != s.Snapshot(ctx).EvidenceEpoch {
			s.authority.transports.Add(1)
		}
		p.EvidenceEpoch = s.Snapshot(ctx).EvidenceEpoch
	}
	return p, nil
}
