// Code generated by research-cohort-batch-gen; DO NOT EDIT.
package libravdbstore

import (
	"bytes"
	"context"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/JuanHuaXu/eventframed/internal/bayes"
	"github.com/JuanHuaXu/eventframed/internal/model"
	"github.com/JuanHuaXu/eventframed/internal/researchvalidity"
	"github.com/JuanHuaXu/eventframed/internal/residual"
	"github.com/JuanHuaXu/eventframed/internal/service"
	"github.com/JuanHuaXu/eventframed/internal/store"
	libra "github.com/xDarkicex/libravdb/libravdb"
	"os"
	"reflect"
	"sort"
	"sync"
	"sync/atomic"
	"testing"
	"time"
)

type joinedWitnessV25_CohortV46 struct {
	*scheduledWitnessV24
	joined  bool
	mu      sync.Mutex
	closed  bool
	jobs    chan *joinedJobV25
	end     chan struct{}
	batches []joinedBatchV25
	stopAt  string
	barrier func()
}

func (s *joinedWitnessV25_CohortV46) PutBayesianJournal(ctx context.Context, entry model.BayesianJournalEntry) error {
	if !s.joined {
		return s.scheduledWitnessV24.PutBayesianJournal(ctx, entry)
	}
	if err := ctx.Err(); err != nil {
		return err
	}
	scope, _ := ctx.Value(witnessContextV23{}).(*witnessScopeV23)
	if scope == nil || scope.Binding == "" || scope.Vector == "" || scope.Frontier == "" || scope.Snapshot != entry.Snapshot || scope.AsOf != entry.AsOf {
		return errors.New("missing/mismatched joined scope")
	}
	job := &joinedJobV25{entry: entry, binding: witnessBindingV23{Binding: scope.Binding, Vector: scope.Vector, Frontier: scope.Frontier, Snapshot: entry.Snapshot, SourceAt: scope.AsOf}, done: make(chan error, 1)}
	encoded, err := json.Marshal(entry)
	if err != nil {
		return err
	}
	if err = json.Unmarshal(encoded, &job.entry); err != nil {
		return err
	}
	s.mu.Lock()
	if s.closed {
		s.mu.Unlock()
		return errors.New("joined worker closed")
	}
	select {
	case s.jobs <- job:
	case <-ctx.Done():
		s.mu.Unlock()
		return ctx.Err()
	}
	s.mu.Unlock()
	if err := <-job.done; err != nil {
		return err
	}
	return ctx.Err()
}
func (s *joinedWitnessV25_CohortV46) prepare(batch []*joinedJobV25) (*witnessStateV23, string, string, error) {
	if s.poison.Load() || s.state.Head != s.gate.store.Snapshot(context.Background()) {
		return nil, "", "", store.ErrStaleSnapshot
	}
	data, err := json.Marshal(s.state)
	if err != nil {
		return nil, "", "", err
	}
	var next witnessStateV23
	if err = json.Unmarshal(data, &next); err != nil {
		return nil, "", "", err
	}
	for _, job := range batch {
		if previous, ok := next.Journals[job.entry.ID]; ok && previous != job.binding {
			return nil, "", "", store.ErrJournalConflict
		}
		next.Journals[job.entry.ID] = job.binding
		if next.Certificate == nil {
			b := job.binding
			b.Snapshot = next.Base
			next.Certificate = &b
		}
	}
	if len(next.Journals) > 512 || len(next.Sources) > 200 || len(next.Log) > 10000 {
		return nil, "", "", errors.New("joined witness cap")
	}
	tr := witnessTransitionV23{Before: next.Head, After: next.Head, StateHash: witnessStateHashV23(next)}
	encoded, err := json.Marshal(tr)
	if err != nil {
		return nil, "", "", err
	}
	payload := string(encoded)
	digest := witnessHashV23([]string{s.state.Hash, payload})
	next.Hash = digest
	return &next, payload, digest, nil
}
func (s *joinedWitnessV25_CohortV46) apply(batch []*joinedJobV25) error {
	s.owner.Lock()
	defer s.owner.Unlock()
	if s.barrier != nil {
		s.barrier()
	}
	next, payload, digest, err := s.prepare(batch)
	if err != nil {
		s.poison.Store(true)
		s.current.Store(nil)
		return err
	}
	entries := make([]model.BayesianJournalEntry, len(batch))
	for i, job := range batch {
		entries[i] = job.entry
	}
	ctx, cancel := context.WithTimeout(context.Background(), 500*time.Millisecond)
	defer cancel()
	prior := s.state.Hash
	err = s.gate.appendJoinedJournalV25_CohortV46(ctx, entries, s.stopAt, 0, func(tx *sql.Tx) error {
		if s.stopAt == "before_witness" {
			return errors.New("injected witness rollback")
		}
		if _, err := tx.ExecContext(ctx, "INSERT INTO witness_v23(payload,prior,digest) VALUES(?,?,?)", payload, prior, digest); err != nil {
			return err
		}
		encoded, err := json.Marshal(next)
		if err != nil {
			return err
		}
		result, err := tx.ExecContext(ctx, "UPDATE witness_state_v23 SET payload=? WHERE id=1", string(encoded))
		if err != nil {
			return err
		}
		if count, err := result.RowsAffected(); err != nil || count != 1 {
			return errors.New("missing witness state row")
		}
		return nil
	})
	if err != nil {
		s.poison.Store(true)
		s.current.Store(nil)
		return err
	}
	s.state = next
	if err = s.publishLocked(ctx); err != nil {
		s.poison.Store(true)
		s.current.Store(nil)
	}
	return err
}
func (s *joinedWitnessV25_CohortV46) worker() {
	defer close(s.end)
	for first := range s.jobs {
		batch := []*joinedJobV25{first}
		timer := time.NewTimer(time.Millisecond)
		closed := false
	collect:
		for len(batch) < 8 {
			select {
			case next, ok := <-s.jobs:
				if !ok {
					closed = true
					break collect
				}
				batch = append(batch, next)
			case <-timer.C:
				break collect
			}
		}
		if !timer.Stop() {
			select {
			case <-timer.C:
			default:
			}
		}
		row := joinedBatchV25{Begin: time.Now().UTC()}
		for _, job := range batch {
			row.IDs = append(row.IDs, job.entry.ID)
		}
		row.Before = s.state.Hash
		err := s.apply(batch)
		row.After = s.state.Hash
		row.End = time.Now().UTC()
		if err != nil {
			row.Error = err.Error()
		}
		s.batches = append(s.batches, row)
		for _, job := range batch {
			job.done <- err
		}
		if closed {
			return
		}
	}
}
func (s *joinedWitnessV25_CohortV46) Close() error {
	if !s.joined {
		return s.scheduledWitnessV24.Close()
	}
	s.mu.Lock()
	if !s.closed {
		s.closed = true
		close(s.jobs)
	}
	s.mu.Unlock()
	<-s.end
	s.scheduler.Close()
	return nil
}
func attachJoinedV25_CohortV46(t *testing.T, f *witnessFixtureV23, joined bool) *joinedWitnessV25_CohortV46 {
	t.Helper()
	s := &joinedWitnessV25_CohortV46{scheduledWitnessV24: attachScheduledV24(t, f, false), joined: joined, jobs: make(chan *joinedJobV25, 128), end: make(chan struct{})}
	if joined {
		if err := s.publishedRecallLoadStoreV16.Close(); err != nil {
			t.Fatal(err)
		}
		go s.worker()
	}
	before := f.adapter.gate.store.Snapshot(context.Background())
	svc, err := service.New(s, f.em, service.Config{DefaultRecallK: 50, DefaultPackK: 10, DefaultTokenBudget: 10000, OverfetchMultiplier: 3})
	if err != nil {
		t.Fatal(err)
	}
	if before != f.adapter.gate.store.Snapshot(context.Background()) {
		t.Fatal("attachment moved source")
	}
	f.svc = svc
	return s
}
func TestResearchJoinedWitnessLifecycleV25_CohortV46(t *testing.T) {
	if os.Getenv("EVENTFRAME_RUN_JOINED_WITNESS_V25") != "1" {
		t.Skip("isolated joined integration")
	}
	ctx := context.Background()
	for _, visible := range []bool{false, true} {
		t.Run(fmt.Sprint("visible-", visible), func(t *testing.T) {
			f := createWitnessFixtureV23(t, true)
			defer f.close()
			s := attachJoinedV25_CohortV46(t, f, true)
			prime, _, err := s.recall(ctx, f.svc, f.request(time.Now().UTC(), "prime"))
			if err != nil {
				t.Fatal(err)
			}
			response, err := f.feedback(ctx, prime.BayesianShadow.JournalID, "past100", "first", false)
			if err != nil {
				t.Fatal(err)
			}
			at := f.origin.Add(time.Hour)
			if visible {
				at = f.origin
			}
			w := pinnedWrite("joined-event", at)
			w.Vector = denseRowV6(f.query, 7, .0003)
			if _, err := s.append(ctx, []ResearchEventWrite{w}, false); err != nil {
				t.Fatal(err)
			}
			after, _, err := s.recall(ctx, f.svc, f.request(time.Now().UTC(), "after"))
			if err != nil || (witnessBeliefsV23(after) > 0) == visible {
				t.Fatal("wrong transport", err)
			}
			p, err := s.gate.store.GetBayesianPosterior(ctx, "tenant-a", "past100")
			if err != nil || !reflect.DeepEqual(p, response.Posterior) {
				t.Fatal("retagged posterior", err)
			}
			for _, alter := range []string{"query", "vector", "selection", "old"} {
				r := f.request(time.Now().UTC(), "changed")
				switch alter {
				case "query":
					r.Query = "different"
				case "vector":
					r.Embedding = denseRowV6(f.query, 11, .1)
				case "selection":
					r.PackK = 9
				case "old":
					r.AsOf = p.UpdatedAt.Add(-time.Nanosecond)
				}
				other, _, err := s.recall(ctx, f.svc, r)
				if err != nil || witnessBeliefsV23(other) != 0 {
					t.Fatal("changed request reused", alter, err)
				}
			}
			f.reopen(t)
			s = attachJoinedV25_CohortV46(t, f, true)
			if s.poison.Load() {
				t.Fatal("reopen poisoned")
			}
			after, _, err = s.recall(ctx, f.svc, f.request(time.Now().UTC(), "reopen"))
			if err != nil || (witnessBeliefsV23(after) > 0) == visible {
				t.Fatal("wrong reopened transport", err)
			}
		})
	}
	for _, stop := range []string{"after_db", "before_witness", "after_sqlite"} {
		t.Run(stop, func(t *testing.T) {
			f := createWitnessFixtureV23(t, true)
			defer f.close()
			s := attachJoinedV25_CohortV46(t, f, true)
			s.stopAt = stop
			if _, _, err := s.recall(ctx, f.svc, f.request(time.Now().UTC(), "interrupt")); err == nil {
				t.Fatal("interruption acknowledged")
			}
			if !s.poison.Load() || s.current.Load() != nil {
				t.Fatal("failure not blocked")
			}
			if stop == "after_sqlite" {
				f.reopen(t)
				s = attachJoinedV25_CohortV46(t, f, true)
				if s.poison.Load() {
					t.Fatal("durable joint commit lost")
				}
				if _, _, err := s.recall(ctx, f.svc, f.request(time.Now().UTC(), "after")); err != nil {
					t.Fatal(err)
				}
			} else {
				f.close()
				g, err := openDenseOutcomeGateV17(f.root)
				if err != nil {
					t.Fatal(err)
				}
				defer g.close()
				if _, ready := g.capture(ctx); ready {
					t.Fatal("incomplete cross-store publication became READY")
				}
				base := &publishedRecallLoadStoreV16{gate: g}
				if err := base.publishLocked(ctx); err == nil || base.current.Load() != nil {
					t.Fatal("incomplete publication served")
				}
			}
		})
	}
}
func TestResearchJoinedWitnessCancellationV25_CohortV46(t *testing.T) {
	if os.Getenv("EVENTFRAME_RUN_JOINED_WITNESS_V25") != "1" {
		t.Skip("isolated joined cancellation")
	}
	f := createWitnessFixtureV23(t, true)
	defer f.close()
	s := attachJoinedV25_CohortV46(t, f, true)
	entered, release := make(chan struct{}), make(chan struct{})
	s.barrier = func() {
		close(entered)
		<-release
	}
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	done := make(chan error, 1)
	go func() {
		_, _, err := s.recall(ctx, f.svc, f.request(time.Now().UTC(), "cancel"))
		done <- err
	}()
	select {
	case <-entered:
	case <-time.After(3 * time.Second):
		t.Fatal("no handoff")
	}
	cancel()
	select {
	case err := <-done:
		close(release)
		t.Fatal("early terminal", err)
	case <-time.After(10 * time.Millisecond):
	}
	close(release)
	select {
	case err := <-done:
		if !errors.Is(err, context.Canceled) {
			t.Fatal(err)
		}
	case <-time.After(3 * time.Second):
		t.Fatal("no terminal")
	}
	if len(s.state.Journals) != 1 {
		t.Fatal("lost binding")
	}
	f.reopen(t)
	s = attachJoinedV25_CohortV46(t, f, true)
	if s.poison.Load() || len(s.state.Journals) != 1 {
		t.Fatal("canceled durability lost")
	}
}
func TestResearchJoinedWitnessBatchV25_CohortV46(t *testing.T) {
	if os.Getenv("EVENTFRAME_RUN_JOINED_WITNESS_V25") != "1" {
		t.Skip("isolated joined batch contract")
	}
	f := createWitnessFixtureV23(t, true)
	defer f.close()
	s := attachJoinedV25_CohortV46(t, f, true)
	p, _, err := s.recall(context.Background(), f.svc, f.request(time.Now().UTC(), "prime"))
	if err != nil {
		t.Fatal(err)
	}
	e, err := s.gate.store.GetBayesianJournal(context.Background(), "tenant-a", p.BayesianShadow.JournalID)
	if err != nil {
		t.Fatal(err)
	}
	b := s.state.Journals[e.ID]
	jobs := make([]*joinedJobV25, 4)
	for i := range jobs {
		clone := e
		clone.ID = fmt.Sprintf("batch-%d", i)
		clone.Report.JournalID = clone.ID
		jobs[i] = &joinedJobV25{entry: clone, binding: b}
	}
	before := len(s.state.Journals)
	if err := s.apply(jobs); err != nil {
		t.Fatal(err)
	}
	if len(s.state.Journals) != before+4 {
		t.Fatal("partial witness batch")
	}
	for _, job := range jobs {
		saved, err := s.gate.store.GetBayesianJournal(context.Background(), "tenant-a", job.entry.ID)
		got, _ := json.Marshal(saved)
		want, _ := json.Marshal(job.entry)
		if err != nil || !bytes.Equal(got, want) {
			t.Fatal("wire mismatch", err)
		}
	}
	if err := s.apply(jobs); err != nil {
		t.Fatal("duplicate batch", err)
	}
	conflict := *jobs[0]
	conflict.binding.Binding = "wrong"
	if err := s.apply([]*joinedJobV25{&conflict}); !errors.Is(err, store.ErrJournalConflict) {
		t.Fatal("conflicting scope accepted", err)
	}
	if len(s.state.Journals) != before+4 {
		t.Fatal("conflict mutated state")
	}
}
func TestResearchJoinedWitnessGapV25_CohortV46(t *testing.T) {
	if os.Getenv("EVENTFRAME_RUN_JOINED_WITNESS_V25") != "1" {
		t.Skip("isolated joined fail-closed controls")
	}
	ctx := context.Background()
	for _, interrupt := range []bool{false, true} {
		t.Run(fmt.Sprint("runtime-", interrupt), func(t *testing.T) {
			f := createWitnessFixtureV23(t, true)
			defer f.close()
			s := attachJoinedV25_CohortV46(t, f, true)
			w := pinnedWrite("unaccounted", f.origin.Add(time.Hour))
			w.Vector = denseRowV6(f.query, 3, .0001)
			if interrupt {
				if _, err := s.append(ctx, []ResearchEventWrite{w}, true); err == nil {
					t.Fatal("interruption missing")
				}
			} else {
				if err := appendDenseV6(ctx, s.gate, []ResearchEventWrite{w}); err != nil {
					t.Fatal(err)
				}
			}
			if _, _, err := s.recall(ctx, f.svc, f.request(time.Now().UTC(), "gap")); !errors.Is(err, store.ErrStaleSnapshot) {
				t.Fatal("unaccounted runtime served", err)
			}
			f.reopen(t)
			s = attachJoinedV25_CohortV46(t, f, true)
			if !s.poison.Load() {
				t.Fatal("reopened runtime gap repaired")
			}
			if _, _, err := s.recall(ctx, f.svc, f.request(time.Now().UTC(), "gap")); !errors.Is(err, store.ErrStaleSnapshot) {
				t.Fatal("reopened gap served", err)
			}
		})
	}
	t.Run("wire-conflict-no-partial-batch", func(t *testing.T) {
		f := createWitnessFixtureV23(t, true)
		defer f.close()
		s := attachJoinedV25_CohortV46(t, f, true)
		p, _, err := s.recall(ctx, f.svc, f.request(time.Now().UTC(), "prime"))
		if err != nil {
			t.Fatal(err)
		}
		e, err := s.gate.store.GetBayesianJournal(ctx, "tenant-a", p.BayesianShadow.JournalID)
		if err != nil {
			t.Fatal(err)
		}
		b := s.state.Journals[e.ID]
		fresh := e
		fresh.ID = "never-partial"
		fresh.Report.JournalID = fresh.ID
		conflict := e
		conflict.QueryDigest = "different-wire-query"
		before := s.state.Hash
		if err := s.apply([]*joinedJobV25{{entry: fresh, binding: b}, {entry: conflict, binding: b}}); !errors.Is(err, store.ErrJournalConflict) {
			t.Fatal("wire conflict accepted", err)
		}
		if s.state.Hash != before {
			t.Fatal("rollback changed witness")
		}
		if _, err := s.gate.store.GetBayesianJournal(ctx, "tenant-a", fresh.ID); !errors.Is(err, store.ErrJournalNotFound) {
			t.Fatal("partial native batch", err)
		}
	})
	t.Run("missing-scope-and-canceled", func(t *testing.T) {
		f := createWitnessFixtureV23(t, true)
		defer f.close()
		s := attachJoinedV25_CohortV46(t, f, true)
		if err := s.PutBayesianJournal(ctx, model.BayesianJournalEntry{}); err == nil {
			t.Fatal("missing scope accepted")
		}
		c, cancel := context.WithCancel(ctx)
		cancel()
		if err := s.PutBayesianJournal(c, model.BayesianJournalEntry{}); !errors.Is(err, context.Canceled) {
			t.Fatal(err)
		}
		if len(s.state.Journals) != 0 {
			t.Fatal("invalid call persisted")
		}
		if err := s.Close(); err != nil {
			t.Fatal(err)
		}
		if _, _, err := s.recall(ctx, f.svc, f.request(time.Now().UTC(), "closed")); err == nil {
			t.Fatal("closed worker accepted")
		}
	})
}
func attachCombinedV26_CohortV46(t *testing.T, f *witnessFixtureV23, combined bool) *joinedWitnessV25_CohortV46 {
	t.Helper()
	s := attachJoinedV25_CohortV46(t, f, true)
	s.mode = combined
	return s
}

type joinedJournalV25_CohortV46 struct {
	entry   model.BayesianJournalEntry
	encoded []byte
	id      string
}

func (g *incrementalSortGate) appendJoinedJournalV25_CohortV46(ctx context.Context, entries []model.BayesianJournalEntry, stopAt string, failAfter int, witness func(*sql.Tx) error) error {
	if len(entries) == 0 || len(entries) > 8 {
		return errors.New("journal batch size must be in [1,8]")
	}
	g.mu.Lock()
	defer g.mu.Unlock()
	marker, err := g.readMarker(ctx)
	if err != nil {
		return err
	}
	if g.verified == "" || marker.phase != "READY" || marker.digest != g.verified || marker.count != g.wantRows || marker.lsn != g.verifiedLSN {
		return errors.New("frontier journal batch gate is not current")
	}
	g.store.writeMu.RLock()
	defer g.store.writeMu.RUnlock()
	beforeSnapshot := g.store.snapshot
	beforeLSN, err := g.store.db.LatestCommitLSN(ctx)
	if err != nil || beforeLSN != marker.lsn {
		g.verified = ""
		return fmt.Errorf("frontier journal batch LSN moved: latest=%d marker=%d: %w", beforeLSN, marker.lsn, err)
	}
	unique := make(map[string]joinedJournalV25_CohortV46, len(entries))
	pending := make([]joinedJournalV25_CohortV46, 0, len(entries))
	for _, entry := range entries {
		if entry.ID == "" || entry.TenantID == "" || entry.AsOf.IsZero() || !store.JournalSnapshotCompatible(entry.Snapshot, beforeSnapshot, entry.AsOf, g.store.ingestMotion) {
			g.verified = ""
			return store.ErrStaleSnapshot
		}
		encoded, err := json.Marshal(entry)
		if err != nil {
			return err
		}
		item := joinedJournalV25_CohortV46{entry: entry, encoded: encoded, id: bayesianJournalRecordID(entry.TenantID, entry.ID)}
		if previous, ok := unique[item.id]; ok {
			if !bytes.Equal(previous.encoded, item.encoded) {
				g.verified = ""
				return store.ErrJournalConflict
			}
			continue
		}
		unique[item.id] = item
		existing, err := g.store.bayesian.Get(ctx, item.id)
		if err == nil {
			current, _ := existing.Metadata["journal_json"].(string)
			if current != string(encoded) {
				g.verified = ""
				return store.ErrJournalConflict
			}
			continue
		}
		if !errors.Is(err, libra.ErrRecordNotFound) {
			g.verified = ""
			return err
		}
		pending = append(pending, item)
	}
	if len(pending) == 0 {
		tx, err := g.sidecar.BeginTx(ctx, nil)
		if err != nil {
			return err
		}
		defer tx.Rollback()
		if err := witness(tx); err != nil {
			return err
		}
		return tx.Commit()
	}
	receipt, err := g.store.db.WithTxReceipt(ctx, func(tx libra.ReceiptTx) error {
		for index, item := range pending {
			metadata := map[string]interface{}{"record_type": "frontier_journal", "tenant_id": item.entry.TenantID, "journal_id": item.entry.ID, "as_of": item.entry.AsOf.UTC().Format(time.RFC3339Nano), "journal_json": string(item.encoded)}
			if err := tx.Insert(ctx, bayesianCollection, item.id, nil, metadata); err != nil {
				return err
			}
			if failAfter == index+1 {
				return errors.New("injected journal batch transaction failure")
			}
		}
		return nil
	})
	if err != nil {
		g.verified = ""
		return err
	}
	afterLSN, err := g.store.db.LatestCommitLSN(ctx)
	if err != nil || receipt.CommitLSN == 0 || afterLSN != receipt.CommitLSN || g.store.snapshot != beforeSnapshot {
		g.verified = ""
		return fmt.Errorf("frontier journal batch receipt mismatch: receipt=%d latest=%d: %v", receipt.CommitLSN, afterLSN, err)
	}
	for _, item := range unique {
		saved, err := g.store.GetBayesianJournal(ctx, item.entry.TenantID, item.entry.ID)
		if err != nil {
			g.verified = ""
			return err
		}
		got, err := json.Marshal(saved)
		if err != nil || !bytes.Equal(got, item.encoded) {
			g.verified = ""
			return fmt.Errorf("frontier batch journal readback mismatch: %v", err)
		}
	}
	if stopAt == "after_db" {
		return errors.New("injected interruption after journal batch DB commit")
	}
	markerTx, err := g.sidecar.BeginTx(ctx, nil)
	if err != nil {
		g.verified = ""
		return err
	}
	defer markerTx.Rollback()
	updated, err := markerTx.ExecContext(ctx, "UPDATE marker SET lsn=? WHERE id=1 AND phase='READY' AND lsn=? AND row_count=? AND digest=?", afterLSN, marker.lsn, marker.count, marker.digest)
	if err != nil {
		g.verified = ""
		return err
	}
	if affected, err := updated.RowsAffected(); err != nil || affected != 1 {
		g.verified = ""
		return fmt.Errorf("frontier batch marker update affected %d rows: %v", affected, err)
	}
	if err := witness(markerTx); err != nil {
		g.verified = ""
		return err
	}
	if err := markerTx.Commit(); err != nil {
		g.verified = ""
		return err
	}
	if stopAt == "after_sqlite" {
		return errors.New("injected interruption after journal batch marker commit")
	}
	g.verifiedLSN = afterLSN
	return nil
}
func (g *incrementalSortGate) appendArchiveJournalV29_CohortV46(ctx context.Context, entries []model.BayesianJournalEntry, stopAt string, failAfter int, witness func(*sql.Tx) error, admit func(model.BayesianJournalEntry, model.Snapshot) bool) error {
	if len(entries) == 0 || len(entries) > 8 {
		return errors.New("journal batch size must be in [1,8]")
	}
	g.mu.Lock()
	defer g.mu.Unlock()
	marker, err := g.readMarker(ctx)
	if err != nil {
		return err
	}
	if g.verified == "" || marker.phase != "READY" || marker.digest != g.verified || marker.count != g.wantRows || marker.lsn != g.verifiedLSN {
		return errors.New("frontier journal batch gate is not current")
	}
	g.store.writeMu.RLock()
	defer g.store.writeMu.RUnlock()
	beforeSnapshot := g.store.snapshot
	beforeLSN, err := g.store.db.LatestCommitLSN(ctx)
	if err != nil || beforeLSN != marker.lsn {
		g.verified = ""
		return fmt.Errorf("frontier journal batch LSN moved: latest=%d marker=%d: %w", beforeLSN, marker.lsn, err)
	}
	unique := make(map[string]joinedJournalV25_CohortV46, len(entries))
	pending := make([]joinedJournalV25_CohortV46, 0, len(entries))
	for _, entry := range entries {
		if entry.ID == "" || entry.TenantID == "" || entry.AsOf.IsZero() || !admit(entry, beforeSnapshot) {
			g.verified = ""
			return store.ErrStaleSnapshot
		}
		encoded, err := json.Marshal(entry)
		if err != nil {
			return err
		}
		item := joinedJournalV25_CohortV46{entry: entry, encoded: encoded, id: bayesianJournalRecordID(entry.TenantID, entry.ID)}
		if previous, ok := unique[item.id]; ok {
			if !bytes.Equal(previous.encoded, item.encoded) {
				g.verified = ""
				return store.ErrJournalConflict
			}
			continue
		}
		unique[item.id] = item
		existing, err := g.store.bayesian.Get(ctx, item.id)
		if err == nil {
			current, _ := existing.Metadata["journal_json"].(string)
			if current != string(encoded) {
				g.verified = ""
				return store.ErrJournalConflict
			}
			continue
		}
		if !errors.Is(err, libra.ErrRecordNotFound) {
			g.verified = ""
			return err
		}
		pending = append(pending, item)
	}
	if len(pending) == 0 {
		tx, err := g.sidecar.BeginTx(ctx, nil)
		if err != nil {
			return err
		}
		defer tx.Rollback()
		if err := witness(tx); err != nil {
			return err
		}
		return tx.Commit()
	}
	receipt, err := g.store.db.WithTxReceipt(ctx, func(tx libra.ReceiptTx) error {
		for index, item := range pending {
			metadata := map[string]interface{}{"record_type": "frontier_journal", "tenant_id": item.entry.TenantID, "journal_id": item.entry.ID, "as_of": item.entry.AsOf.UTC().Format(time.RFC3339Nano), "journal_json": string(item.encoded)}
			if err := tx.Insert(ctx, bayesianCollection, item.id, nil, metadata); err != nil {
				return err
			}
			if failAfter == index+1 {
				return errors.New("injected journal batch transaction failure")
			}
		}
		return nil
	})
	if err != nil {
		g.verified = ""
		return err
	}
	afterLSN, err := g.store.db.LatestCommitLSN(ctx)
	if err != nil || receipt.CommitLSN == 0 || afterLSN != receipt.CommitLSN || g.store.snapshot != beforeSnapshot {
		g.verified = ""
		return fmt.Errorf("frontier journal batch receipt mismatch: receipt=%d latest=%d: %v", receipt.CommitLSN, afterLSN, err)
	}
	for _, item := range unique {
		saved, err := g.store.GetBayesianJournal(ctx, item.entry.TenantID, item.entry.ID)
		if err != nil {
			g.verified = ""
			return err
		}
		got, err := json.Marshal(saved)
		if err != nil || !bytes.Equal(got, item.encoded) {
			g.verified = ""
			return fmt.Errorf("frontier batch journal readback mismatch: %v", err)
		}
	}
	if stopAt == "after_db" {
		return errors.New("injected interruption after journal batch DB commit")
	}
	markerTx, err := g.sidecar.BeginTx(ctx, nil)
	if err != nil {
		g.verified = ""
		return err
	}
	defer markerTx.Rollback()
	updated, err := markerTx.ExecContext(ctx, "UPDATE marker SET lsn=? WHERE id=1 AND phase='READY' AND lsn=? AND row_count=? AND digest=?", afterLSN, marker.lsn, marker.count, marker.digest)
	if err != nil {
		g.verified = ""
		return err
	}
	if affected, err := updated.RowsAffected(); err != nil || affected != 1 {
		g.verified = ""
		return fmt.Errorf("frontier batch marker update affected %d rows: %v", affected, err)
	}
	if err := witness(markerTx); err != nil {
		g.verified = ""
		return err
	}
	if err := markerTx.Commit(); err != nil {
		g.verified = ""
		return err
	}
	if stopAt == "after_sqlite" {
		return errors.New("injected interruption after journal batch marker commit")
	}
	g.verifiedLSN = afterLSN
	return nil
}

var errArchiveCapacityV34_CohortV46 = errors.New("archive accepted-job capacity exceeded")

type archiveJobV34_CohortV46 struct {
	capture    *archiveCaptureV29
	done       chan error
	capturedAt time.Time
}
type archiveProofV34_CohortV46 struct {
	ID, Root, Wire string
	Encoded        string
	Snapshot       model.Snapshot
	CapturedAt     time.Time
}
type archiveQueueStatsV34_CohortV46 struct {
	Accepted, Finished, Rejected, Peak, Active, Capacity int
	Closed                                               bool
}
type batchArchiveV34_CohortV46 struct {
	*archiveWitnessV29
	mu                             sync.Mutex
	jobs                           chan *archiveJobV34_CohortV46
	end                            chan struct{}
	stats                          archiveQueueStatsV34_CohortV46
	api                            sync.WaitGroup
	batches                        []joinedBatchV25
	proofs                         []archiveProofV34_CohortV46
	barrier                        func()
	sharedAncestry, deferredProofs bool
	scanPasses, proofBeforeAck     int
	pendingProofs                  []*archiveJobV34_CohortV46
}

func attachBatchArchiveV34_CohortV46(t *testing.T, f *witnessFixtureV23, capacity int, shared, deferred bool) *batchArchiveV34_CohortV46 {
	t.Helper()
	if capacity < 1 || capacity > 128 {
		t.Fatal("archive capacity must be1..128")
	}
	base := &archiveWitnessV29{scheduledWitnessV24: attachScheduledV24(t, f, true)}
	if err := base.publishedRecallLoadStoreV16.Close(); err != nil {
		t.Fatal(err)
	}
	if _, err := base.gate.sidecar.Exec("CREATE TABLE IF NOT EXISTS archive_capture_v29(journal_id TEXT PRIMARY KEY, root TEXT NOT NULL, wire TEXT NOT NULL, snapshot TEXT NOT NULL)"); err != nil {
		t.Fatal(err)
	}
	s := &batchArchiveV34_CohortV46{archiveWitnessV29: base, jobs: make(chan *archiveJobV34_CohortV46, capacity), end: make(chan struct{}), stats: archiveQueueStatsV34_CohortV46{Capacity: capacity}, sharedAncestry: shared, deferredProofs: deferred}
	go s.workerV34()
	before := s.gate.store.Snapshot(context.Background())
	svc, err := service.New(s, f.em, service.Config{DefaultRecallK: 50, DefaultPackK: 10, DefaultTokenBudget: 10000, OverfetchMultiplier: 3})
	if err != nil {
		t.Fatal(err)
	}
	if before != s.gate.store.Snapshot(context.Background()) {
		t.Fatal("batch attachment moved source")
	}
	f.svc = svc
	return s
}
func (s *batchArchiveV34_CohortV46) recall(ctx context.Context, svc *service.Service, req model.RecallRequest) (model.ContextPacket, *publishedRecallViewV8, error) {
	s.mu.Lock()
	if s.stats.Closed {
		s.mu.Unlock()
		return model.ContextPacket{}, nil, errors.New("archive closed")
	}
	s.api.Add(1)
	s.mu.Unlock()
	defer s.api.Done()
	return s.archiveWitnessV29.recall(ctx, svc, req)
}
func (s *batchArchiveV34_CohortV46) PutBayesianJournal(ctx context.Context, e model.BayesianJournalEntry) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	s.mu.Lock()
	if s.stats.Closed {
		s.mu.Unlock()
		return errors.New("archive closed")
	}
	if s.stats.Active >= s.stats.Capacity {
		s.stats.Rejected++
		s.mu.Unlock()
		return errArchiveCapacityV34_CohortV46
	}
	s.stats.Active++
	if s.stats.Active > s.stats.Peak {
		s.stats.Peak = s.stats.Active
	}
	s.api.Add(1)
	s.mu.Unlock()
	defer func() {
		s.mu.Lock()
		s.stats.Active--
		s.mu.Unlock()
		s.api.Done()
	}()
	c, err := s.capture(ctx, e)
	if err != nil {
		return err
	}
	job := &archiveJobV34_CohortV46{capture: c, done: make(chan error, 1), capturedAt: time.Now().UTC()}
	s.mu.Lock()
	if s.stats.Closed {
		s.mu.Unlock()
		return errors.New("archive closed before enqueue")
	}
	ctx.Value(archiveLeaseKeyV29{}).(*archiveLeaseV29).finish()
	s.jobs <- job
	s.stats.Accepted++
	s.mu.Unlock()
	if err := <-job.done; err != nil {
		return err
	}
	return ctx.Err()
}
func (s *batchArchiveV34_CohortV46) applyV34(batch []*archiveJobV34_CohortV46) (joinedBatchV25, error) {
	if s.barrier != nil {
		s.barrier()
	}
	s.owner.Lock()
	defer s.owner.Unlock()
	row := joinedBatchV25{Begin: time.Now().UTC(), Before: s.state.Hash}
	ctx, cancel := context.WithTimeout(context.Background(), 500*time.Millisecond)
	defer cancel()
	validate, err := s.validatorV34(ctx, s.state.Head)
	if err != nil {
		return row, err
	}
	jobs := make([]*joinedJobV25, len(batch))
	entries := make([]model.BayesianJournalEntry, len(batch))
	caps := map[string]*archiveCaptureV29{}
	for i, job := range batch {
		c := job.capture
		row.IDs = append(row.IDs, c.entry.ID)
		if err := validate(c); err != nil {
			return row, err
		}
		if prior, ok := caps[c.entry.ID]; ok && (prior.wire != c.wire || prior.binding != c.binding) {
			return row, store.ErrJournalConflict
		}
		caps[c.entry.ID] = c
		jobs[i] = &joinedJobV25{entry: c.entry, binding: c.binding}
		entries[i] = c.entry
	}
	prep := &joinedWitnessV25_CohortV46{scheduledWitnessV24: s.scheduledWitnessV24}
	canonical := map[string]string{}
	for id, c := range caps {
		var root, wire, snap string
		err := s.gate.sidecar.QueryRowContext(ctx, "SELECT root,wire,snapshot FROM archive_capture_v29 WHERE journal_id=?", id).Scan(&root, &wire, &snap)
		if errors.Is(err, sql.ErrNoRows) {
			canonical[id] = c.root
			continue
		}
		if err != nil {
			return row, err
		}
		snapshot, _ := json.Marshal(c.entry.Snapshot)
		if wire != c.wire || snap != string(snapshot) {
			return row, store.ErrJournalConflict
		}
		old := *c
		old.root = root
		old.seal = witnessHashV23([]any{old.entry, old.binding, old.root})
		if err := validate(&old); err != nil {
			return row, err
		}
		canonical[id] = root
	}
	next, payload, digest, err := prep.prepare(jobs)
	if err != nil {
		return row, err
	}
	prior := s.state.Hash
	err = s.gate.appendArchiveJournalV29_CohortV46(ctx, entries, s.stopAt, 0, func(tx *sql.Tx) error {
		if s.stopAt == "before_witness" {
			return errors.New("injected batch archive witness rollback")
		}
		for _, c := range caps {
			snapshot, err := json.Marshal(c.entry.Snapshot)
			if err != nil {
				return err
			}
			if _, err := tx.ExecContext(ctx, "INSERT INTO archive_capture_v29(journal_id,root,wire,snapshot) VALUES(?,?,?,?) ON CONFLICT(journal_id) DO NOTHING", c.entry.ID, c.root, c.wire, string(snapshot)); err != nil {
				return err
			}
			var root, wire, snap string
			if err := tx.QueryRowContext(ctx, "SELECT root,wire,snapshot FROM archive_capture_v29 WHERE journal_id=?", c.entry.ID).Scan(&root, &wire, &snap); err != nil {
				return err
			}
			if root != canonical[c.entry.ID] || wire != c.wire || snap != string(snapshot) {
				return store.ErrJournalConflict
			}
		}
		if _, err := tx.ExecContext(ctx, "INSERT INTO witness_v23(payload,prior,digest) VALUES(?,?,?)", payload, prior, digest); err != nil {
			return err
		}
		encoded, err := json.Marshal(next)
		if err != nil {
			return err
		}
		result, err := tx.ExecContext(ctx, "UPDATE witness_state_v23 SET payload=? WHERE id=1", string(encoded))
		if err != nil {
			return err
		}
		if n, err := result.RowsAffected(); err != nil || n != 1 {
			return fmt.Errorf("archive batch state rows=%d: %v", n, err)
		}
		return nil
	}, func(e model.BayesianJournalEntry, current model.Snapshot) bool {
		c := caps[e.ID]
		return c != nil && current == s.state.Head && witnessHashV23(e) == c.wire && e.Snapshot == c.entry.Snapshot
	})
	if err != nil {
		s.poison.Store(true)
		s.current.Store(nil)
		return row, err
	}
	s.state = next
	if err = s.publishLocked(ctx); err != nil {
		s.poison.Store(true)
		s.current.Store(nil)
		return row, err
	}
	row.After = s.state.Hash
	row.End = time.Now().UTC()
	return row, nil
}
func (s *batchArchiveV34_CohortV46) workerV34() {
	defer close(s.end)
	for first := range s.jobs {
		batch := []*archiveJobV34_CohortV46{first}
		timer := time.NewTimer(time.Millisecond)
	collect:
		for len(batch) < 8 {
			select {
			case next, ok := <-s.jobs:
				if !ok {
					break collect
				}
				batch = append(batch, next)
			case <-timer.C:
				break collect
			}
		}
		if !timer.Stop() {
			select {
			case <-timer.C:
			default:
			}
		}
		row, err := s.applyV34(batch)
		if err != nil {
			row.Error = err.Error()
			row.End = time.Now().UTC()
		}
		s.mu.Lock()
		s.batches = append(s.batches, row)
		s.stats.Finished += len(batch)
		for _, job := range batch {
			if s.deferredProofs {
				s.pendingProofs = append(s.pendingProofs, job)
			} else {
				c := job.capture
				encoded, _ := json.Marshal(c.entry)
				s.proofs = append(s.proofs, archiveProofV34_CohortV46{ID: c.entry.ID, Root: c.root, Wire: c.wire, Encoded: string(encoded), Snapshot: c.entry.Snapshot, CapturedAt: job.capturedAt})
				s.proofBeforeAck++
			}
		}
		s.mu.Unlock()
		for _, job := range batch {
			job.done <- err
		}
	}
}
func (s *batchArchiveV34_CohortV46) Close() error {
	s.mu.Lock()
	if !s.stats.Closed {
		s.stats.Closed = true
		close(s.jobs)
	}
	s.mu.Unlock()
	s.scheduler.Close()
	<-s.end
	s.api.Wait()
	return nil
}
func (s *batchArchiveV34_CohortV46) validatorV34(ctx context.Context, current model.Snapshot) (func(*archiveCaptureV29) error, error) {
	if !s.sharedAncestry {
		return func(c *archiveCaptureV29) error {
			s.scanPasses++
			return s.validate(ctx, c, current)
		}, nil
	}
	s.scanPasses++
	head := s.state.Base
	root := witnessGenesisV23(head).Hash
	stateHash := root
	roots := map[string]model.Snapshot{root: head}
	rows, err := s.gate.sidecar.QueryContext(ctx, "SELECT payload,prior,digest FROM witness_v23 ORDER BY seq")
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	count := 0
	for rows.Next() {
		count++
		if count > 11000 {
			return nil, errors.New("archive history cap")
		}
		var payload, prior, digest string
		if err := rows.Scan(&payload, &prior, &digest); err != nil {
			return nil, err
		}
		var tr witnessTransitionV23
		if err := json.Unmarshal([]byte(payload), &tr); err != nil {
			return nil, err
		}
		if prior != root || tr.Before != head || digest != witnessHashV23([]string{prior, payload}) {
			return nil, errors.New("archive chain gap")
		}
		root, head, stateHash = digest, tr.After, tr.StateHash
		roots[root] = head
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	if head != current || root != s.state.Hash || stateHash != witnessStateHashV23(*s.state) {
		return nil, errors.New("archive ancestry mismatch")
	}
	return func(c *archiveCaptureV29) error {
		if c == nil || c.owner != s.archiveWitnessV29 || c.root == "" || c.wire != witnessHashV23(c.entry) || c.seal != witnessHashV23([]any{c.entry, c.binding, c.root}) || c.binding.Snapshot != c.entry.Snapshot || c.binding.SourceAt != c.entry.AsOf || s.poison.Load() || current != s.state.Head || current != s.gate.store.Snapshot(ctx) {
			return errors.New("invalid archive authority")
		}
		if snap, ok := roots[c.root]; !ok || snap != c.entry.Snapshot {
			return errors.New("archive ancestry mismatch")
		}
		return nil
	}, nil
}

type loadArchiveV34_CohortV46 struct {
	*joinedWitnessV25_CohortV46
	archive *batchArchiveV34_CohortV46
	mode    int
}

func attachLoadArchiveV34_CohortV46(t *testing.T, f *witnessFixtureV23, mode int) *loadArchiveV34_CohortV46 {
	if mode < -1 || mode > 3 {
		t.Fatal("invalid factorial mode")
	}
	if mode == -1 {
		return &loadArchiveV34_CohortV46{joinedWitnessV25_CohortV46: attachCombinedV26_CohortV46(t, f, true), mode: mode}
	}
	a := attachBatchArchiveV34_CohortV46(t, f, 128, mode&1 != 0, mode&2 != 0)
	return &loadArchiveV34_CohortV46{joinedWitnessV25_CohortV46: &joinedWitnessV25_CohortV46{scheduledWitnessV24: a.scheduledWitnessV24, joined: true}, archive: a, mode: mode}
}
func (s *loadArchiveV34_CohortV46) recall(ctx context.Context, svc *service.Service, r model.RecallRequest) (model.ContextPacket, *publishedRecallViewV8, error) {
	if s.archive != nil {
		return s.archive.recall(ctx, svc, r)
	}
	return s.joinedWitnessV25_CohortV46.recall(ctx, svc, r)
}
func (s *loadArchiveV34_CohortV46) closeV34() error {
	if s.archive != nil {
		return s.archive.Close()
	}
	return s.joinedWitnessV25_CohortV46.Close()
}

type archiveTrialV34_CohortV46 struct {
	joinedTrialV25
	Mode                                     int
	Archived, SharedAncestry, DeferredProofs bool
	Captures                                 []archiveProofV34_CohortV46
	ArchiveQueue                             archiveQueueStatsV34_CohortV46
	AncestryScans, ProofBeforeAck            int
	PostDrainProofNS                         int64
}

func finishArchiveTrialV34_CohortV46(s *loadArchiveV34_CohortV46, r joinedTrialV25) archiveTrialV34_CohortV46 {
	if s.archive == nil {
		return archiveTrialV34_CohortV46{joinedTrialV25: r, Mode: s.mode}
	}
	a := s.archive
	a.mu.Lock()
	defer a.mu.Unlock()
	if a.stats.Active != 0 || a.stats.Accepted != a.stats.Finished {
		panic("proof materialization before serving drain")
	}
	start := time.Now()
	for _, job := range a.pendingProofs {
		c := job.capture
		encoded, err := json.Marshal(c.entry)
		if err != nil {
			panic(err)
		}
		a.proofs = append(a.proofs, archiveProofV34_CohortV46{ID: c.entry.ID, Root: c.root, Wire: c.wire, Encoded: string(encoded), Snapshot: c.entry.Snapshot, CapturedAt: job.capturedAt})
	}
	a.pendingProofs = nil
	proofNS := time.Since(start).Nanoseconds()
	r.Batches = append([]joinedBatchV25(nil), a.batches...)
	a.owner.Lock()
	scans := a.scanPasses
	a.owner.Unlock()
	return archiveTrialV34_CohortV46{joinedTrialV25: r, Mode: s.mode, Archived: true, SharedAncestry: a.sharedAncestry, DeferredProofs: a.deferredProofs, Captures: append([]archiveProofV34_CohortV46(nil), a.proofs...), ArchiveQueue: a.stats, AncestryScans: scans, ProofBeforeAck: a.proofBeforeAck, PostDrainProofNS: proofNS}
}
func TestResearchBatchArchiveRetryV34_CohortV46(t *testing.T) {
	if os.Getenv("EVENTFRAME_RUN_ARCHIVE_COST_V34") != "1" {
		t.Skip("isolated archival retry controls")
	}
	ctx := context.Background()
	t.Run("sealed-v31-rejects-identical-retry", func(t *testing.T) {
		f := createWitnessFixtureV23(t, true)
		defer f.close()
		s := attachArchiveV31(t, f)
		defer s.Close()
		r := f.request(time.Now().UTC(), "first")
		first, _, err := s.recall(ctx, f.svc, r)
		if err != nil {
			t.Fatal(err)
		}
		if _, _, err := s.recall(ctx, f.svc, f.request(time.Now().UTC(), "other")); err != nil {
			t.Fatal(err)
		}
		_, _, err = s.recall(ctx, f.svc, r)
		if !errors.Is(err, store.ErrJournalConflict) {
			t.Fatal("expected V31 capture-root conflict", err)
		}
		t.Logf("confirmed V31 retry conflict after journal-only publication; original journal=%s", first.BayesianShadow.JournalID)
	})
	t.Run("batch-retains-original-provenance", func(t *testing.T) {
		f := createWitnessFixtureV23(t, true)
		defer f.close()
		s := attachBatchArchiveV34_CohortV46(t, f, 128, true, true)
		defer s.Close()
		r := f.request(time.Now().UTC(), "first")
		first, _, err := s.recall(ctx, f.svc, r)
		if err != nil {
			t.Fatal(err)
		}
		var original string
		if err := s.gate.sidecar.QueryRow("SELECT root FROM archive_capture_v29 WHERE journal_id=?", first.BayesianShadow.JournalID).Scan(&original); err != nil {
			t.Fatal(err)
		}
		if _, _, err := s.recall(ctx, f.svc, f.request(time.Now().UTC(), "other")); err != nil {
			t.Fatal(err)
		}
		retry, _, err := s.recall(ctx, f.svc, r)
		if err != nil || retry.BayesianShadow.JournalID != first.BayesianShadow.JournalID {
			t.Fatal("identical retry rejected/changed", err)
		}
		var after string
		_ = s.gate.sidecar.QueryRow("SELECT root FROM archive_capture_v29 WHERE journal_id=?", first.BayesianShadow.JournalID).Scan(&after)
		if original != after || len(s.state.Journals) != 2 {
			t.Fatal("retry rewrote provenance")
		}
		if err := s.Close(); err != nil {
			t.Fatal(err)
		}
		f.reopen(t)
		s = attachBatchArchiveV34_CohortV46(t, f, 128, true, true)
		defer s.Close()
		if _, _, err := s.recall(ctx, f.svc, f.request(time.Now().UTC(), "reopen")); err != nil {
			t.Fatal(err)
		}
		if _, err := s.gate.sidecar.Exec("UPDATE archive_capture_v29 SET root='forged' WHERE journal_id=?", first.BayesianShadow.JournalID); err != nil {
			t.Fatal(err)
		}
		if _, _, err := s.recall(ctx, f.svc, r); err == nil {
			t.Fatal("forged original capture root accepted")
		}
	})
}
func TestResearchBatchArchiveLifecycleV34_CohortV46(t *testing.T) {
	if os.Getenv("EVENTFRAME_RUN_ARCHIVE_COST_V34") != "1" {
		t.Skip("isolated bounded queue/cancel/close controls")
	}
	f := createWitnessFixtureV23(t, true)
	defer f.close()
	s := attachBatchArchiveV34_CohortV46(t, f, 3, true, true)
	defer s.Close()
	entered, release := make(chan struct{}), make(chan struct{})
	var once sync.Once
	unblock := func() {
		once.Do(func() {
			close(release)
		})
	}
	defer unblock()
	var first sync.Once
	s.barrier = func() {
		first.Do(func() {
			close(entered)
		})
		<-release
	}
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	done := make(chan error, 3)
	base := time.Now().UTC().Add(-time.Millisecond)
	for i := 0; i < 3; i++ {
		go func(i int) {
			_, _, err := s.recall(ctx, f.svc, f.request(base.Add(time.Duration(i)*time.Nanosecond), "held"))
			done <- err
		}(i)
	}
	remaining := 3
	defer func() {
		unblock()
		for remaining > 0 {
			select {
			case <-done:
				remaining--
			case <-time.After(5 * time.Second):
				t.Error("live caller did not drain")
				return
			}
		}
	}()
	select {
	case <-entered:
	case <-time.After(5 * time.Second):
		t.Fatal("worker did not enter barrier")
	}
	deadline := time.Now().Add(5 * time.Second)
	for {
		s.mu.Lock()
		accepted := s.stats.Accepted
		s.mu.Unlock()
		if accepted == 3 {
			break
		}
		if time.Now().After(deadline) {
			t.Fatal("queue not filled")
		}
		time.Sleep(time.Millisecond)
	}
	if _, _, err := s.recall(context.Background(), f.svc, f.request(time.Now().UTC(), "overload")); !errors.Is(err, errArchiveCapacityV34_CohortV46) {
		t.Fatal("cap did not reject", err)
	}
	cancel()
	closing := make(chan error, 1)
	go func() {
		closing <- s.Close()
	}()
	select {
	case err := <-closing:
		t.Fatal("close returned before accepted durability", err)
	case <-time.After(5 * time.Millisecond):
	}
	select {
	case err := <-done:
		remaining--
		t.Fatal("canceled accepted handoff returned early", err)
	default:
	}
	unblock()
	for remaining > 0 {
		select {
		case err := <-done:
			remaining--
			if !errors.Is(err, context.Canceled) {
				t.Fatal(err)
			}
		case <-time.After(5 * time.Second):
			t.Fatal("accepted cancellation did not finish")
		}
	}
	select {
	case err := <-closing:
		if err != nil {
			t.Fatal(err)
		}
	case <-time.After(5 * time.Second):
		t.Fatal("close did not finish")
	}
	s.mu.Lock()
	stats := s.stats
	s.mu.Unlock()
	if !stats.Closed || stats.Accepted != 3 || stats.Finished != 3 || stats.Active != 0 || stats.Peak > 3 || stats.Rejected != 1 || len(s.state.Journals) != 3 {
		t.Fatal("queue/drain conservation", stats)
	}
	if _, _, err := s.recall(context.Background(), f.svc, f.request(time.Now().UTC(), "closed")); err == nil {
		t.Fatal("closed adapter accepted request")
	}
	t.Logf("capacity/reject/cancel/close stats=%+v", stats)
}
func TestResearchBatchArchiveInterruptionV34_CohortV46(t *testing.T) {
	if os.Getenv("EVENTFRAME_RUN_ARCHIVE_COST_V34") != "1" {
		t.Skip("isolated native/sidecar interruptions")
	}
	for _, stop := range []string{"after_db", "before_witness", "after_sqlite"} {
		t.Run(stop, func(t *testing.T) {
			f := createWitnessFixtureV23(t, true)
			defer f.close()
			s := attachBatchArchiveV34_CohortV46(t, f, 128, true, true)
			defer s.Close()
			s.stopAt = stop
			if _, _, err := s.recall(context.Background(), f.svc, f.request(time.Now().UTC(), "stop")); err == nil {
				t.Fatal("interruption acked")
			}
			if !s.poison.Load() || s.current.Load() != nil {
				t.Fatal("failure not blocked")
			}
			_ = s.Close()
			if stop == "after_sqlite" {
				f.reopen(t)
				s = attachBatchArchiveV34_CohortV46(t, f, 128, true, true)
				defer s.Close()
				if s.poison.Load() {
					t.Fatal("complete joint commit lost")
				}
				if _, _, err := s.recall(context.Background(), f.svc, f.request(time.Now().UTC(), "reopen")); err != nil {
					t.Fatal(err)
				}
			} else {
				f.close()
				g, err := openDenseOutcomeGateV17(f.root)
				if err != nil {
					t.Fatal(err)
				}
				defer g.close()
				if _, ready := g.capture(context.Background()); ready {
					t.Fatal("incomplete publication became READY")
				}
			}
		})
	}
}

type metadataKeyV35_CohortV46 struct{}
type metadataPinV35_CohortV46 struct {
	owner      *projectionStoreV35_CohortV46
	state      *witnessStateV23
	active     atomic.Bool
	encoded    string
	capturedAt time.Time
	scope      *witnessScopeV23
	mu         sync.Mutex
	getters    []metadataGetterV35_CohortV46
}
type metadataGetterV35_CohortV46 struct {
	Method, Key string
	NativeOK    bool
}
type metadataReadV35_CohortV46 struct {
	Journal string
	Getters []metadataGetterV35_CohortV46
}
type metadataProofV35_CohortV46 struct {
	Journal, Root, SHA256, Encoded string
	Snapshot                       model.Snapshot
	CapturedAt                     time.Time
}
type metadataStatsV35_CohortV46 struct {
	Captured, ProjectedGets, NativeSuccess, LegacyOwnerResults int64
	CopiesBytes                                                int64
}
type projectionStoreV35_CohortV46 struct {
	store.EventStore
	authority                                                               *witnessStoreV23
	projected                                                               bool
	mu                                                                      sync.Mutex
	proofs                                                                  []metadataProofV35_CohortV46
	reads                                                                   []metadataReadV35_CohortV46
	captured, projectedGets, nativeSuccess, legacyOwnerResults, copiesBytes atomic.Int64
	afterProjection                                                         func(context.Context)
}

func (s *projectionStoreV35_CohortV46) Search(ctx context.Context, tenant string, vector []float32, asOf time.Time, k int) ([]store.SearchResult, error) {
	results, err := s.authority.Search(ctx, tenant, vector, asOf, k)
	if err != nil || !s.projected {
		return results, err
	}
	p, _ := ctx.Value(metadataKeyV35_CohortV46{}).(*metadataPinV35_CohortV46)
	scope, _ := ctx.Value(witnessContextV23{}).(*witnessScopeV23)
	view, _ := ctx.Value(publishedRecallPinKeyV8{}).(*publishedRecallPinV8)
	if p == nil || p.owner != s || scope == nil || view == nil || view.view == nil {
		return nil, errors.New("missing metadata request authority")
	}
	s.authority.owner.Lock()
	if s.authority.poison.Load() || s.authority.state.Head != scope.Snapshot || scope.Snapshot != view.view.snapshot || s.authority.gate.store.Snapshot(ctx) != scope.Snapshot {
		s.authority.owner.Unlock()
		return nil, store.ErrStaleSnapshot
	}
	state := s.authority.state
	read := struct {
		Head        model.Snapshot
		Hash        string
		Log         []researchvalidity.Mutation
		Sources     map[string]witnessSourceV23
		Certificate *witnessBindingV23
	}{state.Head, state.Hash, state.Log, state.Sources, state.Certificate}
	encoded, err := json.Marshal(read)
	if err == nil {
		var owned witnessStateV23
		err = json.Unmarshal(encoded, &owned)
		if err == nil {
			p.state, p.scope, p.encoded, p.capturedAt = &owned, scope, string(encoded), time.Now().UTC()
			p.active.Store(true)
		}
	}
	s.authority.owner.Unlock()
	if err != nil {
		return nil, err
	}
	s.captured.Add(1)
	s.copiesBytes.Add(int64(len(encoded)))
	if s.afterProjection != nil {
		s.afterProjection(ctx)
	}
	return results, nil
}
func (s *projectionStoreV35_CohortV46) pinV35(ctx context.Context) (*metadataPinV35_CohortV46, bool, error) {
	if !s.projected {
		return nil, false, nil
	}
	p, _ := ctx.Value(metadataKeyV35_CohortV46{}).(*metadataPinV35_CohortV46)
	if p == nil {
		return nil, false, nil
	}
	scope, _ := ctx.Value(witnessContextV23{}).(*witnessScopeV23)
	view, _ := ctx.Value(publishedRecallPinKeyV8{}).(*publishedRecallPinV8)
	if p.owner != s || !p.active.Load() || p.state == nil || p.scope != scope || scope == nil || scope.Snapshot != p.state.Head || view == nil || view.view == nil || view.view.snapshot != p.state.Head || s.authority.poison.Load() || s.authority.current.Load() == nil || time.Since(view.view.at) >= 250*time.Millisecond || s.authority.gate.store.Snapshot(ctx) != p.state.Head {
		return nil, true, errors.New("invalid or expired metadata projection")
	}
	return p, true, nil
}
func (s *projectionStoreV35_CohortV46) compatibleV35(ctx context.Context, pin *metadataPinV35_CohortV46, record researchvalidity.Record, b witnessBindingV23) bool {
	scope, _ := ctx.Value(witnessContextV23{}).(*witnessScopeV23)
	if !s.authority.enabled || s.authority.poison.Load() || scope == nil || scope.Binding != b.Binding || scope.Vector != b.Vector || scope.Frontier != b.Frontier {
		return false
	}
	if scope.Snapshot != pin.state.Head || s.authority.gate.store.Snapshot(ctx) != pin.state.Head {
		return false
	}
	start := sort.Search(len(pin.state.Log), func(i int) bool {
		return pin.state.Log[i].RuntimeVersion > record.Base.RuntimeVersion
	})
	req := researchvalidity.Request{TenantID: record.TenantID, PosteriorKey: record.PosteriorKey, QueryDigest: scope.Binding, ModelID: scope.Vector, HorizonKey: record.HorizonKey, SourceID: record.SourceID, AsOf: scope.AsOf, FrontierDigest: scope.Frontier, Current: scope.Snapshot}
	return researchvalidity.Check(record, req, pin.state.Log[start:]).Status == researchvalidity.Compatible
}
func (s *projectionStoreV35_CohortV46) markOwnerResultV35(err error) {
	if err == nil {
		s.legacyOwnerResults.Add(1)
	}
}
func (s *projectionStoreV35_CohortV46) traceGetterV35(ctx context.Context, method, key string, err error) {
	p, _ := ctx.Value(metadataKeyV35_CohortV46{}).(*metadataPinV35_CohortV46)
	if p == nil {
		return
	}
	p.mu.Lock()
	p.getters = append(p.getters, metadataGetterV35_CohortV46{Method: method, Key: key, NativeOK: err == nil})
	p.mu.Unlock()
}
func (s *projectionStoreV35_CohortV46) PutBayesianJournal(ctx context.Context, e model.BayesianJournalEntry) error {
	if p, _ := ctx.Value(metadataKeyV35_CohortV46{}).(*metadataPinV35_CohortV46); p != nil {
		p.mu.Lock()
		getters := append([]metadataGetterV35_CohortV46(nil), p.getters...)
		p.mu.Unlock()
		s.mu.Lock()
		s.reads = append(s.reads, metadataReadV35_CohortV46{Journal: e.ID, Getters: getters})
		s.mu.Unlock()
	}
	if s.projected {
		p, selected, err := s.pinV35(ctx)
		if err != nil {
			return err
		}
		if !selected {
			return errors.New("journal lacks projected Recall authority")
		}
		if p.state.Head != e.Snapshot {
			return store.ErrStaleSnapshot
		}
		s.mu.Lock()
		s.proofs = append(s.proofs, metadataProofV35_CohortV46{Journal: e.ID, Root: p.state.Hash, SHA256: witnessHashV23(json.RawMessage(p.encoded)), Encoded: p.encoded, Snapshot: e.Snapshot, CapturedAt: p.capturedAt})
		s.mu.Unlock()
		p.active.Store(false)
	}
	return s.EventStore.PutBayesianJournal(ctx, e)
}

type loadProjectionV35_CohortV46 struct {
	*loadArchiveV34_CohortV46
	metadata *projectionStoreV35_CohortV46
}

func attachLoadProjectionV35_CohortV46(t *testing.T, f *witnessFixtureV23, mode int) *loadProjectionV35_CohortV46 {
	t.Helper()
	projected := mode == -2 || mode == 4
	baseMode := mode
	if mode == -2 {
		baseMode = -1
	}
	if mode == 4 {
		baseMode = 3
	}
	if baseMode != -1 && baseMode != 3 {
		t.Fatal("invalid projection/storage factorial")
	}
	inner := attachLoadArchiveV34_CohortV46(t, f, baseMode)
	var backend store.EventStore = inner.joinedWitnessV25_CohortV46
	if inner.archive != nil {
		backend = inner.archive
	}
	m := &projectionStoreV35_CohortV46{EventStore: backend, authority: inner.witnessStoreV23, projected: projected}
	before := m.authority.gate.store.Snapshot(context.Background())
	svc, err := service.New(m, f.em, service.Config{DefaultRecallK: 50, DefaultPackK: 10, DefaultTokenBudget: 10000, OverfetchMultiplier: 3})
	if err != nil {
		t.Fatal(err)
	}
	if before != m.authority.gate.store.Snapshot(context.Background()) {
		t.Fatal("projection attachment moved native head")
	}
	f.svc = svc
	return &loadProjectionV35_CohortV46{loadArchiveV34_CohortV46: inner, metadata: m}
}
func (s *loadProjectionV35_CohortV46) recall(ctx context.Context, svc *service.Service, r model.RecallRequest) (model.ContextPacket, *publishedRecallViewV8, error) {
	p := &metadataPinV35_CohortV46{owner: s.metadata}
	ctx = context.WithValue(ctx, metadataKeyV35_CohortV46{}, p)
	defer p.active.Store(false)
	return s.loadArchiveV34_CohortV46.recall(ctx, svc, r)
}
func (s *loadProjectionV35_CohortV46) closeV35() error {
	return s.closeV34()
}

type projectionTrialV35_CohortV46 struct {
	archiveTrialV34_CohortV46
	Projected      bool
	Metadata       metadataStatsV35_CohortV46
	MetadataProofs []metadataProofV35_CohortV46
	MetadataReads  []metadataReadV35_CohortV46
}

func finishProjectionTrialV35_CohortV46(s *loadProjectionV35_CohortV46, r joinedTrialV25) projectionTrialV35_CohortV46 {
	m := s.metadata
	m.mu.Lock()
	proofs := append([]metadataProofV35_CohortV46(nil), m.proofs...)
	reads := append([]metadataReadV35_CohortV46(nil), m.reads...)
	m.mu.Unlock()
	stats := metadataStatsV35_CohortV46{Captured: m.captured.Load(), ProjectedGets: m.projectedGets.Load(), NativeSuccess: m.nativeSuccess.Load(), LegacyOwnerResults: m.legacyOwnerResults.Load(), CopiesBytes: m.copiesBytes.Load()}
	return projectionTrialV35_CohortV46{archiveTrialV34_CohortV46: finishArchiveTrialV34_CohortV46(s.loadArchiveV34_CohortV46, r), Projected: m.projected, Metadata: stats, MetadataProofs: proofs, MetadataReads: reads}
}

type readCoreV36_CohortV46 struct {
	state   *witnessStateV23
	encoded string
	at      time.Time
}
type coreBuildV36_CohortV46 struct {
	Root, Encoded string
	At            time.Time
}
type coreStatsV36_CohortV46 struct{ Builds, Hits, OwnerAcquisitions, PhysicalBytes int64 }
type coreStoreV36_CohortV46 struct {
	*projectionStoreV35_CohortV46
	enabled                             bool
	core                                atomic.Pointer[readCoreV36_CohortV46]
	builds, hits, owners, physicalBytes atomic.Int64
	mu                                  sync.Mutex
	proofs                              []coreBuildV36_CohortV46
}

func (s *coreStoreV36_CohortV46) Search(ctx context.Context, tenant string, vector []float32, asOf time.Time, k int) ([]store.SearchResult, error) {
	if !s.enabled {
		return s.projectionStoreV35_CohortV46.Search(ctx, tenant, vector, asOf, k)
	}
	results, err := s.authority.Search(ctx, tenant, vector, asOf, k)
	if err != nil {
		return nil, err
	}
	p, _ := ctx.Value(metadataKeyV35_CohortV46{}).(*metadataPinV35_CohortV46)
	scope, _ := ctx.Value(witnessContextV23{}).(*witnessScopeV23)
	view, _ := ctx.Value(publishedRecallPinKeyV8{}).(*publishedRecallPinV8)
	if p == nil || p.owner != s.projectionStoreV35_CohortV46 || scope == nil || view == nil || view.view == nil || scope.Snapshot != view.view.snapshot || s.authority.poison.Load() || s.authority.gate.store.Snapshot(ctx) != scope.Snapshot {
		return nil, errors.New("invalid shared-core request authority")
	}
	c := s.core.Load()
	if c == nil || c.state.Head != scope.Snapshot {
		s.authority.owner.Lock()
		s.owners.Add(1)
		if s.authority.poison.Load() || s.authority.state.Head != scope.Snapshot || s.authority.gate.store.Snapshot(ctx) != scope.Snapshot {
			s.authority.owner.Unlock()
			return nil, store.ErrStaleSnapshot
		}
		c = s.core.Load()
		if c == nil || c.state.Head != scope.Snapshot {
			state := s.authority.state
			read := struct {
				Head        model.Snapshot
				Hash        string
				Log         []researchvalidity.Mutation
				Sources     map[string]witnessSourceV23
				Certificate *witnessBindingV23
			}{state.Head, state.Hash, state.Log, state.Sources, state.Certificate}
			encoded, e := json.Marshal(read)
			if e != nil {
				s.authority.owner.Unlock()
				return nil, e
			}
			var owned witnessStateV23
			if e = json.Unmarshal(encoded, &owned); e != nil {
				s.authority.owner.Unlock()
				return nil, e
			}
			c = &readCoreV36_CohortV46{state: &owned, encoded: string(encoded), at: time.Now().UTC()}
			s.builds.Add(1)
			s.physicalBytes.Add(int64(len(encoded)))
			s.copiesBytes.Add(int64(len(encoded)))
			s.mu.Lock()
			s.proofs = append(s.proofs, coreBuildV36_CohortV46{Root: owned.Hash, Encoded: c.encoded, At: c.at})
			s.mu.Unlock()
			if owned.Certificate != nil {
				s.core.Store(c)
			}
		} else {
			s.hits.Add(1)
		}
		s.authority.owner.Unlock()
	} else {
		s.hits.Add(1)
	}
	p.state, p.scope, p.encoded, p.capturedAt = c.state, scope, c.encoded, time.Now().UTC()
	p.active.Store(true)
	s.captured.Add(1)
	if s.afterProjection != nil {
		s.afterProjection(ctx)
	}
	return results, nil
}

type loadCoreV36_CohortV46 struct {
	*loadProjectionV35_CohortV46
	shared *coreStoreV36_CohortV46
}

func attachLoadCoreV36_CohortV46(t *testing.T, f *witnessFixtureV23, mode int) *loadCoreV36_CohortV46 {
	t.Helper()
	enabled := mode == -2 || mode == 4
	storageMode := -2
	if mode == 3 || mode == 4 {
		storageMode = 4
	} else if mode != -1 && mode != -2 {
		t.Fatal("invalid core factorial")
	}
	inner := attachLoadProjectionV35_CohortV46(t, f, storageMode)
	s := &coreStoreV36_CohortV46{projectionStoreV35_CohortV46: inner.metadata, enabled: enabled}
	before := s.authority.gate.store.Snapshot(context.Background())
	svc, err := service.New(s, f.em, service.Config{DefaultRecallK: 50, DefaultPackK: 10, DefaultTokenBudget: 10000, OverfetchMultiplier: 3})
	if err != nil || before != s.authority.gate.store.Snapshot(context.Background()) {
		t.Fatal("shared-core attachment", err)
	}
	f.svc = svc
	return &loadCoreV36_CohortV46{loadProjectionV35_CohortV46: inner, shared: s}
}
func (s *loadCoreV36_CohortV46) closeV36() error {
	return s.closeV35()
}

type coreTrialV36_CohortV46 struct {
	projectionTrialV35_CohortV46
	CoreEnabled bool
	CoreStats   coreStatsV36_CohortV46
	CoreBuilds  []coreBuildV36_CohortV46
}

func finishCoreTrialV36_CohortV46(s *loadCoreV36_CohortV46, r joinedTrialV25) coreTrialV36_CohortV46 {
	c := s.shared
	c.mu.Lock()
	builds := append([]coreBuildV36_CohortV46(nil), c.proofs...)
	c.mu.Unlock()
	stats := coreStatsV36_CohortV46{Builds: c.builds.Load(), Hits: c.hits.Load(), OwnerAcquisitions: c.owners.Load(), PhysicalBytes: c.physicalBytes.Load()}
	return coreTrialV36_CohortV46{projectionTrialV35_CohortV46: finishProjectionTrialV35_CohortV46(s.loadProjectionV35_CohortV46, r), CoreEnabled: c.enabled, CoreStats: stats, CoreBuilds: builds}
}
func (s *projectionStoreV35_CohortV46) GetSelectionCertificate(ctx context.Context, tenant string) (model.SelectionSupportCertificate, error) {
	pin, projected, projectionErr := s.pinV35(ctx)
	if projectionErr != nil {
		return model.SelectionSupportCertificate{}, projectionErr
	}
	if !projected {
		value, err := s.authority.GetSelectionCertificate(ctx, tenant)
		s.markOwnerResultV35(err)
		s.traceGetterV35(ctx, "GetSelectionCertificate", "", err)
		return value, err
	}
	s.projectedGets.Add(1)
	c, err := s.authority.EventStore.GetSelectionCertificate(ctx, tenant)
	s.traceGetterV35(ctx, "GetSelectionCertificate", "", err)
	if err != nil {
		return c, err
	}
	s.nativeSuccess.Add(1)
	if pin.state.Certificate != nil {
		b := *pin.state.Certificate
		r := witnessRecordV23("certificate", b, c.ValidFrom)
		if c.EvidenceEpoch == b.Snapshot.EvidenceEpoch && s.compatibleV35(ctx, pin, r, b) {
			c.EvidenceEpoch = s.Snapshot(ctx).EvidenceEpoch
		}
	}
	return c, nil
}
func (s *projectionStoreV35_CohortV46) GetOmittedInfluenceCertificate(ctx context.Context, tenant string) (model.OmittedInfluenceCertificate, error) {
	pin, projected, projectionErr := s.pinV35(ctx)
	if projectionErr != nil {
		return model.OmittedInfluenceCertificate{}, projectionErr
	}
	if !projected {
		value, err := s.authority.GetOmittedInfluenceCertificate(ctx, tenant)
		s.markOwnerResultV35(err)
		s.traceGetterV35(ctx, "GetOmittedInfluenceCertificate", "", err)
		return value, err
	}
	s.projectedGets.Add(1)
	c, err := s.authority.EventStore.GetOmittedInfluenceCertificate(ctx, tenant)
	s.traceGetterV35(ctx, "GetOmittedInfluenceCertificate", "", err)
	if err != nil {
		return c, err
	}
	s.nativeSuccess.Add(1)
	if pin.state.Certificate != nil {
		b := *pin.state.Certificate
		r := witnessRecordV23("certificate", b, b.SourceAt)
		if c.EvidenceEpoch == b.Snapshot.EvidenceEpoch && s.compatibleV35(ctx, pin, r, b) {
			c.EvidenceEpoch = s.Snapshot(ctx).EvidenceEpoch
		}
	}
	return c, nil
}
func (s *projectionStoreV35_CohortV46) GetBayesianPosterior(ctx context.Context, tenant, key string) (model.BayesianPosterior, error) {
	pin, projected, projectionErr := s.pinV35(ctx)
	if projectionErr != nil {
		return model.BayesianPosterior{}, projectionErr
	}
	if !projected {
		value, err := s.authority.GetBayesianPosterior(ctx, tenant, key)
		s.markOwnerResultV35(err)
		s.traceGetterV35(ctx, "GetBayesianPosterior", key, err)
		return value, err
	}
	s.projectedGets.Add(1)
	p, err := s.authority.EventStore.GetBayesianPosterior(ctx, tenant, key)
	s.traceGetterV35(ctx, "GetBayesianPosterior", key, err)
	if err != nil {
		return p, err
	}
	s.nativeSuccess.Add(1)
	if source, ok := pin.state.Sources[key]; ok && reflect.DeepEqual(source.Posterior, p) && s.compatibleV35(ctx, pin, source.Record, source.Binding) {
		if p.EvidenceEpoch != s.Snapshot(ctx).EvidenceEpoch {
			s.authority.transports.Add(1)
		}
		p.EvidenceEpoch = s.Snapshot(ctx).EvidenceEpoch
	}
	return p, nil
}

type warmKeyV37_CohortV46 struct{}
type warmUseV37_CohortV46 struct {
	Journal, Root string
	Fast          bool
	CheckedAt     time.Time
}
type warmStatsV37_CohortV46 struct{ Fast, Cold int64 }
type warmStoreV37_CohortV46 struct {
	*coreStoreV36_CohortV46
	enabled    bool
	fast, cold atomic.Int64
	mu         sync.Mutex
	uses       []warmUseV37_CohortV46
}

func (s *warmStoreV37_CohortV46) Search(ctx context.Context, tenant string, vector []float32, asOf time.Time, k int) ([]store.SearchResult, error) {
	u, _ := ctx.Value(warmKeyV37_CohortV46{}).(*warmUseV37_CohortV46)
	if u == nil {
		return nil, errors.New("missing warm-search request")
	}
	c := s.core.Load()
	u.CheckedAt = time.Now().UTC()
	current := s.authority.current.Load()
	native := s.authority.gate.store.Snapshot(ctx)
	if !s.enabled || c == nil || current == nil || c.state.Head != native || current.snapshot != native || s.authority.poison.Load() {
		s.cold.Add(1)
		return s.coreStoreV36_CohortV46.Search(ctx, tenant, vector, asOf, k)
	}
	p, _ := ctx.Value(metadataKeyV35_CohortV46{}).(*metadataPinV35_CohortV46)
	scope, _ := ctx.Value(witnessContextV23{}).(*witnessScopeV23)
	if p == nil || p.owner != s.projectionStoreV35_CohortV46 || scope == nil || p.scope != nil && !p.active.Load() {
		return nil, errors.New("foreign or expired warm-search request")
	}
	results, err := s.authority.publishedRecallLoadStoreV16.Search(ctx, tenant, vector, asOf, k)
	if err != nil {
		return nil, err
	}
	scope.Vector = witnessHashV23(vector)
	scope.AsOf = asOf
	scope.Snapshot = s.authority.Snapshot(ctx)
	ids := make([]string, len(results))
	for i, r := range results {
		ids[i] = r.Event.ID
	}
	scope.Frontier = witnessIDsV23(ids)
	view, _ := ctx.Value(publishedRecallPinKeyV8{}).(*publishedRecallPinV8)
	if view == nil || view.view == nil || scope.Snapshot != c.state.Head || view.view.snapshot != c.state.Head || s.authority.poison.Load() || s.authority.current.Load() == nil || s.authority.gate.store.Snapshot(ctx) != c.state.Head {
		return nil, store.ErrStaleSnapshot
	}
	p.state, p.scope, p.encoded, p.capturedAt = c.state, scope, c.encoded, time.Now().UTC()
	p.active.Store(true)
	s.hits.Add(1)
	s.captured.Add(1)
	s.fast.Add(1)
	u.Fast = true
	if s.afterProjection != nil {
		s.afterProjection(ctx)
	}
	return results, nil
}
func (s *warmStoreV37_CohortV46) PutBayesianJournal(ctx context.Context, e model.BayesianJournalEntry) error {
	u, _ := ctx.Value(warmKeyV37_CohortV46{}).(*warmUseV37_CohortV46)
	p, _, err := s.pinV35(ctx)
	if err != nil {
		return err
	}
	if u == nil || p == nil || p.state == nil {
		return errors.New("missing warm-search handoff")
	}
	u.Journal, u.Root = e.ID, p.state.Hash
	s.mu.Lock()
	s.uses = append(s.uses, *u)
	s.mu.Unlock()
	return s.projectionStoreV35_CohortV46.PutBayesianJournal(ctx, e)
}

type loadWarmV37_CohortV46 struct {
	*loadCoreV36_CohortV46
	warm *warmStoreV37_CohortV46
}

func attachLoadWarmV37_CohortV46(t *testing.T, f *witnessFixtureV23, mode int) *loadWarmV37_CohortV46 {
	t.Helper()
	enabled := mode == -2 || mode == 4
	coreMode := -2
	if mode == 3 || mode == 4 {
		coreMode = 4
	} else if mode != -1 && mode != -2 {
		t.Fatal("invalid warm-search factorial")
	}
	inner := attachLoadCoreV36_CohortV46(t, f, coreMode)
	w := &warmStoreV37_CohortV46{coreStoreV36_CohortV46: inner.shared, enabled: enabled}
	before := w.authority.gate.store.Snapshot(context.Background())
	svc, err := service.New(w, f.em, service.Config{DefaultRecallK: 50, DefaultPackK: 10, DefaultTokenBudget: 10000, OverfetchMultiplier: 3})
	if err != nil || before != w.authority.gate.store.Snapshot(context.Background()) {
		t.Fatal("warm attachment", err)
	}
	f.svc = svc
	return &loadWarmV37_CohortV46{loadCoreV36_CohortV46: inner, warm: w}
}
func (s *loadWarmV37_CohortV46) recall(ctx context.Context, svc *service.Service, r model.RecallRequest) (model.ContextPacket, *publishedRecallViewV8, error) {
	return s.loadCoreV36_CohortV46.recall(context.WithValue(ctx, warmKeyV37_CohortV46{}, &warmUseV37_CohortV46{}), svc, r)
}
func (s *loadWarmV37_CohortV46) closeV37() error {
	return s.closeV36()
}

type warmTrialV37_CohortV46 struct {
	coreTrialV36_CohortV46
	WarmEnabled bool
	WarmStats   warmStatsV37_CohortV46
	WarmUses    []warmUseV37_CohortV46
}

func finishWarmTrialV37_CohortV46(s *loadWarmV37_CohortV46, r joinedTrialV25) warmTrialV37_CohortV46 {
	w := s.warm
	w.mu.Lock()
	uses := append([]warmUseV37_CohortV46(nil), w.uses...)
	w.mu.Unlock()
	return warmTrialV37_CohortV46{coreTrialV36_CohortV46: finishCoreTrialV36_CohortV46(s.loadCoreV36_CohortV46, r), WarmEnabled: w.enabled, WarmStats: warmStatsV37_CohortV46{Fast: w.fast.Load(), Cold: w.cold.Load()}, WarmUses: uses}
}

var _ store.EventStore = (*warmStoreV37_CohortV46)(nil)

type preparationV44_CohortV46 struct {
	Kind                             string
	OperationIDs                     []string
	Begin, OwnerAt, End, BuiltAt     time.Time
	Owner, Built, Reused, InitialNil bool
	Head                             model.Snapshot
	Root, Encoded, Error             string
}
type eagerStoreV44_CohortV46 struct {
	*warmStoreV37_CohortV46
	enabled       bool
	preparationMu sync.Mutex
	preparations  []preparationV44_CohortV46
}

func (s *eagerStoreV44_CohortV46) refresh(ctx context.Context, kind string, ids ...string) (err error) {
	if !s.enabled {
		return nil
	}
	trace := preparationV44_CohortV46{Kind: kind, OperationIDs: append([]string(nil), ids...), Begin: time.Now().UTC()}
	defer func() {
		trace.End = time.Now().UTC()
		if err != nil {
			trace.Error = err.Error()
		}
		s.preparationMu.Lock()
		s.preparations = append(s.preparations, trace)
		s.preparationMu.Unlock()
	}()
	if err = ctx.Err(); err != nil {
		return err
	}
	a := s.authority
	a.owner.Lock()
	trace.OwnerAt = time.Now().UTC()
	trace.Owner = true
	defer a.owner.Unlock()
	if err = ctx.Err(); err != nil {
		return err
	}
	native := a.gate.store.Snapshot(ctx)
	view := a.current.Load()
	if a.poison.Load() || a.state == nil || a.state.Head != native || view == nil || view.snapshot != native {
		return store.ErrStaleSnapshot
	}
	trace.Head = a.state.Head
	if a.state.Certificate == nil {
		trace.InitialNil = true
		return nil
	}
	if c := s.core.Load(); c != nil && c.state.Head == native && c.state.Certificate != nil {
		trace.Reused = true
		trace.Root = c.state.Hash
		return nil
	}
	state := a.state
	read := struct {
		Head        model.Snapshot
		Hash        string
		Log         []researchvalidity.Mutation
		Sources     map[string]witnessSourceV23
		Certificate *witnessBindingV23
	}{state.Head, state.Hash, state.Log, state.Sources, state.Certificate}
	encoded, err := json.Marshal(read)
	if err != nil {
		return err
	}
	var owned witnessStateV23
	if err = json.Unmarshal(encoded, &owned); err != nil {
		return err
	}
	if a.poison.Load() || a.gate.store.Snapshot(ctx) != owned.Head || a.current.Load() != view {
		return store.ErrStaleSnapshot
	}
	c := &readCoreV36_CohortV46{state: &owned, encoded: string(encoded), at: time.Now().UTC()}
	s.core.Store(c)
	s.builds.Add(1)
	s.physicalBytes.Add(int64(len(encoded)))
	s.copiesBytes.Add(int64(len(encoded)))
	s.coreStoreV36_CohortV46.mu.Lock()
	s.proofs = append(s.proofs, coreBuildV36_CohortV46{Root: owned.Hash, Encoded: c.encoded, At: c.at})
	s.coreStoreV36_CohortV46.mu.Unlock()
	trace.Built = true
	trace.Root = owned.Hash
	trace.Encoded = c.encoded
	trace.BuiltAt = c.at
	return nil
}
func (s *eagerStoreV44_CohortV46) PutBayesianJournal(ctx context.Context, e model.BayesianJournalEntry) error {
	if err := s.warmStoreV37_CohortV46.PutBayesianJournal(ctx, e); err != nil {
		return err
	}
	_ = s.refresh(ctx, "journal", e.ID)
	return nil
}
func (s *eagerStoreV44_CohortV46) ApplyBayesianOutcome(ctx context.Context, request model.BayesianOutcomeRequest, key, parent, digest string, weight float64, change bayes.ChangePolicy, group bayes.GroupPolicy, observation model.ResidualObservation, policy residual.Policy) (store.BayesianOutcomeResult, error) {
	r, err := s.warmStoreV37_CohortV46.ApplyBayesianOutcome(ctx, request, key, parent, digest, weight, change, group, observation, policy)
	if err == nil {
		_ = s.refresh(ctx, "outcome", request.IdempotencyKey)
	}
	return r, err
}

type loadEagerV44_CohortV46 struct {
	*loadWarmV37_CohortV46
	eager *eagerStoreV44_CohortV46
}

func attachLoadEagerV44_CohortV46(t *testing.T, f *witnessFixtureV23, mode int, enabled bool) *loadEagerV44_CohortV46 {
	t.Helper()
	if mode != -2 && mode != 4 {
		t.Fatal("eager load requires joined/archive with warm Search enabled")
	}
	inner := attachLoadWarmV37_CohortV46(t, f, mode)
	s := &eagerStoreV44_CohortV46{warmStoreV37_CohortV46: inner.warm, enabled: enabled}
	before := s.authority.gate.store.Snapshot(context.Background())
	svc, err := service.New(s, f.em, service.Config{DefaultRecallK: 50, DefaultPackK: 10, DefaultTokenBudget: 10000, OverfetchMultiplier: 3})
	if err != nil || before != s.authority.gate.store.Snapshot(context.Background()) {
		t.Fatal("eager attachment changed authority", err)
	}
	f.svc = svc
	return &loadEagerV44_CohortV46{inner, s}
}
func (s *loadEagerV44_CohortV46) append(ctx context.Context, writes []ResearchEventWrite, interrupt bool) (model.Snapshot, error) {
	r, err := s.loadWarmV37_CohortV46.append(ctx, writes, interrupt)
	if err == nil {
		ids := make([]string, len(writes))
		for i, write := range writes {
			ids[i] = write.Event.ID
		}
		_ = s.eager.refresh(ctx, "write", ids...)
	}
	return r, err
}

type eagerTrialV44_CohortV46 struct {
	warmTrialV37_CohortV46
	EagerEnabled bool
	Preparations []preparationV44_CohortV46
}

func finishEagerTrialV44_CohortV46(s *loadEagerV44_CohortV46, r joinedTrialV25) eagerTrialV44_CohortV46 {
	s.eager.preparationMu.Lock()
	traces := append([]preparationV44_CohortV46(nil), s.eager.preparations...)
	s.eager.preparationMu.Unlock()
	return eagerTrialV44_CohortV46{warmTrialV37_CohortV46: finishWarmTrialV37_CohortV46(s.loadWarmV37_CohortV46, r), EagerEnabled: s.eager.enabled, Preparations: traces}
}

var _ store.EventStore = (*eagerStoreV44_CohortV46)(nil)

func runEagerLoadV44_CohortV46(t *testing.T, trial int, mode int, visible bool, eager bool) eagerTrialV44_CohortV46 {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()
	f := createWitnessFixtureV23(t, true)
	defer f.close()
	s := attachLoadEagerV44_CohortV46(t, f, mode, eager)
	defer s.closeV37()
	a := f.adapter
	prime, _, err := s.recall(ctx, f.svc, f.request(time.Now().UTC(), "prime"))
	if err != nil {
		t.Fatal(err)
	}
	var events []string
	for _, d := range prime.BayesianShadow.Decisions {
		if d.Activated {
			events = append(events, d.EventID)
			if len(events) == 16 {
				break
			}
		}
	}
	if len(events) != 16 {
		t.Fatal("prime activation")
	}
	start := time.Now().Add(20 * time.Millisecond)
	jobs := make(chan recallLoadOfferV16, 128)
	writeJobs := make(chan sortLoadWriteJob, 128)
	outcomeJobs := make(chan outcomeOfferV18, 16)
	reads := make(chan witnessReadV23, 128)
	writes := make(chan []witnessWriteV23, 1)
	outcomes := make(chan []witnessOutcomeV23, 1)
	waitUntil := func(at time.Time) bool {
		timer := time.NewTimer(time.Until(at))
		select {
		case <-timer.C:
			return true
		case <-ctx.Done():
			timer.Stop()
			return false
		}
	}
	go func() {
		defer close(jobs)
		for i := 0; i < 128; i++ {
			if !waitUntil(start.Add(time.Duration(i) * 4 * time.Millisecond)) {
				return
			}
			jobs <- recallLoadOfferV16{index: i, offered: time.Now().UTC()}
		}
	}()
	go func() {
		defer close(writeJobs)
		for i := 0; i < 128; i++ {
			if !waitUntil(start.Add(time.Duration(i) * 4 * time.Millisecond)) {
				return
			}
			at := f.origin.Add(time.Hour)
			if visible {
				at = f.origin
			}
			w := pinnedWrite(fmt.Sprintf("write-%03d", i), at)
			w.Vector = denseRowV6(f.query, i, .00213*float64(i+1))
			writeJobs <- sortLoadWriteJob{write: w, offered: time.Now().UTC()}
		}
	}()
	go func() {
		var rows []witnessWriteV23
		for {
			group, closed := sortLoadTakeGroup(writeJobs, 16, 16*time.Millisecond)
			if len(group) == 0 {
				break
			}
			batch := make([]ResearchEventWrite, len(group))
			for j, job := range group {
				batch[j] = job.write
			}
			snap, err := s.append(ctx, batch, false)
			ack := time.Now().UTC()
			for _, job := range group {
				r := witnessWriteV23{Index: len(rows), Offer: job.offered, Ack: ack, Snapshot: snap, Available: job.write.Event.AvailableAt}
				if err != nil {
					r.Error = err.Error()
				}
				rows = append(rows, r)
			}
			if closed || err != nil {
				break
			}
		}
		writes <- rows
	}()
	go func() {
		defer close(outcomeJobs)
		for i, event := range events {
			if !waitUntil(start.Add(20*time.Millisecond + time.Duration(i)*16*time.Millisecond)) {
				return
			}
			offer := time.Now().UTC()
			outcomeJobs <- outcomeOfferV18{index: i, request: f.outcomeRequest(prime.BayesianShadow.JournalID, event, fmt.Sprintf("load-%d", i), i%2 == 0, offer)}
		}
	}()
	go func() {
		var rows []witnessOutcomeV23
		for job := range outcomeJobs {
			response, err := f.svc.ObserveBayesianOutcome(ctx, job.request)
			r := witnessOutcomeV23{Index: job.index, EventID: job.request.EventID, Useful: job.request.Useful, Offer: job.request.AvailableAt, Published: time.Now().UTC(), Response: response, Request: job.request}
			if err != nil {
				r.Error = err.Error()
			}
			rows = append(rows, r)
			if err != nil {
				break
			}
		}
		outcomes <- rows
	}()
	var wg sync.WaitGroup
	for worker := 0; worker < 8; worker++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for job := range jobs {
				began := time.Now().UTC()
				request := f.request(job.offered, "load")
				packet, view, err := s.recall(ctx, f.svc, request)
				r := witnessReadV23{Index: job.index, Offer: job.offered, Start: began, End: time.Now().UTC(), Snapshot: packet.Snapshot, Journal: packet.BayesianShadow.JournalID, Decisions: packet.BayesianShadow.Decisions, Packed: packet.Candidates, Request: request, Selection: packet.BayesianShadow.SelectionSupportCertified, Omitted: packet.BayesianShadow.OmittedInfluenceCertified}
				if view != nil {
					r.ViewAt = view.at.UTC()
					r.PinSnapshot = view.snapshot
				}
				if err != nil {
					r.Error = err.Error()
				}
				reads <- r
			}
		}()
	}
	go func() {
		wg.Wait()
		close(reads)
	}()
	row := scheduledTrialV24{witnessTrialV23: witnessTrialV23{Trial: trial, Enabled: true, Visible: visible, Metrics: map[string]int64{}, Origin: f.origin, InitialSnapshot: prime.Snapshot}, Scheduled: true}
	for r := range reads {
		row.Reads = append(row.Reads, r)
	}
	row.Writes = <-writes
	row.Outcomes = <-outcomes
	row.Admission = s.scheduler.Snapshot()
	s.traceMu.Lock()
	row.Trace = append([]scheduledWaitV24(nil), s.trace...)
	s.traceMu.Unlock()
	row.Transported = a.transports.Load()
	row.WitnessHash = a.state.Hash
	row.FinalSnapshot = a.gate.store.Snapshot(ctx)
	row.FinalWitness = *a.state
	commitRows, err := a.gate.sidecar.QueryContext(ctx, "SELECT seq,payload,prior,digest FROM witness_v23 ORDER BY seq")
	if err != nil {
		t.Fatal(err)
	}
	for commitRows.Next() {
		var c witnessCommitV23
		if err := commitRows.Scan(&c.Seq, &c.Payload, &c.Prior, &c.Digest); err != nil {
			commitRows.Close()
			t.Fatal(err)
		}
		row.Commits = append(row.Commits, c)
	}
	if err := commitRows.Err(); err != nil {
		t.Fatal(err)
	}
	commitRows.Close()
	for _, event := range events {
		p, err := a.gate.store.GetBayesianPosterior(ctx, "tenant-a", event)
		if err != nil {
			row.Errors = append(row.Errors, "missing durable source")
		}
		row.DurableSources = append(row.DurableSources, p)
	}
	if len(row.Reads) != 128 || len(row.Writes) != 128 || len(row.Outcomes) != 16 {
		row.Errors = append(row.Errors, "incomplete offered work")
	}
	var readNS, offerNS, viewNS, writeNS, outcomeNS []int64
	learned := 0
	for _, r := range row.Reads {
		readNS = append(readNS, r.End.Sub(r.Start).Nanoseconds())
		offerNS = append(offerNS, r.End.Sub(r.Offer).Nanoseconds())
		viewNS = append(viewNS, r.End.Sub(r.ViewAt).Nanoseconds())
		if r.Error != "" || r.Journal == "" || len(r.Decisions) != 150 {
			row.Errors = append(row.Errors, "invalid Recall/journal")
		}
		saved, err := a.gate.store.GetBayesianJournal(ctx, "tenant-a", r.Journal)
		got, marshalErr := json.Marshal(saved.Report.Decisions)
		want, _ := json.Marshal(r.Decisions)
		if err != nil || marshalErr != nil || saved.Snapshot != r.Snapshot || !bytes.Equal(got, want) {
			row.Errors = append(row.Errors, "wire journal mismatch")
		}
		h := sha256.Sum256(got)
		row.JournalProofs = append(row.JournalProofs, scheduledJournalV24{r.Index, saved.Snapshot, hex.EncodeToString(h[:])})
		for _, d := range r.Decisions {
			if d.Forecast.BeliefLaw != nil {
				learned++
			}
		}
	}
	for _, w := range row.Writes {
		writeNS = append(writeNS, w.Ack.Sub(w.Offer).Nanoseconds())
		if w.Error != "" {
			row.Errors = append(row.Errors, "write: "+w.Error)
		}
	}
	for _, o := range row.Outcomes {
		outcomeNS = append(outcomeNS, o.Published.Sub(o.Offer).Nanoseconds())
		if o.Error != "" || o.Response.Duplicate {
			row.Errors = append(row.Errors, "outcome: "+o.Error)
		}
	}
	row.Metrics["learned_decisions"] = int64(learned)
	for name, values := range map[string][]int64{"call": readNS, "offer": offerNS, "view": viewNS, "write": writeNS, "outcome": outcomeNS} {
		row.Metrics[name+"_p99_ns"] = pinnedPercentile(values, .99).Nanoseconds()
		row.Metrics[name+"_max_ns"] = pinnedPercentile(values, 1).Nanoseconds()
	}
	if a.poison.Load() || a.state.Head != row.FinalSnapshot {
		row.Errors = append(row.Errors, "invalid witness head")
	}
	if _, ready := a.gate.capture(ctx); !ready {
		row.Errors = append(row.Errors, "marker not READY")
	}
	if row.Admission.ActiveWriter || row.Admission.ActiveReaders != 0 || row.Admission.Queued != ([3]int{}) {
		row.Errors = append(row.Errors, "undrained admission")
	}
	row.Pass = len(row.Errors) == 0 && row.Metrics["call_p99_ns"] < int64(100*time.Millisecond) && row.Metrics["offer_p99_ns"] < int64(100*time.Millisecond) && row.Metrics["write_p99_ns"] < int64(250*time.Millisecond) && row.Metrics["outcome_p99_ns"] < int64(100*time.Millisecond) && row.Metrics["outcome_max_ns"] < int64(250*time.Millisecond) && row.Metrics["view_max_ns"] < int64(250*time.Millisecond)
	if !visible {
		row.Pass = row.Pass && learned > 0 && row.Transported > 0
	} else {
		row.Pass = row.Pass && row.Transported == 0
	}
	return finishEagerTrialV44_CohortV46(s, joinedTrialV25{scheduledTrialV24: row, Joined: true, Batches: append([]joinedBatchV25(nil), s.batches...)})
}
func TestResearchEagerTracedOwnerAndDurabilityV44_CohortV46(t *testing.T) {
	if os.Getenv("EVENTFRAME_RUN_EAGER_LOAD_V44") != "1" {
		t.Skip("explicit isolated native control")
	}
	for _, mode := range []int{-2, 4} {
		for _, enabled := range []bool{false, true} {
			t.Run(map[int]string{-2: "joined", 4: "archive"}[mode]+map[bool]string{false: "-lazy", true: "-eager"}[enabled], func(t *testing.T) {
				ctx := context.Background()
				f := createWitnessFixtureV23(t, true)
				defer f.close()
				s := attachLoadEagerV44_CohortV46(t, f, mode, enabled)
				defer s.closeV37()
				prime, _, err := s.recall(ctx, f.svc, f.request(time.Now().UTC(), "prime"))
				if err != nil {
					t.Fatal(err)
				}
				j, err := s.eager.authority.gate.store.GetBayesianJournal(ctx, "tenant-a", prime.BayesianShadow.JournalID)
				if err != nil || durableWireV42(j, prime) != nil {
					t.Fatal("prime full durable wire", err)
				}
				if enabled {
					if len(s.eager.preparations) != 1 || !s.eager.preparations[0].Built || s.eager.preparations[0].Kind != "journal" || !reflect.DeepEqual(s.eager.preparations[0].OperationIDs, []string{j.ID}) {
						t.Fatal("prime preparation trace")
					}
				} else if len(s.eager.preparations) != 0 {
					t.Fatal("disabled hidden preparation")
				}
				entered := make(chan struct{}, 1)
				resume := make(chan struct{})
				s.metadata.afterProjection = func(context.Context) {
					entered <- struct{}{}
					<-resume
				}
				s.eager.authority.owner.Lock()
				held := true
				released := false
				release := func() {
					if held {
						s.eager.authority.owner.Unlock()
						held = false
					}
					if !released {
						close(resume)
						released = true
					}
				}
				type response struct {
					packet model.ContextPacket
					err    error
				}
				done := make(chan response, 1)
				go func() {
					p, _, e := s.recall(ctx, f.svc, f.request(time.Now().UTC(), "held"))
					done <- response{p, e}
				}()
				terminal := false
				defer func() {
					release()
					if !terminal {
						select {
						case <-done:
						case <-time.After(5 * time.Second):
							t.Error("held request not drained")
						}
					}
				}()
				if enabled {
					select {
					case <-entered:
					case <-time.After(time.Second):
						t.Fatal("eager nomination blocked")
					}
				} else {
					select {
					case <-entered:
						t.Fatal("lazy unexpectedly warmed first head")
					case <-time.After(10 * time.Millisecond):
					}
				}
				select {
				case r := <-done:
					terminal = true
					t.Fatal("packet before full owner release", r.err)
				case <-time.After(10 * time.Millisecond):
				}
				release()
				select {
				case r := <-done:
					terminal = true
					if r.err != nil {
						t.Fatal(r.err)
					}
					j, e := s.eager.authority.gate.store.GetBayesianJournal(ctx, "tenant-a", r.packet.BayesianShadow.JournalID)
					if e != nil || durableWireV42(j, r.packet) != nil {
						t.Fatal("held durable wire", e)
					}
				case <-time.After(5 * time.Second):
					t.Fatal("held request unfinished")
				}
				s.metadata.afterProjection = nil
				if enabled {
					if len(s.eager.preparations) != 2 || !s.eager.preparations[1].Reused {
						t.Fatal("same-head preparation missing")
					}
					cancelled, cancel := context.WithCancel(ctx)
					cancel()
					if !errors.Is(s.eager.refresh(cancelled, "control"), context.Canceled) {
						t.Fatal("cancelled preparation accepted")
					}
					last := s.eager.preparations[len(s.eager.preparations)-1]
					if last.Owner || !last.OwnerAt.IsZero() || last.Built || last.Error == "" {
						t.Fatal("cancelled work attribution")
					}
					for _, trace := range s.eager.preparations[:len(s.eager.preparations)-1] {
						if !trace.Owner || trace.OwnerAt.Before(trace.Begin) || trace.OwnerAt.After(trace.End) || (trace.Built && trace.BuiltAt.Before(trace.OwnerAt)) {
							t.Fatal("owner-time attribution", trace)
						}
					}
				}
				s.eager.authority.poison.Store(true)
				if _, _, e := s.recall(ctx, f.svc, f.request(time.Now().UTC(), "poison")); !errors.Is(e, store.ErrStaleSnapshot) {
					t.Fatal("poison delivered", e)
				}
				s.eager.authority.poison.Store(false)
			})
		}
	}
}
