// Code generated by research-handoff-observer-gen; DO NOT EDIT.
package libravdbstore

import (
	"context"
	"github.com/JuanHuaXu/eventframed/internal/bayes"
	"github.com/JuanHuaXu/eventframed/internal/model"
	"github.com/JuanHuaXu/eventframed/internal/residual"
	"github.com/JuanHuaXu/eventframed/internal/store"
	"time"
)

const handoffMethodCountV27 = 31

var _ store.EventStore = (*handoffObserverV27)(nil)

func (p *handoffObserverV27) BindBayesianPolicy(ctx context.Context, digest string) (model.Snapshot, error) {
	p.observe("BindBayesianPolicy")
	return p.EventStore.BindBayesianPolicy(ctx, digest)
}
func (p *handoffObserverV27) Put(ctx context.Context, event model.Event, vector []float32, digest string) (store.PutResult, error) {
	p.observe("Put")
	return p.EventStore.Put(ctx, event, vector, digest)
}
func (p *handoffObserverV27) PutComposition(ctx context.Context, event model.Event, vector []float32, digest string, base model.Snapshot) (store.PutResult, error) {
	p.observe("PutComposition")
	return p.EventStore.PutComposition(ctx, event, vector, digest, base)
}
func (p *handoffObserverV27) Delete(ctx context.Context, tenantID, eventID string) (store.DeleteResult, error) {
	p.observe("Delete")
	return p.EventStore.Delete(ctx, tenantID, eventID)
}
func (p *handoffObserverV27) DeleteComposition(ctx context.Context, tenantID, eventID, reason string, decomposedAt time.Time) (store.CompositionDeleteResult, error) {
	p.observe("DeleteComposition")
	return p.EventStore.DeleteComposition(ctx, tenantID, eventID, reason, decomposedAt)
}
func (p *handoffObserverV27) GetCompositionTombstone(ctx context.Context, tenantID, eventID string) (model.CompositionTombstone, error) {
	p.observe("GetCompositionTombstone")
	return p.EventStore.GetCompositionTombstone(ctx, tenantID, eventID)
}
func (p *handoffObserverV27) DeleteBefore(ctx context.Context, tenantID string, before time.Time, limit int) (store.RetentionResult, error) {
	p.observe("DeleteBefore")
	return p.EventStore.DeleteBefore(ctx, tenantID, before, limit)
}
func (p *handoffObserverV27) Backup(ctx context.Context, destination string) error {
	p.observe("Backup")
	return p.EventStore.Backup(ctx, destination)
}
func (p *handoffObserverV27) Compact(ctx context.Context) error {
	p.observe("Compact")
	return p.EventStore.Compact(ctx)
}
func (p *handoffObserverV27) Search(ctx context.Context, tenantID string, vector []float32, availableBy time.Time, limit int) ([]store.SearchResult, error) {
	p.observe("Search")
	return p.EventStore.Search(ctx, tenantID, vector, availableBy, limit)
}
func (p *handoffObserverV27) GetEvents(ctx context.Context, tenantID string, eventIDs []string, availableBy time.Time) ([]model.Event, error) {
	p.observe("GetEvents")
	return p.EventStore.GetEvents(ctx, tenantID, eventIDs, availableBy)
}
func (p *handoffObserverV27) GetBayesianJournal(ctx context.Context, tenantID, journalID string) (model.BayesianJournalEntry, error) {
	p.observe("GetBayesianJournal")
	return p.EventStore.GetBayesianJournal(ctx, tenantID, journalID)
}
func (p *handoffObserverV27) PublishSelectionCertificate(ctx context.Context, certificate model.SelectionSupportCertificate) (model.Snapshot, error) {
	p.observe("PublishSelectionCertificate")
	return p.EventStore.PublishSelectionCertificate(ctx, certificate)
}
func (p *handoffObserverV27) GetSelectionCertificate(ctx context.Context, tenantID string) (model.SelectionSupportCertificate, error) {
	p.observe("GetSelectionCertificate")
	return p.EventStore.GetSelectionCertificate(ctx, tenantID)
}
func (p *handoffObserverV27) PublishAntiPigeonCertificate(ctx context.Context, certificate model.AntiPigeonCertificate) (model.Snapshot, error) {
	p.observe("PublishAntiPigeonCertificate")
	return p.EventStore.PublishAntiPigeonCertificate(ctx, certificate)
}
func (p *handoffObserverV27) GetAntiPigeonCertificate(ctx context.Context, tenantID string, eventIDs []string) (model.AntiPigeonCertificate, error) {
	p.observe("GetAntiPigeonCertificate")
	return p.EventStore.GetAntiPigeonCertificate(ctx, tenantID, eventIDs)
}
func (p *handoffObserverV27) PublishOmittedInfluenceCertificate(ctx context.Context, certificate model.OmittedInfluenceCertificate) (model.Snapshot, error) {
	p.observe("PublishOmittedInfluenceCertificate")
	return p.EventStore.PublishOmittedInfluenceCertificate(ctx, certificate)
}
func (p *handoffObserverV27) GetOmittedInfluenceCertificate(ctx context.Context, tenantID string) (model.OmittedInfluenceCertificate, error) {
	p.observe("GetOmittedInfluenceCertificate")
	return p.EventStore.GetOmittedInfluenceCertificate(ctx, tenantID)
}
func (p *handoffObserverV27) ApplyBayesianOutcome(ctx context.Context, request model.BayesianOutcomeRequest, posteriorKey, parentPosteriorKey, digest string, weight float64, changePolicy bayes.ChangePolicy, groupPolicy bayes.GroupPolicy, residualObservation model.ResidualObservation, residualPolicy residual.Policy) (store.BayesianOutcomeResult, error) {
	p.observe("ApplyBayesianOutcome")
	return p.EventStore.ApplyBayesianOutcome(ctx, request, posteriorKey, parentPosteriorKey, digest, weight, changePolicy, groupPolicy, residualObservation, residualPolicy)
}
func (p *handoffObserverV27) GetBayesianPosterior(ctx context.Context, tenantID, posteriorKey string) (model.BayesianPosterior, error) {
	p.observe("GetBayesianPosterior")
	return p.EventStore.GetBayesianPosterior(ctx, tenantID, posteriorKey)
}
func (p *handoffObserverV27) GetResidualCandidates(ctx context.Context, tenantID, actionKey, generalKey string) (model.ResidualCandidates, error) {
	p.observe("GetResidualCandidates")
	return p.EventStore.GetResidualCandidates(ctx, tenantID, actionKey, generalKey)
}
func (p *handoffObserverV27) GetPredictiveGraph(ctx context.Context, tenantID string) (model.PredictiveGraph, error) {
	p.observe("GetPredictiveGraph")
	return p.EventStore.GetPredictiveGraph(ctx, tenantID)
}
func (p *handoffObserverV27) PublishPredictiveSnap(ctx context.Context, record model.PredictiveSnapRecord) (model.PredictiveGraph, model.Snapshot, error) {
	p.observe("PublishPredictiveSnap")
	return p.EventStore.PublishPredictiveSnap(ctx, record)
}
func (p *handoffObserverV27) RollbackPredictiveSnap(ctx context.Context, tenantID, snapID, reason string) (model.PredictiveGraph, model.Snapshot, error) {
	p.observe("RollbackPredictiveSnap")
	return p.EventStore.RollbackPredictiveSnap(ctx, tenantID, snapID, reason)
}
func (p *handoffObserverV27) PutAgencyProposal(ctx context.Context, record model.AgencyProposalRecord, digest string, maxPerChain, maxPending int, evidenceAvailableBy time.Time) (store.AgencyPutResult, error) {
	p.observe("PutAgencyProposal")
	return p.EventStore.PutAgencyProposal(ctx, record, digest, maxPerChain, maxPending, evidenceAvailableBy)
}
func (p *handoffObserverV27) ClaimAgencyProposals(ctx context.Context, tenantID, consumerID string, now time.Time, limit int, lease time.Duration) ([]model.AgencyProposalRecord, model.Snapshot, error) {
	p.observe("ClaimAgencyProposals")
	return p.EventStore.ClaimAgencyProposals(ctx, tenantID, consumerID, now, limit, lease)
}
func (p *handoffObserverV27) ResolveAgencyProposal(ctx context.Context, request model.ResolveAgencyProposalRequest, now time.Time) (store.AgencyResolveResult, error) {
	p.observe("ResolveAgencyProposal")
	return p.EventStore.ResolveAgencyProposal(ctx, request, now)
}
func (p *handoffObserverV27) Stats(ctx context.Context) (store.Stats, error) {
	p.observe("Stats")
	return p.EventStore.Stats(ctx)
}
func (p *handoffObserverV27) Snapshot(ctx context.Context) model.Snapshot {
	p.observe("Snapshot")
	return p.EventStore.Snapshot(ctx)
}
func (p *handoffObserverV27) Close() error {
	p.observe("Close")
	return p.EventStore.Close()
}
