// Code generated by research-archive-cost-gen; DO NOT EDIT.
package libravdbstore

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"sync"
	"testing"
	"time"
)

func runBatchArchiveLoadV34(t *testing.T, trial int, mode int, visible bool) archiveTrialV34 {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()
	f := createWitnessFixtureV23(t, true)
	defer f.close()
	s := attachLoadArchiveV34(t, f, mode)
	defer s.closeV34()
	a := f.adapter
	prime, _, err := s.recall(ctx, f.svc, f.request(time.Now().UTC(), "prime"))
	if err != nil {
		t.Fatal(err)
	}
	var events []string
	for _, d := range prime.BayesianShadow.Decisions {
		if d.Activated {
			events = append(events, d.EventID)
			if len(events) == 16 {
				break
			}
		}
	}
	if len(events) != 16 {
		t.Fatal("prime activation")
	}
	start := time.Now().Add(20 * time.Millisecond)
	jobs := make(chan recallLoadOfferV16, 128)
	writeJobs := make(chan sortLoadWriteJob, 128)
	outcomeJobs := make(chan outcomeOfferV18, 16)
	reads := make(chan witnessReadV23, 128)
	writes := make(chan []witnessWriteV23, 1)
	outcomes := make(chan []witnessOutcomeV23, 1)
	waitUntil := func(at time.Time) bool {
		timer := time.NewTimer(time.Until(at))
		select {
		case <-timer.C:
			return true
		case <-ctx.Done():
			timer.Stop()
			return false
		}
	}
	go func() {
		defer close(jobs)
		for i := 0; i < 128; i++ {
			if !waitUntil(start.Add(time.Duration(i) * 4 * time.Millisecond)) {
				return
			}
			jobs <- recallLoadOfferV16{index: i, offered: time.Now().UTC()}
		}
	}()
	go func() {
		defer close(writeJobs)
		for i := 0; i < 128; i++ {
			if !waitUntil(start.Add(time.Duration(i) * 4 * time.Millisecond)) {
				return
			}
			at := f.origin.Add(time.Hour)
			if visible {
				at = f.origin
			}
			w := pinnedWrite(fmt.Sprintf("write-%03d", i), at)
			w.Vector = denseRowV6(f.query, i, .00213*float64(i+1))
			writeJobs <- sortLoadWriteJob{write: w, offered: time.Now().UTC()}
		}
	}()
	go func() {
		var rows []witnessWriteV23
		for {
			group, closed := sortLoadTakeGroup(writeJobs, 16, 16*time.Millisecond)
			if len(group) == 0 {
				break
			}
			batch := make([]ResearchEventWrite, len(group))
			for j, job := range group {
				batch[j] = job.write
			}
			snap, err := s.append(ctx, batch, false)
			ack := time.Now().UTC()
			for _, job := range group {
				r := witnessWriteV23{Index: len(rows), Offer: job.offered, Ack: ack, Snapshot: snap, Available: job.write.Event.AvailableAt}
				if err != nil {
					r.Error = err.Error()
				}
				rows = append(rows, r)
			}
			if closed || err != nil {
				break
			}
		}
		writes <- rows
	}()
	go func() {
		defer close(outcomeJobs)
		for i, event := range events {
			if !waitUntil(start.Add(20*time.Millisecond + time.Duration(i)*16*time.Millisecond)) {
				return
			}
			offer := time.Now().UTC()
			outcomeJobs <- outcomeOfferV18{index: i, request: f.outcomeRequest(prime.BayesianShadow.JournalID, event, fmt.Sprintf("load-%d", i), i%2 == 0, offer)}
		}
	}()
	go func() {
		var rows []witnessOutcomeV23
		for job := range outcomeJobs {
			response, err := f.svc.ObserveBayesianOutcome(ctx, job.request)
			r := witnessOutcomeV23{Index: job.index, EventID: job.request.EventID, Useful: job.request.Useful, Offer: job.request.AvailableAt, Published: time.Now().UTC(), Response: response, Request: job.request}
			if err != nil {
				r.Error = err.Error()
			}
			rows = append(rows, r)
			if err != nil {
				break
			}
		}
		outcomes <- rows
	}()
	var wg sync.WaitGroup
	for worker := 0; worker < 8; worker++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for job := range jobs {
				began := time.Now().UTC()
				request := f.request(job.offered, "load")
				packet, view, err := s.recall(ctx, f.svc, request)
				r := witnessReadV23{Index: job.index, Offer: job.offered, Start: began, End: time.Now().UTC(), Snapshot: packet.Snapshot, Journal: packet.BayesianShadow.JournalID, Decisions: packet.BayesianShadow.Decisions, Packed: packet.Candidates, Request: request, Selection: packet.BayesianShadow.SelectionSupportCertified, Omitted: packet.BayesianShadow.OmittedInfluenceCertified}
				if view != nil {
					r.ViewAt = view.at.UTC()
					r.PinSnapshot = view.snapshot
				}
				if err != nil {
					r.Error = err.Error()
				}
				reads <- r
			}
		}()
	}
	go func() { wg.Wait(); close(reads) }()
	row := scheduledTrialV24{witnessTrialV23: witnessTrialV23{Trial: trial, Enabled: true, Visible: visible, Metrics: map[string]int64{}, Origin: f.origin, InitialSnapshot: prime.Snapshot}, Scheduled: true}
	for r := range reads {
		row.Reads = append(row.Reads, r)
	}
	row.Writes = <-writes
	row.Outcomes = <-outcomes
	row.Admission = s.scheduler.Snapshot()
	s.traceMu.Lock()
	row.Trace = append([]scheduledWaitV24(nil), s.trace...)
	s.traceMu.Unlock()
	row.Transported = a.transports.Load()
	row.WitnessHash = a.state.Hash
	row.FinalSnapshot = a.gate.store.Snapshot(ctx)
	row.FinalWitness = *a.state
	commitRows, err := a.gate.sidecar.QueryContext(ctx, "SELECT seq,payload,prior,digest FROM witness_v23 ORDER BY seq")
	if err != nil {
		t.Fatal(err)
	}
	for commitRows.Next() {
		var c witnessCommitV23
		if err := commitRows.Scan(&c.Seq, &c.Payload, &c.Prior, &c.Digest); err != nil {
			commitRows.Close()
			t.Fatal(err)
		}
		row.Commits = append(row.Commits, c)
	}
	if err := commitRows.Err(); err != nil {
		t.Fatal(err)
	}
	commitRows.Close()
	for _, event := range events {
		p, err := a.gate.store.GetBayesianPosterior(ctx, "tenant-a", event)
		if err != nil {
			row.Errors = append(row.Errors, "missing durable source")
		}
		row.DurableSources = append(row.DurableSources, p)
	}
	if len(row.Reads) != 128 || len(row.Writes) != 128 || len(row.Outcomes) != 16 {
		row.Errors = append(row.Errors, "incomplete offered work")
	}
	var readNS, offerNS, viewNS, writeNS, outcomeNS []int64
	learned := 0
	for _, r := range row.Reads {
		readNS = append(readNS, r.End.Sub(r.Start).Nanoseconds())
		offerNS = append(offerNS, r.End.Sub(r.Offer).Nanoseconds())
		viewNS = append(viewNS, r.End.Sub(r.ViewAt).Nanoseconds())
		if r.Error != "" || r.Journal == "" || len(r.Decisions) != 150 {
			row.Errors = append(row.Errors, "invalid Recall/journal")
		}
		saved, err := a.gate.store.GetBayesianJournal(ctx, "tenant-a", r.Journal)
		got, marshalErr := json.Marshal(saved.Report.Decisions)
		want, _ := json.Marshal(r.Decisions)
		if err != nil || marshalErr != nil || saved.Snapshot != r.Snapshot || !bytes.Equal(got, want) {
			row.Errors = append(row.Errors, "wire journal mismatch")
		}
		h := sha256.Sum256(got)
		row.JournalProofs = append(row.JournalProofs, scheduledJournalV24{r.Index, saved.Snapshot, hex.EncodeToString(h[:])})
		for _, d := range r.Decisions {
			if d.Forecast.BeliefLaw != nil {
				learned++
			}
		}
	}
	for _, w := range row.Writes {
		writeNS = append(writeNS, w.Ack.Sub(w.Offer).Nanoseconds())
		if w.Error != "" {
			row.Errors = append(row.Errors, "write: "+w.Error)
		}
	}
	for _, o := range row.Outcomes {
		outcomeNS = append(outcomeNS, o.Published.Sub(o.Offer).Nanoseconds())
		if o.Error != "" || o.Response.Duplicate {
			row.Errors = append(row.Errors, "outcome: "+o.Error)
		}
	}
	row.Metrics["learned_decisions"] = int64(learned)
	for name, values := range map[string][]int64{"call": readNS, "offer": offerNS, "view": viewNS, "write": writeNS, "outcome": outcomeNS} {
		row.Metrics[name+"_p99_ns"] = pinnedPercentile(values, .99).Nanoseconds()
		row.Metrics[name+"_max_ns"] = pinnedPercentile(values, 1).Nanoseconds()
	}
	if a.poison.Load() || a.state.Head != row.FinalSnapshot {
		row.Errors = append(row.Errors, "invalid witness head")
	}
	if _, ready := a.gate.capture(ctx); !ready {
		row.Errors = append(row.Errors, "marker not READY")
	}
	if row.Admission.ActiveWriter || row.Admission.ActiveReaders != 0 || row.Admission.Queued != ([3]int{}) {
		row.Errors = append(row.Errors, "undrained admission")
	}
	row.Pass = len(row.Errors) == 0 && row.Metrics["call_p99_ns"] < int64(100*time.Millisecond) && row.Metrics["offer_p99_ns"] < int64(100*time.Millisecond) && row.Metrics["write_p99_ns"] < int64(250*time.Millisecond) && row.Metrics["outcome_p99_ns"] < int64(100*time.Millisecond) && row.Metrics["outcome_max_ns"] < int64(250*time.Millisecond) && row.Metrics["view_max_ns"] < int64(250*time.Millisecond)
	if !visible {
		row.Pass = row.Pass && learned > 0 && row.Transported > 0
	} else {
		row.Pass = row.Pass && row.Transported == 0
	}
	return finishArchiveTrialV34(s, joinedTrialV25{scheduledTrialV24: row, Joined: true, Batches: append([]joinedBatchV25(nil), s.batches...)})
}
func TestResearchBatchArchiveLoadV34(t *testing.T) {
	output := os.Getenv("EVENTFRAME_ARCHIVE_COST_V34_OUTPUT")
	if output == "" {
		t.Skip("exclusive frozen joined workload")
	}
	manifest, err := os.ReadFile("../../../research/archive-cost-v34/freeze.json")
	if err != nil {
		t.Fatal(err)
	}
	h := sha256.Sum256(manifest)
	f, err := os.OpenFile(output, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600)
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	enc := json.NewEncoder(f)
	if err := enc.Encode(map[string]any{"Type": "header", "Trials": 20, "FreezeSHA256": hex.EncodeToString(h[:]), "Time": time.Now().UTC()}); err != nil {
		t.Fatal(err)
	}
	for trial := 1; trial <= 2; trial++ {
		for _, visible := range []bool{false, true} {
			for _, mode := range []int{-1, 0, 1, 2, 3} {
				r := runBatchArchiveLoadV34(t, trial, mode, visible)
				if err := enc.Encode(r); err != nil {
					t.Fatal(err)
				}
				if err := f.Sync(); err != nil {
					t.Fatal(err)
				}
				t.Logf("trial=%d combined=%v visible=%v pass=%v errors=%v metrics=%v transported=%d", trial, mode, visible, r.Pass, r.Errors, r.Metrics, r.Transported)
			}
		}
	}
	if err := enc.Encode(map[string]any{"Type": "footer", "Trials": 20}); err != nil {
		t.Fatal(err)
	}
	if err := f.Sync(); err != nil {
		t.Fatal(err)
	}
}
