package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"strconv"
)

func sha(b []byte) string { h := sha256.Sum256(b); return hex.EncodeToString(h[:]) }
func exclusive(p string, b []byte) error {
	f, err := os.OpenFile(p, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600)
	if err != nil {
		return err
	}
	defer f.Close()
	if _, err = f.Write(b); err != nil {
		return err
	}
	return f.Sync()
}
func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
func run() error {
	const source, target = "internal/researchdispersion/hybrid_fixture_v48_test.go", "internal/researchdispersion/scored_fixture_v51_generated_test.go"
	input, err := os.ReadFile(source)
	if err != nil {
		return err
	}
	set := token.NewFileSet()
	f, err := parser.ParseFile(set, source, input, parser.ParseComments)
	if err != nil {
		return err
	}
	names := map[string]string{"hybridCohortV48": "scoredCohortV51", "TestSpecialistActualSeedSeparationV48": "TestScoredV51SeedSeparation", "TestSpecialistFixtureV48": "TestScoredV51Fixture"}
	ast.Inspect(f, func(n ast.Node) bool {
		if x, ok := n.(*ast.Ident); ok {
			if v, yes := names[x.Name]; yes {
				x.Name = v
			}
		}
		return true
	})
	seeds, separation, envs := 0, 0, 0
	for _, d := range f.Decls {
		fn, ok := d.(*ast.FuncDecl)
		if !ok {
			continue
		}
		ast.Inspect(fn, func(n ast.Node) bool {
			if x, ok := n.(*ast.BasicLit); ok {
				if fn.Name.Name == "scoredCohortV51" {
					if v, found := map[string]string{"2026104807": "2026105107", "2026104809": "2026105109", "2026104811": "2026105111"}[x.Value]; found {
						x.Value = v
						seeds++
					}
				}
				if x.Kind == token.STRING {
					if v, found := map[string]string{strconv.Quote("EVENTFRAME_HYBRID_V48_FIXTURE"): strconv.Quote("EVENTFRAME_SCORED_V51_FIXTURE"), strconv.Quote("EVENTFRAME_HYBRID_V48_SPLIT"): strconv.Quote("EVENTFRAME_SCORED_V51_SPLIT")}[x.Value]; found {
						x.Value = v
						envs++
					}
				}
			}
			if fn.Name.Name == "TestScoredV51SeedSeparation" {
				if x, ok := n.(*ast.CompositeLit); ok && len(x.Elts) == 17 {
					for _, v := range []string{"2026105107", "2026105109", "2026105111"} {
						x.Elts = append(x.Elts, &ast.BasicLit{Kind: token.INT, Value: v})
					}
					separation++
				}
			}
			return true
		})
	}
	if seeds != 3 || separation != 1 || envs != 2 {
		return fmt.Errorf("edit counts %d/%d/%d", seeds, separation, envs)
	}
	var b bytes.Buffer
	if err := format.Node(&b, set, f); err != nil {
		return err
	}
	output, err := format.Source(append([]byte("// Code generated by research-scored-fixture-gen; DO NOT EDIT.\n"), b.Bytes()...))
	if err != nil {
		return err
	}
	if err := exclusive(target, output); err != nil {
		return err
	}
	m, _ := json.MarshalIndent(map[string]any{"source": source, "target": target, "sourceSHA256": sha(input), "targetSHA256": sha(output), "newSeedBases": []int64{2026105107, 2026105109, 2026105111}, "oldBasesRetainedInSeparation": 17, "generatorAndControlCallsUnchanged": true}, "", "  ")
	if err := exclusive("research/scored-v51-fixture-generation.json", append(m, '\n')); err != nil {
		return err
	}
	fmt.Println(string(m))
	return nil
}
