// Mechanical normal-cohort harness fork. No statistical or model changes.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"strings"
)

func main() {
	const source = "internal/researchswitch/hybrid_study_v48_test.go"
	const dest = "internal/researchswitch/memo_normal_v49_generated_test.go"
	b, e := os.ReadFile(source)
	must(e)
	fset := token.NewFileSet()
	f, e := parser.ParseFile(fset, source, b, 0)
	must(e)
	var fn *ast.FuncDecl
	for _, d := range f.Decls {
		if x, ok := d.(*ast.FuncDecl); ok && x.Name.Name == "TestHybridV48Study" {
			fn = x
		}
	}
	if fn == nil {
		panic("missing original collector harness")
	}
	var original bytes.Buffer
	must(format.Node(&original, fset, fn))
	names := map[string]string{"TestHybridV48Study": "TestMemoV49Normal", "collectHybridV48": "collectMemoV49"}
	counts := map[string]int{}
	ast.Inspect(fn, func(n ast.Node) bool {
		if x, ok := n.(*ast.Ident); ok {
			if name, ok := names[x.Name]; ok {
				counts[x.Name]++
				x.Name = name
			}
		}
		return true
	})
	if counts["TestHybridV48Study"] != 1 || counts["collectHybridV48"] != 1 {
		panic("unexpected rewrite cardinality")
	}
	var output bytes.Buffer
	output.WriteString("// Code generated by research-memo-normal-gen; DO NOT EDIT.\npackage researchswitch\nimport (\"bufio\";\"encoding/json\";\"io\";\"os\";\"testing\")\n")
	must(format.Node(&output, fset, fn))
	out, e := format.Source(output.Bytes())
	must(e)
	ast.Inspect(fn, func(n ast.Node) bool {
		if x, ok := n.(*ast.Ident); ok {
			for old, name := range names {
				if x.Name == name {
					x.Name = old
				}
			}
		}
		return true
	})
	var inverse bytes.Buffer
	must(format.Node(&inverse, fset, fn))
	if !bytes.Equal(original.Bytes(), inverse.Bytes()) {
		panic("harness inverse mismatch")
	}
	write(dest, out)
	const oldReader = "research/hybrid-v48-env-repair-readback.mjs"
	r, e := os.ReadFile(oldReader)
	must(e)
	s := string(r)
	from := "const root='research/hybrid-v48-env-repair-'+stage,done="
	to := "const root='research/memo-v49-normal',done="
	if strings.Count(s, from) != 1 || strings.Count(s, "cost.constructorMaxBytes<=8<<20") != 1 {
		panic("reader rewrite cardinality")
	}
	s = strings.Replace(s, from, to, 1)
	s = strings.Replace(s, "cost.constructorMaxBytes<=8<<20", "cost.constructorMaxBytes.memo<=8<<20", 1)
	if strings.Replace(strings.Replace(s, to, from, 1), "cost.constructorMaxBytes.memo<=8<<20", "cost.constructorMaxBytes<=8<<20", 1) != string(r) {
		panic("reader inverse mismatch")
	}
	const newReader = "research/memo-v49-normal-readback-generated.mjs"
	write(newReader, []byte(s))
	report := map[string]any{"source": source, "sourceSHA256": hash(b), "destination": dest, "destinationSHA256": hash(out), "rewrites": counts, "inverseHarnessEqual": true, "originalReader": oldReader, "originalReaderSHA256": hash(r), "reader": newReader, "readerSHA256": hash([]byte(s)), "readerChanges": []string{"artifact root", "memo allocation field"}, "inverseReaderEqual": true, "qualityGatesChanged": false}
	r, e = json.MarshalIndent(report, "", "  ")
	must(e)
	write("research/memo-v49-normal-generation.json", append(r, '\n'))
}
func hash(b []byte) string { return fmt.Sprintf("%x", sha256.Sum256(b)) }
func write(p string, b []byte) {
	w, e := os.OpenFile(p, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600)
	must(e)
	_, e = w.Write(b)
	must(e)
	must(w.Sync())
	must(w.Close())
}
func must(e error) {
	if e != nil {
		panic(e)
	}
}
