// Preserve the entire sealed offered workload except declared wrapper names.
package main

import (
	"bytes"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"strconv"
)

func main() {
	f, e := parser.ParseFile(token.NewFileSet(), "internal/store/libravdbstore/research_metadata_core_load_v36_generated_test.go", nil, 0)
	if e != nil {
		panic(e)
	}
	renames := map[string]string{"runMetadataCoreLoadV36": "runWarmSearchLoadV37", "TestResearchMetadataCoreLoadV36": "TestResearchWarmSearchLoadV37", "attachLoadCoreV36": "attachLoadWarmV37", "finishCoreTrialV36": "finishWarmTrialV37", "closeV36": "closeV37", "coreTrialV36": "warmTrialV37"}
	ast.Inspect(f, func(n ast.Node) bool {
		if id, ok := n.(*ast.Ident); ok {
			if name, ok := renames[id.Name]; ok {
				id.Name = name
			}
		}
		if l, ok := n.(*ast.BasicLit); ok && l.Kind == token.STRING {
			v, _ := strconv.Unquote(l.Value)
			if v == "EVENTFRAME_METADATA_CORE_V36_OUTPUT" {
				l.Value = strconv.Quote("EVENTFRAME_WARM_SEARCH_V37_OUTPUT")
			}
			if v == "../../../research/metadata-core-v36/freeze.json" {
				l.Value = strconv.Quote("../../../research/warm-search-v37/freeze.json")
			}
		}
		return true
	})
	var b bytes.Buffer
	if e = format.Node(&b, token.NewFileSet(), f); e != nil {
		panic(e)
	}
	data, e := format.Source(b.Bytes())
	if e != nil {
		panic(e)
	}
	if e = os.WriteFile("internal/store/libravdbstore/research_warm_search_load_v37_generated_test.go", append([]byte("// Code generated by research-warm-search-gen; DO NOT EDIT.\n"), data...), 0600); e != nil {
		panic(e)
	}
}
