// Structured collector/auditor forks; scope-only edits are counted explicitly.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
)

func sha(b []byte) string { h := sha256.Sum256(b); return hex.EncodeToString(h[:]) }
func stmt(src string) []ast.Stmt {
	f, err := parser.ParseFile(token.NewFileSet(), "fragment", "package p;func f(){"+src+"}", 0)
	if err != nil {
		panic(err)
	}
	return f.Decls[0].(*ast.FuncDecl).Body.List
}
func exclusive(p string, b []byte) error {
	f, err := os.OpenFile(p, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600)
	if err != nil {
		return err
	}
	defer f.Close()
	if _, err = f.Write(b); err != nil {
		return err
	}
	return f.Sync()
}
func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
func run() error {
	meta := []map[string]any{}
	for _, spec := range []struct{ source, old, name, target string }{
		{"internal/researchswitch/memo_collector_v49_generated_test.go", "collectMemoV49", "collectScoredV51", "internal/researchswitch/scored_collector_v51_generated_test.go"},
		{"internal/researchswitch/hybrid_study_v48_test.go", "auditHybridV48", "auditScoredV51", "internal/researchswitch/scored_audit_v51_generated_test.go"},
	} {
		original, err := os.ReadFile(spec.source)
		if err != nil {
			return err
		}
		set := token.NewFileSet()
		f, err := parser.ParseFile(set, spec.source, original, 0)
		if err != nil {
			return err
		}
		var fn *ast.FuncDecl
		for _, d := range f.Decls {
			if v, ok := d.(*ast.FuncDecl); ok && v.Name.Name == spec.old {
				fn = v
			}
		}
		if fn == nil {
			return fmt.Errorf("missing function %s", spec.old)
		}
		fn.Name.Name = spec.name
		fn.Type.Params.List = append(fn.Type.Params.List, &ast.Field{Names: []*ast.Ident{ast.NewIdent("style")}, Type: ast.NewIdent("string")})
		calls, laws := 0, 0
		ast.Inspect(fn, func(n ast.Node) bool {
			if id, ok := n.(*ast.Ident); ok && spec.old == "collectMemoV49" {
				if id.Name == "HybridTicket" {
					id.Name = "ScoredHybridTicketV51"
				}
			}
			if c, ok := n.(*ast.CallExpr); ok {
				if id, ok := c.Fun.(*ast.Ident); ok && id.Name == "NewMemoHybridV49" {
					id.Name = "NewScoredHybridV51"
					c.Args = append(c.Args, ast.NewIdent("style"))
					calls++
				}
				if sel, ok := c.Fun.(*ast.SelectorExpr); ok && sel.Sel.Name == "End" {
					if id, ok := sel.X.(*ast.Ident); ok && id.Name == "researchhybridref" {
						id.Name = "researchscoreref"
						c.Args = append(c.Args, ast.NewIdent("style"))
						calls++
					}
				}
			}
			return true
		})
		if spec.old == "auditHybridV48" {
			ast.Inspect(fn, func(n ast.Node) bool {
				if b, ok := n.(*ast.BlockStmt); ok {
					var list []ast.Stmt
					for _, s := range b.List {
						match := false
						if a, ok := s.(*ast.AssignStmt); ok && len(a.Rhs) == 1 {
							var expr bytes.Buffer
							format.Node(&expr, set, a.Rhs[0])
							match = expr.String() == "sw[0]*heads[0] + sw[1]*heads[1]"
						}
						if match {
							list = append(list, stmt(`q,err:=researchscoreref.Forecast(sw,heads[:],style);if err!=nil{return err}`)...)
							laws++
						} else {
							list = append(list, s)
						}
					}
					b.List = list
				}
				return true
			})
		}
		if calls != 1 || (spec.old == "auditHybridV48" && laws != 2) {
			return fmt.Errorf("unexpected edit counts %s %d/%d", spec.old, calls, laws)
		}
		var out bytes.Buffer
		if spec.old == "collectMemoV49" {
			out.WriteString("// Code generated by research-scored-study-gen; DO NOT EDIT.\npackage researchswitch\nimport \"time\"\n")
		} else {
			out.WriteString("// Code generated by research-scored-study-gen; DO NOT EDIT.\npackage researchswitch\nimport(\"fmt\";\"github.com/JuanHuaXu/eventframed/internal/researchswitchref\";\"github.com/JuanHuaXu/eventframed/internal/researchscoreref\")\n")
		}
		if err := format.Node(&out, set, fn); err != nil {
			return err
		}
		generated, err := format.Source(out.Bytes())
		if err != nil {
			return err
		}
		if err := exclusive(spec.target, generated); err != nil {
			return err
		}
		meta = append(meta, map[string]any{"source": spec.source, "target": spec.target, "sourceSHA256": sha(original), "targetSHA256": sha(generated), "function": spec.old, "constructorOrScopeStateCalls": calls, "servedLawExpressionsChanged": laws})
	}
	b, err := json.MarshalIndent(meta, "", "  ")
	if err != nil {
		return err
	}
	if err := exclusive("research/scored-v51-study-generation.json", append(b, '\n')); err != nil {
		return err
	}
	fmt.Println(string(b))
	return nil
}
