import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';import {cases,groups} from './cases.mjs';
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
function gcd(a,b){a=a<0n?-a:a;b=b<0n?-b:b;while(b){[a,b]=[b,a%b]}return a}
export function rational(text){
 assert.equal(typeof text,'string');assert(text.length<80);
 if(text.includes('/')){const p=text.split('/');assert.equal(p.length,2);assert(p.every(s=>/^-?\d+$/.test(s)));let n=BigInt(p[0]),d=BigInt(p[1]);assert(d!==0n);if(d<0n){n=-n;d=-d}const g=gcd(n,d);return [n/g,d/g]}
 assert(/^-?(?:\d+(?:\.\d*)?|\.\d+)$/.test(text));const negative=text.startsWith('-'),s=negative?text.slice(1):text,[whole,part='']=s.split('.');const d=10n**BigInt(part.length),n=BigInt((whole||'0')+part)*(negative?-1n:1n),g=gcd(n,d);return [n/g,d/g];
}
export function evaluate(c){const [x,xd]=rational(c.input),[s,sd]=rational(c.scale),[o,od]=rational(c.offset),n=x*s*od+o*xd*sd,d=xd*sd*od,g=gcd(n,d);return {numerator:String(n/g),denominator:String(d/g)}}
function decimal(v){let n=BigInt(v.numerator),d=BigInt(v.denominator);if(d===1n)return String(n);let k=d;while(k%2n===0n)k/=2n;while(k%5n===0n)k/=5n;if(k!==1n)return v.numerator+'/'+v.denominator;const sign=n<0n?'-':'';if(n<0n)n=-n;let out=String(n/d),r=n%d;if(r){out+='.';while(r){r*=10n;out+=String(r/d);r%=d}}return sign+out}
export function prepare(){const corpus=[],queries=[],oracle=[];for(const c of cases){const value=evaluate(c),numeric=Number(value.numerator)/Number(value.denominator);assert(Math.abs(numeric-c.reference)<=1e-12*Math.max(1,Math.abs(c.reference)),'source arithmetic '+c.from);const output=decimal(value),id=hash('metrology-record:'+c.group+'/'+c.from+'/'+c.to).slice(0,24),text='NIST unit conversion: '+c.input+' '+c.from+' equals '+output+' '+c.to+'.';assert(text.length<240&&/^[\x00-\x7f]*$/.test(text));corpus.push({id,text,frame:{who:'unit definitions',what:c.group+': '+c.from+' to '+c.to,where:'measurement conventions',when:c.group==='legacy survey length'?'legacy survey definition':'declared unit definition',why:'preserve quantity and convention',how:c.input+' '+c.from+' equals '+output+' '+c.to},metadata:{source:c.source,exact_value:value,from:c.from,to:c.to,input:c.input,scale:c.scale,offset:c.offset}});for(const[wording,q]of [['literal','Convert '+c.input+' '+c.from+' to '+c.to+' under the specified convention.'],['paraphrase',c.paraphrase]]){const qid=hash('metrology-question:'+wording+':'+q).slice(0,24);queries.push({id:qid,split:c.split,wording,text:q});oracle.push({question_id:qid,target_id:id,cluster:c.group,split:c.split,from:c.from,to:c.to,input:c.input,observable:value})}}
 assert.equal(corpus.length,36);assert.equal(queries.length,72);assert.equal(new Set(corpus.map(c=>c.id)).size,36);assert.equal(new Set(queries.map(q=>q.id)).size,72);return {corpus,queries,oracle,clusters:groups.length}}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){const dir='research/public-task-pilot/metrology-transfer-v1/prepared';fs.mkdirSync(dir,{recursive:true});const result=prepare(),sources={},artifacts={};for(const p of ['cases.mjs','prepare.mjs','prepare.test.mjs','PROTOCOL.md'])sources[p]=hash(fs.readFileSync(new URL(p,import.meta.url)));fs.writeFileSync(dir+'/freeze.json',JSON.stringify({time:new Date().toISOString(),sources,node:process.version,model_fitting:false,whole_goal_complete:false},null,2)+'\n',{flag:'wx',mode:0o600});for(const name of ['corpus','queries','oracle']){const b=JSON.stringify(result[name],null,2)+'\n';fs.writeFileSync(dir+'/'+name+'.json',b,{flag:'wx',mode:0o600});artifacts[name]=hash(b)}const report={time:new Date().toISOString(),corpus:36,questions:72,clusters:12,split_clusters:{design:6,confirmation:6},artifacts,retrieval_runs:0,whole_goal_complete:false};fs.writeFileSync(dir+'/prepared.json',JSON.stringify(report,null,2)+'\n',{flag:'wx',mode:0o600});console.log(JSON.stringify(report,null,2))}
