// Code generated by research-memo-normal-gen; DO NOT EDIT.
package researchswitch

import (
	"bufio"
	"encoding/json"
	"io"
	"os"
	"testing"
)

func TestMemoV49Normal(t *testing.T) {
	input, out := os.Getenv("EVENTFRAME_HYBRID_V48_FIXTURE"), os.Getenv("EVENTFRAME_HYBRID_V48_OUT")
	if out == "" {
		t.Skip("explicit study output required")
	}
	f, err := os.Open(input)
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	w, err := os.OpenFile(out, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600)
	if err != nil {
		t.Fatal(err)
	}
	defer w.Close()
	d := json.NewDecoder(bufio.NewReader(f))
	b := bufio.NewWriter(w)
	e := json.NewEncoder(b)
	var manifest map[string]any
	if err = d.Decode(&manifest); err != nil {
		t.Fatal(err)
	}
	manifest["Kind"] = "hybrid_study_manifest"
	if err = e.Encode(manifest); err != nil {
		t.Fatal(err)
	}
	for {
		var fixture studyFixture
		if err = d.Decode(&fixture); err == io.EOF {
			break
		} else if err != nil {
			t.Fatal(err)
		}
		r := hybridRecordV48{Seed: fixture.World.Population.Seed}
		for s := 0; s < 3; s++ {
			for _, mode := range hybridModesV48 {
				a, err := collectMemoV49(fixture, mode, s)
				if err != nil {
					t.Fatal(err)
				}
				r.Arms = append(r.Arms, a)
			}
		}
		if err = e.Encode(r); err != nil {
			t.Fatal(err)
		}
		t.Log(fixture.World.Population.Geometry + "/" + fixture.World.Population.Regime)
	}
	if err = b.Flush(); err != nil {
		t.Fatal(err)
	}
	if err = w.Sync(); err != nil {
		t.Fatal(err)
	}
}
