// Research generated fork: strategy-loss messages, not a joint Bayesian posterior.
// Code generated by research-compact-mixer-gen; DO NOT EDIT.
// Original SHA256: 15a58956e31162d35f141503615196f3d3b65d064bed3e8366484d22e476428e
// Package researchswitch implements an isolated delayed Bernoulli expert-state
// filter. It is not a production learner, Anti-Pigeon certificate, or detector.
package researchswitch

import (
	"errors"
	"math"
	"sort"
)

const scoreExpertsV51, scoreTrialsV51 = 3, 4096
const scoreFloorV51 = 1e-6

type scoreConfigV51 struct {
	Prior           []float64
	Hazard          float64
	Trials, Pending int
	Mode            string
}

type scoreRowV51 struct {
	advice, logPosterior [scoreExpertsV51]float64
	at                   int64
	forecast             float64
	status               uint8
	useful               bool
}

type scoreModelV51 struct {
	prior, logPrior [scoreExpertsV51]float64
	logReset        [scoreExpertsV51]float64
	logStay         float64
	rows            []scoreRowV51
	work            [][scoreExpertsV51]float64
	known           []int
	hazard          float64
	epoch           uint64
	clock           int64
	n, used, cap    int
	pending         int
	mode            string
}

// Tickets are opaque, owner/epoch-bound handles to privately retained advice.
// Callers cannot replace original predictions when delayed evidence arrives.
type scoreTicketV51 struct {
	owner *scoreModelV51
	epoch uint64
	slot  int
	q     float64
}

func (t scoreTicketV51) Forecast() float64 { return t.q }

type scoreReceiptV51 struct {
	Epoch               uint64
	TrialOrdinal        int
	IssuedAt, ArrivedAt int64
	Forecast            float64
	Useful              bool
}

func scoreFiniteV51(x float64) bool { return !math.IsNaN(x) && !math.IsInf(x, 0) }

func newScoreV51(cfg scoreConfigV51, epoch uint64) (*scoreModelV51, error) {
	if !validScoreModeV51(cfg.Mode) {
		return nil, errors.New("invalid score mode")
	}

	if len(cfg.Prior) < 2 || len(cfg.Prior) > scoreExpertsV51 || !scoreFiniteV51(cfg.Hazard) || cfg.Hazard < 0 || cfg.Hazard > 1 || cfg.Trials < 1 || cfg.Trials > scoreTrialsV51 || cfg.Pending < 1 || cfg.Pending > cfg.Trials || epoch == 0 {
		return nil, errors.New("invalid switching contract")
	}
	sum := 0.
	for _, w := range cfg.Prior {
		if !scoreFiniteV51(w) || w <= 0 || w > 1 {
			return nil, errors.New("invalid expert prior")
		}
		sum += w
	}
	if math.Abs(sum-1) > 1e-12 {
		return nil, errors.New("expert prior must sum to one")
	}
	m := &scoreModelV51{rows: make([]scoreRowV51, cfg.Trials), work: make([][scoreExpertsV51]float64, cfg.Trials), known: make([]int, 0, cfg.Trials), hazard: cfg.Hazard, epoch: epoch, n: len(cfg.Prior), cap: cfg.Pending, mode: cfg.Mode}
	copy(m.prior[:], cfg.Prior)
	// Normalize accepted round-off once so unit-likelihood transitions remain
	// probability laws even at the configured simplex tolerance.
	for i := 0; i < m.n; i++ {
		m.prior[i] /= sum
		m.logPrior[i] = math.Log(m.prior[i])
	}
	// The hazard and prior are immutable within an epoch. Cache only their
	// transition constants; retain the original floating-point expression.
	if m.hazard > 0 && m.hazard < 1 {
		m.logStay = math.Log1p(-m.hazard)
		for i := 0; i < m.n; i++ {
			m.logReset[i] = math.Log(m.hazard) + m.logPrior[i]
		}
	}
	return m, nil
}

func (m *scoreModelV51) transitionLogs(previous [scoreExpertsV51]float64) [scoreExpertsV51]float64 {
	if m.hazard == 0 {
		return previous
	}
	if m.hazard == 1 {
		return m.logPrior
	}
	var next [scoreExpertsV51]float64
	for i := 0; i < m.n; i++ {
		a, b := m.logStay+previous[i], m.logReset[i]
		maximum := math.Max(a, b)
		next[i] = maximum + math.Log(math.Exp(a-maximum)+math.Exp(b-maximum))
	}
	return next
}

func (m *scoreModelV51) nextLogs() [scoreExpertsV51]float64 {
	if m.used == 0 {
		return m.logPrior
	}
	return m.transitionLogs(m.logsAt(m.used - 1))
}

// Unknown/cancelled positions have unit likelihood. The reset-prior matrix
// composes exactly: T^k = (1-alpha)^k I + (1-(1-alpha)^k) 1*pi.
// Expm1 retains small reset mass; zero/full hazard remain exact endpoints.
func (m *scoreModelV51) advanceLogs(previous [scoreExpertsV51]float64, steps int) [scoreExpertsV51]float64 {
	if steps == 0 || m.hazard == 0 {
		return previous
	}
	if steps == 1 {
		return m.transitionLogs(previous)
	}
	if m.hazard == 1 {
		return m.logPrior
	}
	stay := float64(steps) * m.logStay
	reset := math.Log(-math.Expm1(stay))
	var next [scoreExpertsV51]float64
	for i := 0; i < m.n; i++ {
		a, b := stay+previous[i], reset+m.logPrior[i]
		maximum := math.Max(a, b)
		next[i] = maximum + math.Log(math.Exp(a-maximum)+math.Exp(b-maximum))
	}
	return next
}

func (m *scoreModelV51) logsAt(slot int) [scoreExpertsV51]float64 {
	k := sort.SearchInts(m.known, slot+1) - 1
	if k < 0 {
		// Position zero has the prior without a preceding transition.
		return m.advanceLogs(m.logPrior, slot)
	}
	anchor := m.known[k]
	return m.advanceLogs(m.rows[anchor].logPosterior, slot-anchor)
}

// Linear weights may round to zero for output, but finite latent log weights
// MUST remain recoverable after contrary evidence. Do not feed rounded masses
// back into the filter; that would make zero an unintended absorbing state.
func (m *scoreModelV51) probabilities(logs [scoreExpertsV51]float64) [scoreExpertsV51]float64 {
	var weights [scoreExpertsV51]float64
	for i := 0; i < m.n; i++ {
		weights[i] = math.Exp(logs[i])
	}
	return weights
}

// Advice must be produced from the caller's AS-OF visible history by all
// experts. Their generation/training cost is additional to this filter cost.
func (m *scoreModelV51) Predict(advice []float64) (float64, error) {
	if len(advice) != m.n {
		return 0, errors.New("expert advice arity")
	}
	w := m.probabilities(m.nextLogs())
	q := 0.
	for i, p := range advice {
		if !scoreFiniteV51(p) || p < scoreFloorV51 || p > 1-scoreFloorV51 || !scoreFiniteV51(w[i]) || w[i] < 0 {
			return 0, errors.New("invalid expert prediction")
		}
		q += w[i] * p
	}
	if !scoreFiniteV51(q) || q <= 0 || q >= 1 {
		return 0, errors.New("invalid switched forecast")
	}
	return m.scoredForecastV51(advice, q)

}

func (m *scoreModelV51) Issue(advice []float64, at int64) (scoreTicketV51, error) {
	if at < m.clock || m.used == len(m.rows) || m.pending == m.cap {
		return scoreTicketV51{}, errors.New("invalid or capped switching issue")
	}
	q, err := m.Predict(advice)
	if err != nil {
		return scoreTicketV51{}, err
	}
	r := scoreRowV51{at: at, forecast: q, status: 1, logPosterior: m.nextLogs()}
	copy(r.advice[:], advice)
	slot := m.used
	m.rows[slot] = r
	m.used++
	m.pending++
	m.clock = at
	return scoreTicketV51{m, m.epoch, slot, q}, nil
}

func (m *scoreModelV51) validate(t scoreTicketV51, at int64) error {
	if t.owner != m || t.epoch != m.epoch || t.slot < 0 || t.slot >= m.used || at < m.clock || at < m.rows[t.slot].at || m.rows[t.slot].status != 1 {
		return errors.New("invalid switching owner epoch time or status")
	}
	return nil
}

// Replay at ORIGINAL nomination positions, never arrival order. Cached expert
// advice is immutable; only hidden-state forward messages may be revised.
// Scratch messages make a numerical failure atomic. Unknown/cancelled spans
// consume every original transition but need no per-position replay.
func (m *scoreModelV51) Resolve(t scoreTicketV51, useful bool, at int64) (scoreReceiptV51, error) {
	if err := m.validate(t, at); err != nil {
		return scoreReceiptV51{}, err
	}
	insert := sort.SearchInts(m.known, t.slot)
	previous, position := m.logPrior, 0
	if insert > 0 {
		position = m.known[insert-1]
		previous = m.rows[position].logPosterior
	}
	for k := insert; k <= len(m.known); k++ {
		j := t.slot
		if k > insert {
			j = m.known[k-1]
		}
		w := m.advanceLogs(previous, j-position)
		r := m.rows[j]
		y := r.useful
		if j == t.slot {
			y = useful
		}
		for i := 0; i < m.n; i++ {
			p := r.advice[i]
			if !y {
				p = 1 - p
			}
			if !scoreFiniteV51(p) || p < scoreFloorV51/2 || p > 1 {
				return scoreReceiptV51{}, errors.New("invalid retained expert likelihood")
			}
			w[i] += scoreEmissionV51(m.mode, p)

		}
		maximum := math.Inf(-1)
		for i := 0; i < m.n; i++ {
			if !scoreFiniteV51(w[i]) {
				return scoreReceiptV51{}, errors.New("invalid forward message")
			}
			maximum = math.Max(maximum, w[i])
		}
		sum := 0.
		for i := 0; i < m.n; i++ {
			sum += math.Exp(w[i] - maximum)
		}
		if !scoreFiniteV51(sum) || sum <= 0 {
			return scoreReceiptV51{}, errors.New("invalid switching normalization")
		}
		normalizer := maximum + math.Log(sum)
		for i := 0; i < m.n; i++ {
			w[i] -= normalizer
		}
		m.work[j] = w
		previous, position = w, j
	}
	for k := insert; k <= len(m.known); k++ {
		j := t.slot
		if k > insert {
			j = m.known[k-1]
		}
		m.rows[j].logPosterior = m.work[j]
	}
	m.known = append(m.known, 0)
	copy(m.known[insert+1:], m.known[insert:])
	m.known[insert] = t.slot
	r := m.rows[t.slot]
	m.rows[t.slot].status, m.rows[t.slot].useful = 2, useful
	m.pending--
	m.clock = at
	return scoreReceiptV51{m.epoch, t.slot + 1, r.at, at, r.forecast, useful}, nil
}

func (m *scoreModelV51) Cancel(t scoreTicketV51, at int64) error {
	if err := m.validate(t, at); err != nil {
		return err
	}
	m.rows[t.slot].status = 3
	m.pending--
	m.clock = at
	return nil
}

func (m *scoreModelV51) Pending() int { return m.pending }

func (m *scoreModelV51) BeginEpoch(epoch uint64, at int64) error {
	if epoch <= m.epoch || at < m.clock {
		return errors.New("invalid switching epoch")
	}
	cfg := scoreConfigV51{Prior: append([]float64(nil), m.prior[:m.n]...), Hazard: m.hazard, Trials: len(m.rows), Pending: m.cap, Mode: m.mode}
	next, err := newScoreV51(cfg, epoch)
	if err != nil {
		return err
	}
	next.clock = at
	*m = *next
	return nil
}
