// Code generated by scored-v52-gen.mjs; DO NOT EDIT.
package researchswitch

import "errors"

// ScoredHybridV52 aligns all mixture heads, not the statistical child learners.
// Nested strategy weights do not assert independent Bayesian evidence copies.
type ScoredHybridV52 struct {
	local        *scoreLocalV52
	global       *scoreModelV51
	scope        *scoreModelV51
	globalHazard float64
	scopeHazard  float64
	scoreMode    string
}

type ScoredHybridTicketV52 struct {
	owner *ScoredHybridV52
	epoch uint64
	slot  int
	q     float64
}

func (t ScoredHybridTicketV52) Forecast() float64 { return t.q }

func NewScoredHybridV52(base []float64, cfg Config, memberTrials int, globalHazard, scopeHazard float64, epoch uint64, mode string) (*ScoredHybridV52, error) {
	globalCfg := cfg
	globalCfg.Hazard = globalHazard
	global, err := newScoreV51(scoreConfigV51{Prior: globalCfg.Prior, Hazard: globalCfg.Hazard, Trials: globalCfg.Trials, Pending: globalCfg.Pending, Mode: mode}, epoch)
	if err != nil {
		return nil, err
	}
	scope, err := newScoreV51(scoreConfigV51{Prior: []float64{.9, .1}, Hazard: scopeHazard, Trials: cfg.Trials, Pending: cfg.Pending, Mode: mode}, epoch)
	if err != nil {
		return nil, err
	}
	local, err := NewscoreLocalV52(base, cfg, memberTrials, epoch, mode)
	if err != nil {
		return nil, err
	}
	return &ScoredHybridV52{local, global, scope, globalHazard, scopeHazard, mode}, nil
}

func (p *ScoredHybridV52) advice(member int) ([3]float64, [2]float64, error) {
	q, err := p.local.advice(member)
	var heads [2]float64
	if err != nil {
		return q, heads, err
	}
	heads[0], err = p.global.Predict(q[:])
	if err == nil {
		heads[1], err = p.local.mixes[member].Predict(q[:])
	}
	return q, heads, err
}

func (p *ScoredHybridV52) Predict(member int) (float64, error) {
	_, heads, err := p.advice(member)
	if err != nil {
		return 0, err
	}
	return p.scope.Predict(heads[:])
}

// All three levels retain AS-OF original advice. An unexpected partial child
// failure fences the entire bundle; this is not cross-model atomic rollback.
func (p *ScoredHybridV52) Issue(member int, at int64) (ScoredHybridTicketV52, error) {
	l := p.local
	if l.poison || member < 0 || member >= len(l.base) || at < l.clock || l.used == len(l.rows) || l.pending == l.cfg.Pending || l.issued[member] == l.memberTrials {
		return ScoredHybridTicketV52{}, errors.New("invalid or capped scored issue")
	}
	q, heads, err := p.advice(member)
	if err != nil {
		return ScoredHybridTicketV52{}, err
	}
	if _, err = p.scope.Predict(heads[:]); err != nil {
		return ScoredHybridTicketV52{}, err
	}
	lt, err := l.Issue(member, at)
	var gt scoreTicketV51
	var st scoreTicketV51
	if err == nil {
		gt, err = p.global.Issue(q[:], at)
	}
	if err == nil {
		st, err = p.scope.Issue(heads[:], at)
	}
	if err != nil {
		l.poison, l.clock = true, at
		return ScoredHybridTicketV52{}, err
	}
	if lt.Forecast() != heads[1] || gt.Forecast() != heads[0] || lt.slot != gt.slot || gt.slot != st.slot {
		l.poison, l.clock = true, at
		return ScoredHybridTicketV52{}, errors.New("scored advice or position changed")
	}
	return ScoredHybridTicketV52{p, l.epoch, lt.slot, st.Forecast()}, nil
}

func (p *ScoredHybridV52) validate(t ScoredHybridTicketV52, at int64) error {
	if t.owner != p || t.epoch != p.local.epoch {
		return errors.New("scored owner or epoch")
	}
	return p.local.validate(scoreLocalTicketV52{owner: p.local, epoch: t.epoch, slot: t.slot}, at)
}

func (p *ScoredHybridV52) Resolve(t ScoredHybridTicketV52, useful bool, at int64) (PoolReceipt, error) {
	if err := p.validate(t, at); err != nil {
		return PoolReceipt{}, err
	}
	l := p.local
	r, err := l.Resolve(scoreLocalTicketV52{owner: l, epoch: t.epoch, slot: t.slot}, useful, at)
	if err == nil {
		_, err = p.global.Resolve(scoreTicketV51{owner: p.global, epoch: t.epoch, slot: t.slot}, useful, at)
	}
	var receipt scoreReceiptV51
	if err == nil {
		receipt, err = p.scope.Resolve(scoreTicketV51{owner: p.scope, epoch: t.epoch, slot: t.slot}, useful, at)
	}
	if err != nil {
		l.poison, l.clock = true, at
		return PoolReceipt{}, err
	}
	// The receipt is the served outer law, never an auxiliary head's forecast.
	r.Receipt = Receipt(receipt)
	return r, nil
}

func (p *ScoredHybridV52) Cancel(t ScoredHybridTicketV52, at int64) error {
	if err := p.validate(t, at); err != nil {
		return err
	}
	l := p.local
	err := l.Cancel(scoreLocalTicketV52{owner: l, epoch: t.epoch, slot: t.slot}, at)
	if err == nil {
		err = p.global.Cancel(scoreTicketV51{owner: p.global, epoch: t.epoch, slot: t.slot}, at)
	}
	if err == nil {
		err = p.scope.Cancel(scoreTicketV51{owner: p.scope, epoch: t.epoch, slot: t.slot}, at)
	}
	if err != nil {
		l.poison, l.clock = true, at
	}
	return err
}

func (p *ScoredHybridV52) Pending() int { return p.local.Pending() }

func (p *ScoredHybridV52) BeginEpoch(epoch uint64, at int64) error {
	l := p.local
	if epoch <= l.epoch || at < l.clock {
		return errors.New("invalid scored epoch")
	}
	next, err := NewScoredHybridV52(l.base, l.cfg, l.memberTrials, p.globalHazard, p.scopeHazard, epoch, p.scoreMode)
	if err != nil {
		return err
	}
	next.local.clock, next.global.clock, next.scope.clock = at, at, at
	*p = *next
	return nil
}
