// Code generated by scored-v52-gen.mjs; DO NOT EDIT.
package researchswitch

import "time"

func collectScoredV52(f studyFixture, mode string, s int, style string) (hybridArmV48, error) {
	a := hybridArmV48{Mode: mode, Schedule: studySchedules[s], Issued: make([]float64, 2400), Advice: make([][3]float64, 2400), Heads: make([][2]float64, 2400)}
	alpha, err := hybridHazardV48(mode)
	if err != nil {
		return a, err
	}
	started, phase := time.Now(), time.Now()
	p, err := NewScoredHybridV52(f.World.Population.Base, Config{Prior: []float64{.8, .1, .1}, Hazard: 1. / 16, Trials: 2400, Pending: 2400}, 16, 1./2400, alpha, 1, style)
	a.Costs.SetupNS = time.Since(phase).Nanoseconds()
	if err != nil {
		return a, err
	}
	tickets := make([]ScoredHybridTicketV52, 2400)
	due := f.Due[s]
	last := len(due) - 1
	for len(due[last]) == 0 {
		last--
	}
	for tick := 0; tick <= last; tick++ {
		if tick < 2400 {
			phase = time.Now()
			ticket, e := p.Issue(tick%150, int64(tick))
			if e != nil {
				return a, e
			}
			tickets[tick], a.Issued[tick] = ticket, ticket.Forecast()
			copy(a.Advice[tick][:], p.global.rows[tick].advice[:3])
			copy(a.Heads[tick][:], p.scope.rows[tick].advice[:2])
			a.PeakPending = max(a.PeakPending, p.Pending())
			a.Costs.IssueNS += time.Since(phase).Nanoseconds()
		}
		for _, trial := range due[tick] {
			phase = time.Now()
			r, e := p.Resolve(tickets[trial], f.World.Population.Outcomes[trial/150][trial%150], int64(tick))
			if e != nil {
				return a, e
			}
			a.Receipts = append(a.Receipts, r)
			a.Costs.ResolveNS += time.Since(phase).Nanoseconds()
		}
		if (tick < 2400 && tick%150 == 149) || tick == last {
			phase = time.Now()
			snap := hybridSnapshotV48{Tick: tick, Arrived: len(a.Receipts), Pending: p.Pending(), Forecast: make([]float64, 150), Advice: make([][3]float64, 150), Weights: make([][3]float64, 150), Heads: make([][2]float64, 150)}
			gw := p.global.probabilities(p.global.nextLogs())
			sw := p.scope.probabilities(p.scope.nextLogs())
			copy(snap.GlobalWeights[:], gw[:3])
			copy(snap.ScopeWeights[:], sw[:2])
			for m := range snap.Forecast {
				q, heads, e := p.advice(m)
				if e != nil {
					return a, e
				}
				snap.Advice[m] = q
				snap.Heads[m] = heads
				weights := p.local.mixes[m].probabilities(p.local.mixes[m].nextLogs())
				copy(snap.Weights[m][:], weights[:3])
				snap.Forecast[m], e = p.scope.Predict(heads[:])
				if e != nil {
					return a, e
				}
			}
			a.Snapshots = append(a.Snapshots, snap)
			a.Costs.SnapshotNS += time.Since(phase).Nanoseconds()
		}
	}
	a.Costs.AccountedNS = a.Costs.SetupNS + a.Costs.IssueNS + a.Costs.ResolveNS + a.Costs.SnapshotNS
	a.Costs.ElapsedNS = time.Since(started).Nanoseconds()
	return a, nil
}
