// Code generated by scored-v52-gen.mjs; DO NOT EDIT.
package researchswitch

import (
	"fmt"
	"github.com/JuanHuaXu/eventframed/internal/researchscoreref"
)

func auditScoredV52(f studyFixture, a hybridArmV48, s int, style string) error {
	alpha, err := hybridHazardV48(a.Mode)
	if err != nil {
		return err
	}
	if s < 0 || s >= 3 || len(f.Due) != 3 || len(f.World.Arms) != 9 || len(f.World.Population.Base) != 150 || len(f.World.Population.Outcomes) != 16 || a.Schedule != studySchedules[s] || len(a.Issued) != 2400 || len(a.Advice) != 2400 || len(a.Heads) != 2400 {
		return fmt.Errorf("local study domain")
	}
	for _, y := range f.World.Population.Outcomes {
		if len(y) != 150 {
			return fmt.Errorf("outcome domain")
		}
	}
	for h, mode := range []string{"full", "adaptive", "rich_moment2"} {
		c := f.World.Arms[s*3+h]
		if c.Mode != mode || c.Schedule != a.Schedule || len(c.Issued) != 2400 {
			return fmt.Errorf("control domain")
		}
	}
	c := a.Costs
	if c.SetupNS <= 0 || c.IssueNS <= 0 || c.ResolveNS <= 0 || c.SnapshotNS <= 0 || c.AccountedNS != c.SetupNS+c.IssueNS+c.ResolveNS+c.SnapshotNS || c.ElapsedNS < c.AccountedNS {
		return fmt.Errorf("cost conservation")
	}
	tapes := make([][][3]float64, 150)
	known := make([]map[int]bool, 150)
	for m := range known {
		known[m] = map[int]bool{}
	}
	prior := []float64{.8, .1, .1}
	weights := func(m int) ([3]float64, error) {
		w, err := scoreHeadWeightsV52(prior, 1./16, tapes[m], known[m], style)
		if err == nil && len(tapes[m]) > 0 {
			for h := range w {
				w[h] = (1-1./16)*w[h] + (1./16)*prior[h]
			}
		}
		return w, err
	}
	globalKnown := map[int]bool{}
	var globalTape [][3]float64
	var headTape [][]float64
	globalWeights := func() ([3]float64, error) {
		w, err := scoreHeadWeightsV52(prior, 1./2400, globalTape, globalKnown, style)
		if err == nil && len(globalTape) > 0 {
			for h := range w {
				w[h] = (1-1./2400)*w[h] + (1./2400)*prior[h]
			}
		}
		return w, err
	}
	scopeWeights := func() ([]float64, error) {
		prior := []float64{.9, .1}
		w, err := researchscoreref.End(prior, alpha, headTape, globalKnown, style)
		if err == nil && len(headTape) > 0 {
			for h := range w {
				w[h] = (1-alpha)*w[h] + alpha*prior[h]
			}
		}
		return w, err
	}
	position, snapshot, peak := 0, 0, 0
	due := f.Due[s]
	if len(due) < 2400 {
		return fmt.Errorf("arrival domain")
	}
	last := len(due) - 1
	for last >= 0 && len(due[last]) == 0 {
		last--
	}
	for tick := 0; tick <= last; tick++ {
		if tick < 2400 {
			m := tick % 150
			w, err := weights(m)
			if err != nil {
				return err
			}
			gw, err := globalWeights()
			if err != nil {
				return err
			}
			sw, err := scopeWeights()
			if err != nil {
				return err
			}
			var heads [2]float64
			for h, v := range a.Advice[tick] {
				if !studyClose(v, f.World.Arms[s*3+h].Issued[tick]) {
					return fmt.Errorf("original expert advice")
				}
				heads[0] += gw[h] * v
				heads[1] += w[h] * v
			}
			heads[0], err = researchscoreref.Forecast(gw[:], a.Advice[tick][:], style)
			if err != nil {
				return err
			}
			heads[1], err = researchscoreref.Forecast(w[:], a.Advice[tick][:], style)
			if err != nil {
				return err
			}
			for h := range heads {
				if !studyClose(heads[h], a.Heads[tick][h]) {
					return fmt.Errorf("original head advice")
				}
			}
			q, err := researchscoreref.
				Forecast(sw, heads[:], style)
			if err !=
				nil {
				return err
			}

			if !studyClose(q, a.Issued[tick]) {
				return fmt.Errorf("independent issued mixture")
			}
			tapes[m] = append(tapes[m], a.Advice[tick])
			globalTape = append(globalTape, a.Advice[tick])
			headTape = append(headTape, a.Heads[tick][:])
			peak = max(peak, tick+1-position)
		}
		for _, trial := range due[tick] {
			if trial < 0 || trial >= min(tick+1, 2400) || position >= len(a.Receipts) {
				return fmt.Errorf("future or missing receipt")
			}
			r := a.Receipts[position]
			if r.Epoch != 1 || r.TrialOrdinal != trial+1 || r.Member != trial%150 || r.MemberOrdinal != trial/150+1 || r.IssuedAt != int64(trial) || r.ArrivedAt != int64(tick) || r.Forecast != a.Issued[trial] || r.Useful != f.World.Population.Outcomes[trial/150][trial%150] {
				return fmt.Errorf("original receipt identity")
			}
			if _, ok := known[trial%150][trial/150]; ok {
				return fmt.Errorf("duplicate receipt")
			}
			known[trial%150][trial/150] = r.Useful
			globalKnown[trial] = r.Useful
			position++
		}
		if (tick < 2400 && tick%150 == 149) || tick == last {
			if snapshot >= len(a.Snapshots) {
				return fmt.Errorf("missing snapshot")
			}
			snap := a.Snapshots[snapshot]
			if snap.Tick != tick || snap.Arrived != position || snap.Pending != min(tick+1, 2400)-position || len(snap.Advice) != 150 || len(snap.Forecast) != 150 || len(snap.Weights) != 150 || len(snap.Heads) != 150 {
				return fmt.Errorf("snapshot coverage")
			}
			gw, err := globalWeights()
			if err != nil {
				return err
			}
			sw, err := scopeWeights()
			if err != nil {
				return err
			}
			for h := range gw {
				if !studyClose(gw[h], snap.GlobalWeights[h]) {
					return fmt.Errorf("global snapshot weights")
				}
			}
			for h := range sw {
				if !studyClose(sw[h], snap.ScopeWeights[h]) {
					return fmt.Errorf("scope snapshot weights")
				}
			}
			for m, got := range snap.Forecast {
				w, err := weights(m)
				if err != nil {
					return err
				}
				var heads [2]float64
				for h, v := range snap.Advice[m] {
					control := f.World.Arms[s*3+h]
					if snapshot >= len(control.Snapshots) || control.Snapshots[snapshot].Tick != tick || len(control.Snapshots[snapshot].Forecast) != 150 || !studyClose(v, control.Snapshots[snapshot].Forecast[m]) || !studyClose(w[h], snap.Weights[m][h]) {
						return fmt.Errorf("snapshot expert or local weights")
					}
					heads[0] += gw[h] * v
					heads[1] += w[h] * v
				}
				heads[0], err = researchscoreref.Forecast(gw[:], snap.Advice[m][:], style)
				if err != nil {
					return err
				}
				heads[1], err = researchscoreref.Forecast(w[:], snap.Advice[m][:], style)
				if err != nil {
					return err
				}
				for h := range heads {
					if !studyClose(heads[h], snap.Heads[m][h]) {
						return fmt.Errorf("snapshot head law")
					}
				}
				q, err := researchscoreref.
					Forecast(sw, heads[:], style)
				if err !=
					nil {
					return err
				}

				if !studyClose(q, got) {
					return fmt.Errorf("independent snapshot law")
				}
			}
			snapshot++
		}
	}
	if position != 2400 || position != len(a.Receipts) || snapshot != len(a.Snapshots) || peak != a.PeakPending {
		return fmt.Errorf("complete tape coverage")
	}
	return nil
}

func scoreHeadWeightsV52(prior []float64, hazard float64, tape [][3]float64, known map[int]bool, style string) ([3]float64, error) {
	dense := make([][]float64, len(tape))
	for j := range tape {
		dense[j] = tape[j][:]
	}
	w, err := researchscoreref.End(prior, hazard, dense, known, style)
	var out [3]float64
	copy(out[:], w)
	return out, err
}
