// AST-only research fork: shrink unused expert slots, preserve all arithmetic.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/scanner"
	"go/token"
	"os"
	"reflect"
)

var names = map[string]string{"Model": "compactModelV48", "row": "compactRowV48", "Ticket": "compactTicketV48", "New": "newCompactV48", "Config": "compactConfigV48", "Receipt": "compactReceiptV48", "finite": "compactFiniteV48", "MaxExperts": "compactExpertsV48", "MaxTrials": "compactTrialsV48", "ProbabilityFloor": "compactFloorV48"}

func sha(b []byte) string { h := sha256.Sum256(b); return hex.EncodeToString(h[:]) }
func tokens(b []byte) []string {
	f := token.NewFileSet().AddFile("tokens", -1, len(b))
	var s scanner.Scanner
	s.Init(f, b, nil, 0)
	var result []string
	for {
		_, t, v := s.Scan()
		if t == token.EOF {
			return result
		}
		result = append(result, t.String()+":"+v)
	}
}
func transform(f *ast.File, inverse bool) error {
	rename := names
	old, next, value := "MaxExperts", "compactExpertsV48", "3"
	if inverse {
		rename = map[string]string{}
		for a, b := range names {
			rename[b] = a
		}
		old, next, value = next, old, "8"
	}
	changed := 0
	for _, decl := range f.Decls {
		g, ok := decl.(*ast.GenDecl)
		if !ok || g.Tok != token.CONST {
			continue
		}
		for _, spec := range g.Specs {
			v := spec.(*ast.ValueSpec)
			if len(v.Names) == 2 && v.Names[0].Name == old && len(v.Values) == 2 {
				v.Values[0] = &ast.BasicLit{Kind: token.INT, Value: value}
				changed++
			}
		}
	}
	if changed != 1 {
		return fmt.Errorf("expert capacity declaration count %d", changed)
	}
	selectors := map[*ast.Ident]bool{}
	ast.Inspect(f, func(n ast.Node) bool {
		if s, ok := n.(*ast.SelectorExpr); ok {
			selectors[s.Sel] = true
		}
		return true
	})
	ast.Inspect(f, func(n ast.Node) bool {
		if i, ok := n.(*ast.Ident); ok {
			if name, found := rename[i.Name]; found && !selectors[i] {
				i.Name = name
			}
		}
		return true
	})
	return nil
}
func exclusive(p string, b []byte) error {
	f, err := os.OpenFile(p, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600)
	if err != nil {
		return err
	}
	defer f.Close()
	if _, err = f.Write(b); err != nil {
		return err
	}
	return f.Sync()
}
func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
func run() error {
	const source = "internal/researchswitch/model.go"
	const target = "internal/researchswitch/compact_v48_generated.go"
	original, err := os.ReadFile(source)
	if err != nil {
		return err
	}
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, source, original, parser.ParseComments)
	if err != nil {
		return err
	}
	if err = transform(f, false); err != nil {
		return err
	}
	var b bytes.Buffer
	if err = format.Node(&b, fset, f); err != nil {
		return err
	}
	body := b.Bytes()
	// Verify inverse syntax independently of comments/formatting positions.
	inverseSet := token.NewFileSet()
	inverse, err := parser.ParseFile(inverseSet, target, body, 0)
	if err != nil {
		return err
	}
	if err = transform(inverse, true); err != nil {
		return err
	}
	var back bytes.Buffer
	if err = format.Node(&back, inverseSet, inverse); err != nil {
		return err
	}
	if !reflect.DeepEqual(tokens(original), tokens(back.Bytes())) {
		return fmt.Errorf("inverse fork differs from original syntax")
	}
	generated := append([]byte("// Code generated by research-compact-mixer-gen; DO NOT EDIT.\n// Original SHA256: "+sha(original)+"\n"), body...)
	if err = exclusive(target, generated); err != nil {
		return err
	}
	metadata, err := json.MarshalIndent(map[string]any{"source": source, "target": target, "sourceSHA256": sha(original), "targetSHA256": sha(generated), "expertSlots": 3, "renames": names, "inverseSyntaxIdentical": true}, "", "  ")
	if err != nil {
		return err
	}
	if err = exclusive("research/compact-v48-generation.json", append(metadata, '\n')); err != nil {
		return err
	}
	fmt.Println(string(metadata))
	return nil
}
